import { createHash, createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import type { LedgerStore } from './store';
import { ApiError } from './errors';
import { decryptMfaSecret, encryptMfaSecret } from './mfa-crypto';

type CookieStage='enroll'|'verify'|'owner';
type MfaRecord={id:string;encrypted_secret:string;confirmed:number;last_counter:number;recovery_hashes:string;updated_at:string};
type PasswordRecord={id:string;email:string;salt:string;password_hash:string;session_version:number;must_change:number;updated_at:string};
type SetupRecord={id:string;token_hash:string;expires_at:string};
const COOKIE='agora_session';
const PENDING_COOKIE='agora_pending';
const base32Alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
const now=()=>new Date().toISOString();
const apiError=(status:number,code:string,message:string)=>new ApiError(status,code,message);
function sessionKey(){const key=process.env.AGORA_ADMIN_TOKEN;if(!key||key.length<32)throw apiError(503,'auth_not_configured','Set AGORA_ADMIN_TOKEN to at least 32 characters before enabling owner login.');return key;}
function encodeBase32(input:Uint8Array){let bits=0,value=0,out='';for(const b of input){value=(value<<8)|b;bits+=8;while(bits>=5){out+=base32Alphabet[(value>>>(bits-5))&31];bits-=5;}}if(bits)out+=base32Alphabet[(value<<(5-bits))&31];return out;}
function decodeBase32(input:string){let bits=0,value=0;const out:number[]=[];for(const c of input.replace(/=+$/,'').toUpperCase()){const n=base32Alphabet.indexOf(c);if(n<0)throw apiError(500,'mfa_secret_invalid','The saved authenticator secret is invalid.');value=(value<<5)|n;bits+=5;if(bits>=8){out.push((value>>>(bits-8))&255);bits-=8;}}return Buffer.from(out);}
function totp(secret:string,counter:number){const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(counter));const digest=createHmac('sha1',decodeBase32(secret)).update(b).digest();const offset=digest[digest.length-1]&15;const n=(digest.readUInt32BE(offset)&0x7fffffff)%1_000_000;return String(n).padStart(6,'0');}
function verifiedCounter(secret:string,code:string,lastCounter:number){if(!/^\d{6}$/.test(code))return null;const current=Math.floor(Date.now()/30_000);for(const counter of [current-1,current,current+1]){const expected=Buffer.from(totp(secret,counter));const actual=Buffer.from(code);if(counter>lastCounter&&timingSafeEqual(expected,actual))return counter;}return null;}
function passwordRecord(store:LedgerStore){return store.one<PasswordRecord>("SELECT * FROM owner_password WHERE id='owner'");}
function setupRecord(store:LedgerStore){return store.one<SetupRecord>("SELECT * FROM owner_setup WHERE id='owner'");}
export function ownerLoginEmail(store:LedgerStore){return passwordRecord(store)?.email||process.env.AGORA_OWNER_EMAIL||'';}
function makeCookie(stage:CookieStage,store?:LedgerStore){const expires=Math.floor(Date.now()/1000)+(stage==='owner'?12*60*60:10*60);const version=stage==='owner'?(passwordRecord(store!)?.session_version||0):0;const nonce=randomBytes(16).toString('base64url');const payload=`${stage}.${expires}.${version}.${nonce}`;const signature=createHmac('sha256',sessionKey()).update(payload).digest('base64url');return{value:`${payload}.${signature}`,expires};}
function cookieValue(request:Request,name:string){return request.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(`${name}=`))?.slice(name.length+1);}
function verifyRawCookie(raw:string|undefined){if(!raw)return null;const [stage,expiry,version,nonce,signature,...rest]=raw.split('.');if(!stage||!expiry||!version||!nonce||!signature||rest.length||!['enroll','verify','owner'].includes(stage)||!/^\d+$/.test(expiry)||!/^\d+$/.test(version)||Number(expiry)<=Math.floor(Date.now()/1000))return null;const payload=`${stage}.${expiry}.${version}.${nonce}`;try{const a=Buffer.from(createHmac('sha256',sessionKey()).update(payload).digest('base64url'));const b=Buffer.from(signature);return a.length===b.length&&timingSafeEqual(a,b)?{stage:stage as CookieStage,expires:Number(expiry),version:Number(version)}:null;}catch{return null}}
function cookieStage(request:Request){return verifyRawCookie(cookieValue(request,PENDING_COOKIE)||cookieValue(request,COOKIE))?.stage||null;}
export function isAdminSession(store:LedgerStore,request:Request){const raw=cookieValue(request,COOKIE),cookie=verifyRawCookie(raw);if(cookie?.stage!=='owner'||!raw)return false;const password=passwordRecord(store);if(password&&password.session_version!==cookie.version)return false;return !store.one('SELECT token_hash FROM revoked_sessions WHERE token_hash=?',hash(raw));}
export function revokeAdminSession(store:LedgerStore,request:Request){for(const name of [COOKIE,PENDING_COOKIE]){const raw=cookieValue(request,name),valid=verifyRawCookie(raw);if(raw&&valid){store.run('INSERT OR REPLACE INTO revoked_sessions(token_hash,expires_at) VALUES(?,?)',hash(raw),valid.expires);}}store.run('DELETE FROM revoked_sessions WHERE expires_at<?',Math.floor(Date.now()/1000));}
export function pendingMfaStage(request:Request){const stage=verifyRawCookie(cookieValue(request,PENDING_COOKIE))?.stage;return stage==='enroll'||stage==='verify'?stage:null;}
export function setMfaCookie(response:Response,request:Request,scope:'owner'|'pending',session?:{value:string;expires:number}){const secure=new URL(request.url).protocol==='https:'||process.env.NODE_ENV==='production';const name=scope==='owner'?COOKIE:PENDING_COOKIE;const maxAge=session?Math.max(0,session.expires-Math.floor(Date.now()/1000)):0;const value=session?.value||'';const sameSite=scope==='owner'?'Lax':'Strict';response.headers.append('Set-Cookie',`${name}=${value}; Path=/; HttpOnly; SameSite=${sameSite}; Max-Age=${maxAge}${secure?'; Secure':''}`);return response;}
function allowedOrigin(request:Request,required=true){const configured=process.env.AGORA_PUBLIC_ORIGIN;let expected:URL;try{expected=new URL(configured||request.url)}catch{throw apiError(503,'auth_not_configured','The configured browser origin must be a valid URL.');}if(configured&&(expected.origin!==configured.replace(/\/$/,'')||!['https:','http:'].includes(expected.protocol)))throw apiError(503,'auth_not_configured','The configured browser origin must contain only scheme and host.');const origin=request.headers.get('origin');if(required&&!origin)throw apiError(403,'origin_rejected','A same-origin request is required.');if(origin&&origin!==expected.origin)throw apiError(403,'origin_rejected','Use the configured same-origin console.');if(request.headers.get('sec-fetch-site')==='cross-site')throw apiError(403,'origin_rejected','Cross-site console requests are rejected.');}
function rateBucket(request:Request){const ip=request.headers.get('cf-connecting-ip')||request.headers.get('x-forwarded-for')?.split(',').at(-1)?.trim()||'unknown';return `owner-auth:${hash(ip)}`;}
function checkRate(store:LedgerStore,request:Request){const row=store.one<{attempts:number;window_started:number;locked_until:number}>('SELECT attempts,window_started,locked_until FROM auth_rate_limits WHERE bucket=?',rateBucket(request));const nowSeconds=Math.floor(Date.now()/1000);if(row&&row.locked_until>nowSeconds)throw apiError(429,'rate_limited','Too many authentication attempts. Try again later.');if(row&&nowSeconds-row.window_started<900&&row.attempts>=5)throw apiError(429,'rate_limited','Too many authentication attempts. Try again later.');}
function recordFailure(store:LedgerStore,request:Request){const bucket=rateBucket(request);const nowSeconds=Math.floor(Date.now()/1000);const r=store.one<{attempts:number;window_started:number}>('SELECT attempts,window_started FROM auth_rate_limits WHERE bucket=?',bucket);const attempts=r&&nowSeconds-r.window_started<900?r.attempts+1:1;const start=r&&nowSeconds-r.window_started<900?r.window_started:nowSeconds;const locked=attempts>=10?nowSeconds+900:attempts>=5?nowSeconds+60:0;store.run('INSERT INTO auth_rate_limits(bucket,attempts,window_started,locked_until) VALUES(?,?,?,?) ON CONFLICT(bucket) DO UPDATE SET attempts=excluded.attempts,window_started=excluded.window_started,locked_until=excluded.locked_until',bucket,attempts,start,locked);}
function clearFailures(store:LedgerStore,request:Request){store.run('DELETE FROM auth_rate_limits WHERE bucket=?',rateBucket(request));}
function getOwnerMfa(store:LedgerStore){return store.one<MfaRecord>("SELECT * FROM owner_mfa WHERE id='owner'");}
function recoveryHash(code:string){return hash(code.toUpperCase().replace(/[^A-Z0-9]/g,''));}
function recoveries(){return Array.from({length:10},()=>{const raw=randomBytes(7).toString('hex').toUpperCase();return `${raw.slice(0,4)}-${raw.slice(4,8)}-${raw.slice(8,12)}-${raw.slice(12)}`;});}
function verifyStage(request:Request,expected:'enroll'|'verify'){allowedOrigin(request);if(cookieStage(request)!==expected)throw apiError(401,'mfa_step_expired','Restart sign in to continue MFA setup.');}
export function claimOwnerSetup(store:LedgerStore,request:Request,body:unknown){allowedOrigin(request);checkRate(store,request);const parsed=z.object({token:z.string().min(32).max(256),email:z.string().email().max(254),password:z.string().min(12).max(256)}).strict().safeParse(body);if(!parsed.success)throw apiError(422,'invalid_request','Enter a valid email and password with at least 12 characters.');const row=setupRecord(store);if(!row||Date.parse(row.expires_at)<=Date.now()){recordFailure(store,request);throw apiError(401,'setup_token_invalid','This owner setup link is invalid or expired. Ask the host operator to generate a new setup link.');}const supplied=Buffer.from(hash(parsed.data.token));const expected=Buffer.from(row.token_hash);if(supplied.length!==expected.length||!timingSafeEqual(supplied,expected)){recordFailure(store,request);throw apiError(401,'setup_token_invalid','This owner setup link is invalid or expired. Ask the host operator to generate a new setup link.');}const salt=randomBytes(16);const passwordHash=scryptSync(parsed.data.password,salt,32,{N:65536,r:8,p:2,maxmem:96*1024*1024});let result:{secret:string;otpauth_url:string;cookie:{value:string;expires:number}}|null=null;try{store.transaction(()=>{if(passwordRecord(store))throw apiError(409,'owner_already_claimed','The owner account has already been set up.');const live=setupRecord(store);if(!live||live.token_hash!==row.token_hash||Date.parse(live.expires_at)<=Date.now())throw apiError(409,'setup_token_used','This owner setup link has already been used.');store.run("INSERT INTO owner_password(id,email,salt,password_hash,session_version,must_change,updated_at) VALUES('owner',?,?,?,0,0,?)",parsed.data.email.trim().toLowerCase(),salt.toString('base64url'),passwordHash.toString('base64url'),now());store.run("DELETE FROM owner_setup WHERE id='owner'");store.run("UPDATE tenants SET email=? WHERE id='owner'",parsed.data.email.trim().toLowerCase());const secret=encodeBase32(randomBytes(20));store.run("INSERT INTO owner_mfa(id,encrypted_secret,confirmed,last_counter,recovery_hashes,updated_at) VALUES('owner',?,0,-1,'[]',?)",encryptMfaSecret(secret),now());const account=encodeURIComponent(parsed.data.email.trim().toLowerCase()),label=encodeURIComponent(`Agora:${parsed.data.email.trim().toLowerCase()}`),issuer=encodeURIComponent('Agora');result={secret,otpauth_url:`otpauth://totp/${label}?secret=${secret}&issuer=${issuer}&algorithm=SHA1&digits=6&period=30&account=${account}`,cookie:makeCookie('enroll')};});}catch(error){if(error instanceof ApiError)throw error;throw apiError(409,'owner_setup_failed','Owner setup could not be completed. Try again or ask the host operator for a new setup link.');}clearFailures(store,request);return{stage:'enroll' as const,email:parsed.data.email.trim().toLowerCase(),secret:result!.secret,otpauth_url:result!.otpauth_url,cookie:result!.cookie};}
export function beginAdminLogin(store:LedgerStore,request:Request,body:unknown){allowedOrigin(request);checkRate(store,request);const parsed=z.object({password:z.string().min(1).max(256)}).strict().safeParse(body);if(!parsed.success)throw apiError(422,'invalid_request','Provide a valid password.');const saved=passwordRecord(store),expected=process.env.AGORA_ADMIN_PASSWORD;let valid=false;if(saved){const actual=scryptSync(parsed.data.password,Buffer.from(saved.salt,'base64url'),32,{N:65536,r:8,p:2,maxmem:96*1024*1024});const stored=Buffer.from(saved.password_hash,'base64url');valid=actual.length===stored.length&&timingSafeEqual(actual,stored);}else if(expected&&expected.length>=24){const a=Buffer.from(hash(parsed.data.password)),b=Buffer.from(hash(expected));valid=a.length===b.length&&timingSafeEqual(a,b);}else throw apiError(503,'auth_not_configured','Set AGORA_ADMIN_PASSWORD to at least 24 characters.');if(!valid){recordFailure(store,request);throw apiError(401,'invalid_credentials','The email or password is incorrect.');}clearFailures(store,request);const mfa=getOwnerMfa(store);if(mfa?.confirmed)return{stage:'verify' as const,cookie:makeCookie('verify')};const secret=mfa?.encrypted_secret?decryptMfaSecret(mfa.encrypted_secret):encodeBase32(randomBytes(20));if(!mfa?.encrypted_secret)store.run("INSERT INTO owner_mfa(id,encrypted_secret,confirmed,last_counter,recovery_hashes,updated_at) VALUES('owner',?,0,-1,'[]',?) ON CONFLICT(id) DO UPDATE SET encrypted_secret=excluded.encrypted_secret,confirmed=0,last_counter=-1,recovery_hashes='[]',updated_at=excluded.updated_at",encryptMfaSecret(secret),now());const account=encodeURIComponent(ownerLoginEmail(store)||'owner');const label=encodeURIComponent(`Agora:${ownerLoginEmail(store)||'owner'}`);const issuer=encodeURIComponent('Agora');return{stage:'enroll' as const,secret,otpauth_url:`otpauth://totp/${label}?secret=${secret}&issuer=${issuer}&algorithm=SHA1&digits=6&period=30&account=${account}`,cookie:makeCookie('enroll')};}
export function enrollAdminMfa(store:LedgerStore,request:Request,body:unknown){verifyStage(request,'enroll');const parsed=z.object({code:z.string()}).strict().safeParse(body);if(!parsed.success)throw apiError(422,'invalid_request','Enter the six-digit code from your authenticator.');checkRate(store,request);let result:{recovery_codes:string[];cookie:{value:string;expires:number}}|null=null;try{store.transaction(()=>{const mfa=getOwnerMfa(store);if(!mfa||mfa.confirmed)throw apiError(409,'mfa_already_enrolled','MFA enrollment is already complete.');const secret=decryptMfaSecret(mfa.encrypted_secret);const counter=verifiedCounter(secret,parsed.data.code,mfa.last_counter);if(counter===null)throw apiError(401,'invalid_mfa_code','That authenticator code is invalid or already used.');const codes=recoveries();store.run("UPDATE owner_mfa SET confirmed=1,last_counter=?,recovery_hashes=?,updated_at=? WHERE id='owner'",counter,JSON.stringify(codes.map(recoveryHash)),now());clearFailures(store,request);result={recovery_codes:codes,cookie:makeCookie('owner',store)};});}catch(error){if(error instanceof ApiError&&error.code==='invalid_mfa_code')recordFailure(store,request);throw error;}return result!;}
export function verifyAdminMfa(store:LedgerStore,request:Request,body:unknown){verifyStage(request,'verify');const parsed=z.object({code:z.string().optional(),recovery_code:z.string().optional()}).strict().refine(v=>Boolean(v.code)||Boolean(v.recovery_code)).safeParse(body);if(!parsed.success)throw apiError(422,'invalid_request','Enter an authenticator code or recovery code.');checkRate(store,request);let cookie:{value:string;expires:number}|null=null;try{store.transaction(()=>{const mfa=getOwnerMfa(store);if(!mfa?.confirmed)throw apiError(409,'mfa_not_enrolled','Complete MFA enrollment before signing in.');if(parsed.data.recovery_code){const target=recoveryHash(parsed.data.recovery_code);const hashes=JSON.parse(mfa.recovery_hashes) as string[];const index=hashes.findIndex(value=>value===target);if(index<0)throw apiError(401,'invalid_mfa_code','That recovery code is invalid or already used.');hashes.splice(index,1);store.run("UPDATE owner_mfa SET recovery_hashes=?,updated_at=? WHERE id='owner'",JSON.stringify(hashes),now());}else{const counter=verifiedCounter(decryptMfaSecret(mfa.encrypted_secret),parsed.data.code!,mfa.last_counter);if(counter===null)throw apiError(401,'invalid_mfa_code','That authenticator code is invalid or already used.');store.run("UPDATE owner_mfa SET last_counter=?,updated_at=? WHERE id='owner'",counter,now());}clearFailures(store,request);cookie=makeCookie('owner',store);});}catch(error){if(error instanceof ApiError&&error.code==='invalid_mfa_code')recordFailure(store,request);throw error;}return{cookie:cookie!};}
export function changeAdminPassword(store:LedgerStore,request:Request,body:unknown){allowedOrigin(request);if(!isAdminSession(store,request))throw apiError(401,'authentication_required','Sign in with MFA before changing your password.');const parsed=z.object({current_password:z.string().min(1).max(256),new_password:z.string().min(12).max(256)}).strict().safeParse(body);if(!parsed.success)throw apiError(422,'invalid_request','Use a new password with at least 12 characters.');const existing=passwordRecord(store),bootstrap=process.env.AGORA_ADMIN_PASSWORD;let valid=false;if(existing){const actual=scryptSync(parsed.data.current_password,Buffer.from(existing.salt,'base64url'),32,{N:65536,r:8,p:2,maxmem:96*1024*1024}),expected=Buffer.from(existing.password_hash,'base64url');valid=actual.length===expected.length&&timingSafeEqual(actual,expected);}else if(bootstrap){const a=Buffer.from(hash(parsed.data.current_password)),b=Buffer.from(hash(bootstrap));valid=a.length===b.length&&timingSafeEqual(a,b);}if(!valid)throw apiError(401,'invalid_credentials','The current password is incorrect.');if(parsed.data.new_password===parsed.data.current_password)throw apiError(422,'password_reuse','Choose a password different from the current password.');const salt=randomBytes(16),passwordHash=scryptSync(parsed.data.new_password,salt,32,{N:65536,r:8,p:2,maxmem:96*1024*1024}),version=(existing?.session_version||0)+1;store.transaction(()=>{store.run("INSERT INTO owner_password(id,salt,password_hash,session_version,must_change,updated_at) VALUES('owner',?,?,?,0,?) ON CONFLICT(id) DO UPDATE SET salt=excluded.salt,password_hash=excluded.password_hash,session_version=excluded.session_version,must_change=0,updated_at=excluded.updated_at",salt.toString('base64url'),passwordHash.toString('base64url'),version,now());store.event('owner.password_changed','owner','owner',{});});return{ok:true};}
export function authSession(store:LedgerStore,request:Request){const authenticated=isAdminSession(store,request),stage=authenticated?'owner':pendingMfaStage(request);const provider:string=process.env.AGORA_PAYMENT_PROVIDER||'sandbox';const password=passwordRecord(store),setup=setupRecord(store),setupExpired=Boolean(!password&&setup&&Date.parse(setup.expires_at)<=Date.now());return{authenticated,role:authenticated?'owner':stage?'owner':null,access_status:authenticated?'approved':stage?'approved':'none',mfa_stage:authenticated?'complete':stage||null,password_change_required:authenticated?(!password||password.must_change===1):false,owner_setup_required:!password&&Boolean(setup&&Date.parse(setup.expires_at)>Date.now()),owner_setup_expired:setupExpired,mode:provider==='stripe'?'stripe':'sandbox'};}
