import { createService } from './service';
import { localStore } from './db';

const service=createService(localStore);
service.migrateMfaEncryptionKeys();
export const migrateMfaEncryptionKeys=service.migrateMfaEncryptionKeys;
export const owner=service.owner;
export const authenticate=service.authenticate;
export const beginAdminLogin=service.beginAdminLogin;
export const enrollAdminMfa=service.enrollAdminMfa;
export const verifyAdminMfa=service.verifyAdminMfa;
export const authSession=service.authSession;
export const hasAdminSession=service.hasAdminSession;
export const logout=service.logout;
export const requirePaymentMode=service.requirePaymentMode;
export const consoleAuth=service.consoleActor;
export const createMerchantInvite=service.createMerchantInvite;
export const acceptMerchantInvite=service.acceptMerchantInvite;
export const merchantLogin=service.merchantLogin;
export const enrollMerchantMfa=service.enrollMerchantMfa;
export const verifyMerchantMfa=service.verifyMerchantMfa;
export const setMerchantCookie=service.setMerchantCookie;
export const clearMerchantCookie=service.clearMerchantCookie;
export const mutate=service.mutate;
export const createProduct=service.createProduct;
export const archiveProduct=service.archiveProduct;
export const archivePayment=service.archivePayment;
export const paymentActivity=service.paymentActivity;
export const createPayment=service.createPayment;
export const createRefund=service.createRefund;
export const resolveApproval=service.resolveApproval;
export const createCredential=service.createCredential;
export const revokeCredential=service.revokeCredential;
export const registerMerchant=service.registerMerchant;
export const reviewRegistration=service.reviewRegistration;
export const simulate=service.simulate;
export const prepareStripePayment=service.prepareStripePayment;
export const saveStripeSession=service.saveStripeSession;
export const stripePaymentReconcileContext=service.stripePaymentReconcileContext;
export const reconcileStripePayment=service.reconcileStripePayment;
export const beginStripeConnect=service.beginStripeConnect;
export const consumeStripeConnectState=service.consumeStripeConnectState;
export const saveStripeConnectedAccount=service.saveStripeConnectedAccount;
export const stripeAccountForTenant=service.stripeAccountForTenant;
export const disconnectStripeAccount=service.disconnectStripeAccount;
export const stripeRefundContext=service.stripeRefundContext;
export const stripeRefundResult=service.stripeRefundResult;
export const recordStripeRefundResult=service.recordStripeRefundResult;
export const handleStripeWebhook=service.handleStripeWebhook;
export const snapshot=service.snapshot;
export { ApiError, bodyOf, setSessionCookie, requireSameOrigin, responseError, requireScope, requireProviderMode, scopes } from './service';
export { setMfaCookie } from './admin-auth';

export const paymentProviderReadiness=service.paymentProviderReadiness;
export const stripeRuntimeEnvironment=service.stripeRuntimeEnvironment;
export const stripeConfigSummary=service.stripeConfigSummary;
export const setStripeConfig=service.setStripeConfig;
export const stripeSecret=service.stripeSecret;
export const createWebhookEndpoint=service.createWebhookEndpoint;
export const listWebhookEndpoints=service.listWebhookEndpoints;
export const updateWebhookEndpoint=service.updateWebhookEndpoint;
export const archiveWebhookEndpoint=service.archiveWebhookEndpoint;
export const rotateWebhookSecret=service.rotateWebhookSecret;
export const listWebhookDeliveries=service.listWebhookDeliveries;
export const webhookDeliveryDetail=service.webhookDeliveryDetail;
export const replayWebhookDelivery=service.replayWebhookDelivery;
