import { createHash, createHmac, randomBytes, scrypt, timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import type { LedgerStore } from './store';
import { ApiError } from './errors';
import { decryptMfaSecret, encryptMfaSecret } from './mfa-crypto';

const digest=(s:string)=>createHash('sha256').update(s).digest('hex');
const SESSION='agora_merchant_session',PENDING='agora_merchant_pending';
type Stage='enroll'|'verify'|'member';
type User={id:string;tenant_id:string;email:string;password_salt:string;password_hash:string;mfa_secret:string|null;mfa_confirmed:number;last_counter:number;recovery_hashes:string;disabled:number};
function fail(status:number,code:string,message:string){return new ApiError(status,code,message)}
function sessionKey(){const key=process.env.AGORA_ADMIN_TOKEN;if(!key||key.length<32)throw fail(503,'auth_not_configured','Merchant sessions are not configured.');return key;}
function b32(bytes:Uint8Array){const abc='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,value=0,out='';for(const byte of bytes){value=(value<<8)|byte;bits+=8;while(bits>=5){out+=abc[(value>>>(bits-5))&31];bits-=5;}}if(bits)out+=abc[(value<<(5-bits))&31];return out;}
function from32(value:string){const abc='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,n=0;const out:number[]=[];for(const ch of value){const x=abc.indexOf(ch);if(x<0)throw fail(500,'mfa_secret_invalid','The saved authenticator secret is invalid.');n=(n<<5)|x;bits+=5;if(bits>=8){out.push((n>>>(bits-8))&255);bits-=8;}}return Buffer.from(out);}
function totp(secret:string,counter:number){const bytes=Buffer.alloc(8);bytes.writeBigUInt64BE(BigInt(counter));const mac=createHmac('sha1',from32(secret)).update(bytes).digest();const offset=mac[mac.length-1]&15;return String((mac.readUInt32BE(offset)&0x7fffffff)%1_000_000).padStart(6,'0');}
function checkCode(secret:string,code:string,last:number){if(!/^\d{6}$/.test(code))return null;const now=Math.floor(Date.now()/30000);for(const c of [now-1,now,now+1]){const a=Buffer.from(totp(secret,c)),b=Buffer.from(code);if(c>last&&timingSafeEqual(a,b))return c;}return null;}
// OWASP's scrypt tradeoff for constrained memory: N=2^16, r=8, p=2 (64 MiB).
const PASSWORD_KDF='scrypt',SCRYPT_N=65_536,SCRYPT_R=8,SCRYPT_P=2;
function deriveScrypt(password:string,salt:string){return new Promise<Buffer>((resolve,reject)=>scrypt(password,Buffer.from(salt,'base64url'),32,{N:SCRYPT_N,r:SCRYPT_R,p:SCRYPT_P,maxmem:96*1024*1024},(error,key)=>error?reject(error):resolve(key)));}
async function passwordHash(password:string,salt:string){const out=await deriveScrypt(password,salt);return`${PASSWORD_KDF}$${SCRYPT_N}$${SCRYPT_R}$${SCRYPT_P}$${out.toString('base64url')}`;}
async function verifyPassword(password:string,salt:string,stored:string){const parts=stored.split('$');if(parts.length!==5||parts[0]!==PASSWORD_KDF||parts[1]!==String(SCRYPT_N)||parts[2]!==String(SCRYPT_R)||parts[3]!==String(SCRYPT_P)||!/^[A-Za-z0-9_-]{43}$/.test(parts[4])){await deriveScrypt(password,salt);return false;}const actual=await deriveScrypt(password,salt);return equal(actual.toString('base64url'),parts[4]);}
function equal(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);}
function makeCookie(stage:Stage,id:string,tenant:string){const expiry=Math.floor(Date.now()/1000)+(stage==='member'?8*3600:600);const nonce=randomBytes(16).toString('base64url');const payload=`${stage}.${id}.${tenant}.${expiry}.${nonce}`;const sig=createHmac('sha256',sessionKey()).update(payload).digest('base64url');return{value:`${payload}.${sig}`,expires:expiry};}
function readCookie(request:Request,name:string){const v=request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1);if(!v)return null;const p=v.split('.');if(p.length!==6)return null;const[stage,id,tenant,expiry,nonce,sig]=p;if(!['enroll','verify','member'].includes(stage)||!/^[\w-]{1,80}$/.test(id)||!/^[\w-]{1,80}$/.test(tenant)||!/^\d+$/.test(expiry)||Number(expiry)<=Math.floor(Date.now()/1000))return null;const expected=createHmac('sha256',sessionKey()).update(`${stage}.${id}.${tenant}.${expiry}.${nonce}`).digest('base64url');return equal(expected,sig)?{stage:stage as Stage,id,tenant}:null;}
function rawCookie(request:Request,name:string){return request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1)||null;}
function revoked(store:LedgerStore,raw:string|null){return Boolean(raw&&store.one('SELECT token_hash FROM revoked_sessions WHERE token_hash=?',digest(raw)));}
export function revokeMerchantSessions(store:LedgerStore,request:Request){for(const name of [SESSION,PENDING]){const raw=rawCookie(request,name),session=raw?readCookie(new Request(request.url,{headers:{cookie:`${name}=${raw}`}}),name):null,parts=raw?.split('.');if(raw&&session&&parts?.length===6&&/^\d+$/.test(parts[3]))store.run('INSERT OR REPLACE INTO revoked_sessions(token_hash,expires_at) VALUES(?,?)',digest(raw),Number(parts[3]));}store.run('DELETE FROM revoked_sessions WHERE expires_at<?',Math.floor(Date.now()/1000));}
function originGuard(request:Request){const configured=process.env.AGORA_PUBLIC_ORIGIN;if(!configured)throw fail(503,'auth_not_configured','Set AGORA_PUBLIC_ORIGIN before merchant sign-in.');if(request.headers.get('origin')!==new URL(configured).origin||request.headers.get('sec-fetch-site')==='cross-site')throw fail(403,'origin_rejected','Use the configured same-origin sign-in page.');}
function rateBucket(request:Request,email:string){const ip=request.headers.get('cf-connecting-ip')||request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown';return`merchant-auth:${digest(`${ip}|${email.toLowerCase()}`)}`;}
function checkRate(store:LedgerStore,request:Request,email:string){const row=store.one<{attempts:number;window_started:number;locked_until:number}>('SELECT attempts,window_started,locked_until FROM auth_rate_limits WHERE bucket=?',rateBucket(request,email));const now=Math.floor(Date.now()/1000);if(row&&(row.locked_until>now||(now-row.window_started<900&&row.attempts>=5)))throw fail(429,'rate_limited','Too many sign-in attempts. Try again later.');}
function failRate(store:LedgerStore,request:Request,email:string){const bucket=rateBucket(request,email),now=Math.floor(Date.now()/1000),row=store.one<{attempts:number;window_started:number}>('SELECT attempts,window_started FROM auth_rate_limits WHERE bucket=?',bucket);const attempts=row&&now-row.window_started<900?row.attempts+1:1,start=row&&now-row.window_started<900?row.window_started:now,locked=attempts>=10?now+900:attempts>=5?now+60:0;store.run('INSERT INTO auth_rate_limits(bucket,attempts,window_started,locked_until) VALUES(?,?,?,?) ON CONFLICT(bucket) DO UPDATE SET attempts=excluded.attempts,window_started=excluded.window_started,locked_until=excluded.locked_until',bucket,attempts,start,locked);}
function clearRate(store:LedgerStore,request:Request,email:string){store.run('DELETE FROM auth_rate_limits WHERE bucket=?',rateBucket(request,email));}
export function setMerchantCookie(response:Response,request:Request,scope:'member'|'pending',cookie?:{value:string;expires:number}){const name=scope==='member'?SESSION:PENDING;const secure=new URL(request.url).protocol==='https:'||process.env.NODE_ENV==='production';const age=cookie?Math.max(0,cookie.expires-Math.floor(Date.now()/1000)):0;const sameSite=scope==='member'?'Lax':'Strict';response.headers.append('Set-Cookie',`${name}=${cookie?.value||''}; Path=/; HttpOnly; SameSite=${sameSite}; Max-Age=${age}${secure?'; Secure':''}`);return response;}
export function clearMerchantCookie(request:Request){const secure=new URL(request.url).protocol==='https:'||process.env.NODE_ENV==='production';return`${SESSION}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${secure?'; Secure':''}`;}

export function createMerchantInvite(store:LedgerStore,tenantId:string){const tenant=store.one<{email:string;status:string}>('SELECT email,status FROM tenants WHERE id=?',tenantId);if(!tenant||tenant.status!=='approved')throw fail(409,'merchant_pending','Approve the merchant before creating an invite.');const token=randomBytes(32).toString('hex'),now=store.now(),expires=new Date(Date.now()+48*3600_000).toISOString();store.transaction(()=>{store.run('UPDATE merchant_invites SET used_at=? WHERE tenant_id=? AND used_at IS NULL',now,tenantId);store.run('INSERT INTO merchant_invites(token_hash,tenant_id,email,expires_at,used_at,created_at) VALUES(?,?,?,?,NULL,?)',digest(token),tenantId,tenant.email,expires,now);});return{token,email:tenant.email,expires_at:expires};}
export async function acceptMerchantInvite(store:LedgerStore,request:Request,body:unknown){originGuard(request);const parsed=z.object({token:z.string().regex(/^[a-f0-9]{64}$/),password:z.string().min(14).max(128)}).strict().safeParse(body);if(!parsed.success)throw fail(422,'invalid_request','Use your invite link and a password of at least 14 characters.');const tokenHash=digest(parsed.data.token);const invite=store.one<{tenant_id:string;email:string;expires_at:string;used_at:string|null}>('SELECT * FROM merchant_invites WHERE token_hash=?',tokenHash);if(!invite||invite.used_at||Date.parse(invite.expires_at)<=Date.now())throw fail(400,'invite_invalid','This merchant invite is invalid or expired.');const userId=store.id('usr'),salt=randomBytes(16).toString('base64url'),password=await passwordHash(parsed.data.password,salt),secret=b32(randomBytes(20));let session:{value:string;expires:number}|null=null;store.transaction(()=>{const fresh=store.one<{used_at:string|null;expires_at:string}>('SELECT used_at,expires_at FROM merchant_invites WHERE token_hash=?',tokenHash);const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',invite.tenant_id);if(!fresh||fresh.used_at||Date.parse(fresh.expires_at)<=Date.now())throw fail(400,'invite_invalid','This merchant invite is invalid or expired.');if(!tenant||tenant.status!=='approved')throw fail(403,'merchant_pending','This merchant is not approved.');if(store.one('SELECT id FROM merchant_users WHERE tenant_id=? AND lower(email)=lower(?)',invite.tenant_id,invite.email))throw fail(409,'merchant_user_exists','This invite has already been claimed.');store.run("INSERT INTO merchant_users(id,tenant_id,email,password_salt,password_hash,mfa_secret,mfa_confirmed,last_counter,recovery_hashes,disabled,created_at,updated_at) VALUES(?,?,?,?,?,?,0,-1,'[]',0,?,?)",userId,invite.tenant_id,invite.email,salt,password,encryptMfaSecret(secret),store.now(),store.now());store.run('UPDATE merchant_invites SET used_at=? WHERE token_hash=? AND used_at IS NULL',store.now(),tokenHash);session=makeCookie('enroll',userId,invite.tenant_id);});const email=invite.email,label=encodeURIComponent(`Agora:${email}`);return{stage:'enroll' as const,email,secret,otpauth_url:`otpauth://totp/${label}?secret=${secret}&issuer=Agora&algorithm=SHA1&digits=6&period=30&account=${encodeURIComponent(email)}`,cookie:session!};}
export async function merchantLogin(store:LedgerStore,request:Request,body:unknown){originGuard(request);const parsed=z.object({email:z.string().email().max(254),password:z.string().min(1).max(128)}).strict().safeParse(body);if(!parsed.success)throw fail(422,'invalid_request','Enter your merchant email and password.');const email=parsed.data.email.trim().toLowerCase();checkRate(store,request,email);const user=store.one<User>('SELECT * FROM merchant_users WHERE lower(email)=lower(?) AND disabled=0',email);const valid=user?await verifyPassword(parsed.data.password,user.password_salt,user.password_hash):(await deriveScrypt(parsed.data.password,'invalid-user-salt-000000'),false);if(!user||!valid){failRate(store,request,email);throw fail(401,'invalid_credentials','The email or password is incorrect.');}const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',user.tenant_id);if(!tenant||tenant.status!=='approved')throw fail(403,'merchant_pending','This merchant workspace is not approved.');clearRate(store,request,email);if(!user.mfa_confirmed){const secret=decryptMfaSecret(user.mfa_secret!),label=encodeURIComponent(`Agora:${user.email}`);return{stage:'enroll' as const,email:user.email,secret,otpauth_url:`otpauth://totp/${label}?secret=${secret}&issuer=Agora&algorithm=SHA1&digits=6&period=30&account=${encodeURIComponent(user.email)}`,cookie:makeCookie('enroll',user.id,user.tenant_id)};}return{stage:'verify' as const,cookie:makeCookie('verify',user.id,user.tenant_id)};}
export function enrollMerchantMfa(store:LedgerStore,request:Request,body:unknown){
 originGuard(request);const pending=readCookie(request,PENDING);if(!pending||pending.stage!=='enroll')throw fail(401,'mfa_step_expired','Restart merchant sign-in to continue MFA setup.');
 const parsed=z.object({code:z.string().regex(/^\d{6}$/)}).strict().safeParse(body);if(!parsed.success)throw fail(422,'invalid_request','Enter a six-digit authenticator code.');
 const member=store.one<User>('SELECT * FROM merchant_users WHERE id=? AND tenant_id=? AND disabled=0',pending.id,pending.tenant);if(!member)throw fail(401,'mfa_step_expired','Restart merchant sign-in to continue MFA setup.');checkRate(store,request,member.email);
 let codes:string[]=[],cookie:{value:string;expires:number}|null=null;
 try{store.transaction(()=>{const user=store.one<User>('SELECT * FROM merchant_users WHERE id=? AND tenant_id=? AND disabled=0',pending.id,pending.tenant);const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',pending.tenant);if(!user||!tenant||tenant.status!=='approved')throw fail(403,'merchant_pending','This merchant workspace is not approved.');if(user.mfa_confirmed)throw fail(409,'mfa_already_enrolled','Merchant MFA enrollment is already complete.');const counter=checkCode(decryptMfaSecret(user.mfa_secret!),parsed.data.code,user.last_counter);if(counter===null)throw fail(401,'invalid_mfa_code','That authenticator code is invalid or already used.');codes=Array.from({length:10},()=>randomBytes(7).toString('hex').toUpperCase().match(/.{1,4}/g)!.join('-'));store.run('UPDATE merchant_users SET mfa_confirmed=1,last_counter=?,recovery_hashes=?,updated_at=? WHERE id=?',counter,JSON.stringify(codes.map(digest)),store.now(),user.id);cookie=makeCookie('member',user.id,user.tenant_id);});}
 catch(error){if(error instanceof ApiError&&error.code==='invalid_mfa_code')failRate(store,request,member.email);throw error;}
 clearRate(store,request,member.email);return{recovery_codes:codes,cookie:cookie!};
}
export function verifyMerchantMfa(store:LedgerStore,request:Request,body:unknown){
 originGuard(request);const pending=readCookie(request,PENDING);if(!pending||pending.stage!=='verify')throw fail(401,'mfa_step_expired','Restart merchant sign-in to continue MFA.');
 const parsed=z.object({code:z.string().optional(),recovery_code:z.string().optional()}).strict().refine(v=>Boolean(v.code)||Boolean(v.recovery_code)).safeParse(body);if(!parsed.success)throw fail(422,'invalid_request','Enter an authenticator code or recovery code.');
 const member=store.one<User>('SELECT * FROM merchant_users WHERE id=? AND tenant_id=? AND disabled=0 AND mfa_confirmed=1',pending.id,pending.tenant);if(!member)throw fail(403,'mfa_not_enrolled','Complete merchant MFA enrollment first.');checkRate(store,request,member.email);
 let cookie:{value:string;expires:number}|null=null;
 try{store.transaction(()=>{const user=store.one<User>('SELECT * FROM merchant_users WHERE id=? AND tenant_id=? AND disabled=0 AND mfa_confirmed=1',pending.id,pending.tenant);const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',pending.tenant);if(!user||!tenant||tenant.status!=='approved')throw fail(403,'merchant_pending','This merchant workspace is not approved.');if(parsed.data.recovery_code){const target=digest(parsed.data.recovery_code.toUpperCase().replace(/[^A-Z0-9]/g,'')),hashes=JSON.parse(user.recovery_hashes) as string[],index=hashes.indexOf(target);if(index<0)throw fail(401,'invalid_mfa_code','That recovery code is invalid or already used.');hashes.splice(index,1);store.run('UPDATE merchant_users SET recovery_hashes=?,updated_at=? WHERE id=?',JSON.stringify(hashes),store.now(),user.id);}else{const counter=checkCode(decryptMfaSecret(user.mfa_secret!),parsed.data.code!,user.last_counter);if(counter===null)throw fail(401,'invalid_mfa_code','That authenticator code is invalid or already used.');store.run('UPDATE merchant_users SET last_counter=?,updated_at=? WHERE id=?',counter,store.now(),user.id);}cookie=makeCookie('member',user.id,user.tenant_id);});}
 catch(error){if(error instanceof ApiError&&error.code==='invalid_mfa_code')failRate(store,request,member.email);throw error;}
 clearRate(store,request,member.email);return{cookie:cookie!};
}
export function merchantActor(store:LedgerStore,request:Request){const raw=rawCookie(request,SESSION),session=readCookie(request,SESSION);if(!session||session.stage!=='member'||revoked(store,raw))return null;const user=store.one<User>('SELECT * FROM merchant_users WHERE id=? AND tenant_id=? AND disabled=0 AND mfa_confirmed=1',session.id,session.tenant),tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',session.tenant);if(!user||!tenant||tenant.status!=='approved')return null;return{id:user.id,name:user.email,scopes:['*'],tenant_id:user.tenant_id};}
export function merchantAuthSession(store:LedgerStore,request:Request){const pending=readCookie(request,PENDING),rawPending=rawCookie(request,PENDING);const actor=merchantActor(store,request);if(actor)return{authenticated:true,role:'merchant',access_status:'approved',tenant_id:actor.tenant_id,mfa_stage:'complete'};if(pending&&!revoked(store,rawPending)){const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',pending.tenant);if(tenant?.status==='approved')return{authenticated:false,role:'merchant',access_status:'approved',mfa_stage:pending.stage,tenant_id:pending.tenant};}return null;}
