import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { isIP } from 'node:net';
import { ApiError } from './errors';
import type { LedgerStore } from './store';
import { decryptWorkspaceSecret, encryptWorkspaceSecret } from './stripe-config';

export const outgoingEventTypes = [
  'product.created','product.archived','product.restored','payment.created','payment.succeeded','payment.failed','payment.archived','payment.restored',
  'refund.requested','refund.succeeded','refund.failed','approval.requested',
  'key.created','key.revoked','provider.stripe.connected','provider.stripe.disconnected','registration.created',
] as const;
export type OutgoingEventType = typeof outgoingEventTypes[number];
export type WebhookMode = 'test'|'live';
export type WebhookEndpointStatus = 'active'|'paused'|'archived';
export type DeliveryStatus = 'pending'|'delivering'|'delivered'|'failed'|'paused'|'skipped_mode';
const retrySeconds=[30,60,120,300,600,1800,3600,7200,14400];
const maxAttempts=10;
type Environment=Record<string,string|undefined>;
type EventRow={id:string;type:string;actor:string;object_id:string;data:string|object;tenant_id:string;created_at:string};
type EndpointRow={id:string;tenant_id:string;url:string;provider_mode:WebhookMode;event_types:string;secret_ciphertext:string;status:WebhookEndpointStatus;created_at:string;updated_at:string;secret_updated_at:string};
type DeliveryRow={id:string;endpoint_id:string;event_id:string;event_type:string;tenant_id:string;payload:string;status:DeliveryStatus;attempt_count:number;next_attempt_at:string;last_attempt_at:string|null;delivered_at:string|null;last_http_status:number|null;last_error:string|null;lease_token:string|null;locked_until:string|null;created_at:string};
const allowed=new Set<string>(outgoingEventTypes);

function validateUrl(raw:unknown,environment:Environment) {
  if(typeof raw!=='string'||raw.length>2048)throw new ApiError(422,'invalid_webhook_url','Provide a valid public HTTPS URL.');
  let url:URL;try{url=new URL(raw)}catch{throw new ApiError(422,'invalid_webhook_url','Provide a valid public HTTPS URL.');}
  const local=url.hostname==='localhost'||url.hostname.endsWith('.localhost')||url.hostname==='127.0.0.1'||url.hostname==='[::1]';
  const privateHost=local||url.hostname.endsWith('.local')||url.hostname.endsWith('.internal')||url.hostname.endsWith('.lan')||url.hostname.endsWith('.test')||url.hostname==='metadata.google.internal';
  const ip=isIP(url.hostname.replace(/^\[|\]$/g,''));
  let privateIp=false;
  if(ip===4){const n=url.hostname.split('.').map(Number);privateIp=n[0]===0||n[0]===10||n[0]===127||n[0]>=224||n[0]===169&&n[1]===254||n[0]===172&&n[1]>=16&&n[1]<=31||n[0]===192&&n[1]===168;}
  if(ip===6){const host=url.hostname.toLowerCase();privateIp=host==='[::1]'||host.startsWith('[fc')||host.startsWith('[fd')||host.startsWith('[fe8')||host.startsWith('[fe9')||host.startsWith('[fea')||host.startsWith('[feb');}
  const localAllowed=environment.NODE_ENV!=='production'&&environment.VERCEL!=='1'&&environment.AGORA_ALLOW_LOCAL_WEBHOOKS==='true'&&local;
  if(url.username||url.password||url.hash||(!localAllowed&&(url.protocol!=='https:'||privateHost||privateIp))||(localAllowed&&!['http:','https:'].includes(url.protocol)))throw new ApiError(422,'invalid_webhook_url','Webhook endpoints must use public HTTPS. Local loopback is allowed only when explicitly enabled for local development.');
  return url.toString();
}
function eventsOf(raw:unknown):OutgoingEventType[]{
  if(!Array.isArray(raw)||raw.length<1||raw.length>outgoingEventTypes.length)throw new ApiError(422,'invalid_event_types','Choose one or more supported event types.');
  const unique=[...new Set(raw)];if(unique.some(value=>typeof value!=='string'||!allowed.has(value)))throw new ApiError(422,'invalid_event_types','One or more event types are unsupported.');return unique as OutgoingEventType[];
}
function endpointDto(row:EndpointRow){return{id:row.id,tenant_id:row.tenant_id,url:row.url,mode:row.provider_mode,event_types:JSON.parse(row.event_types) as string[],status:row.status,created_at:row.created_at,updated_at:row.updated_at,secret_updated_at:row.secret_updated_at};}
function queue(store:LedgerStore,endpoint:EndpointRow,event:EventRow,payload:string){
  const selected=JSON.parse(endpoint.event_types) as string[];if(endpoint.status!=='active'||!selected.includes(event.type))return;
  store.run('INSERT INTO webhook_deliveries(id,endpoint_id,event_id,event_type,tenant_id,payload,status,attempt_count,next_attempt_at,created_at) VALUES(?,?,?,?,?,?,\'pending\',0,?,?)',store.id('whd'),endpoint.id,event.id,event.type,event.tenant_id,payload,event.created_at,event.created_at);
}
export function enqueueWebhookEvent(store:LedgerStore,event:EventRow){
  const payload=JSON.stringify({id:event.id,type:event.type,created_at:event.created_at,api_version:'2026-09-28',data:{object:typeof event.data==='string'?JSON.parse(event.data):event.data}});
  const endpoints=store.all<EndpointRow>('SELECT * FROM webhook_endpoints WHERE tenant_id=? AND status=\'active\'',event.tenant_id);
  for(const endpoint of endpoints)queue(store,endpoint,event,payload);
  store.scheduleWebhookAlarm?.();
}
function owner(actor:{tenant_id:string}){if(actor.tenant_id!=='owner')throw new ApiError(403,'permission_denied','Only the workspace owner can manage outgoing webhooks.');}
export function createWebhookEndpoint(store:LedgerStore,actor:{tenant_id:string},input:unknown,environment:Environment=process.env){
  owner(actor);const body=input as Record<string,unknown>;const url=validateUrl(body?.url,environment);const mode=body?.mode;if(mode!=='test'&&mode!=='live')throw new ApiError(422,'invalid_mode','Choose test or live mode.');const eventTypes=eventsOf(body?.event_types);const now=store.now();const id=store.id('whk');const secret=`whsec_agora_${randomBytes(32).toString('base64url')}`;const sealed=encryptWorkspaceSecret(secret,environment);
  store.run('INSERT INTO webhook_endpoints(id,tenant_id,url,provider_mode,event_types,secret_ciphertext,status,created_at,updated_at,secret_updated_at) VALUES(?,?,?,?,?,?,\'active\',?,?,?)',id,actor.tenant_id,url,mode,JSON.stringify(eventTypes),sealed,now,now,now);
  return{endpoint:endpointDto({id,tenant_id:actor.tenant_id,url,provider_mode:mode,event_types:JSON.stringify(eventTypes),secret_ciphertext:sealed,status:'active',created_at:now,updated_at:now,secret_updated_at:now}),signing_secret:secret};
}
export function listWebhookEndpoints(store:LedgerStore,actor:{tenant_id:string},includeArchived=false){owner(actor);const statusFilter=includeArchived?'':' AND e.status<>\'archived\'';return store.all<EndpointRow&{last_delivery_at:string|null;last_status:string|null;success_count:number;fail_count:number}>(`SELECT e.*, (SELECT MAX(d.last_attempt_at) FROM webhook_deliveries d WHERE d.endpoint_id=e.id) AS last_delivery_at,(SELECT d.status FROM webhook_deliveries d WHERE d.endpoint_id=e.id ORDER BY d.created_at DESC LIMIT 1) AS last_status,(SELECT COUNT(*) FROM webhook_deliveries d WHERE d.endpoint_id=e.id AND d.status='delivered') AS success_count,(SELECT COUNT(*) FROM webhook_deliveries d WHERE d.endpoint_id=e.id AND d.status='failed') AS fail_count FROM webhook_endpoints e WHERE e.tenant_id=?${statusFilter} ORDER BY e.created_at DESC`,actor.tenant_id).map(row=>({...endpointDto(row),last_delivery_at:row.last_delivery_at,last_status:row.last_status,success_count:row.success_count,fail_count:row.fail_count}));}
export function updateWebhookEndpoint(store:LedgerStore,actor:{tenant_id:string},id:string,input:unknown,environment:Environment=process.env){owner(actor);const body=input as Record<string,unknown>;const existing=store.one<EndpointRow>('SELECT * FROM webhook_endpoints WHERE id=? AND tenant_id=?',id,actor.tenant_id);if(!existing)throw new ApiError(404,'not_found','Webhook endpoint not found.');const url=body.url===undefined?existing.url:validateUrl(body.url,environment);const events=body.event_types===undefined?JSON.parse(existing.event_types) as string[]:eventsOf(body.event_types);const status=body.status===undefined?existing.status:String(body.status);if(!['active','paused'].includes(status))throw new ApiError(422,'invalid_status','Status must be active or paused.');store.transaction(()=>{store.run('UPDATE webhook_endpoints SET url=?,event_types=?,status=?,updated_at=? WHERE id=? AND tenant_id=?',url,JSON.stringify(events),status,store.now(),id,actor.tenant_id);if(status==='active'){const pending=store.all<DeliveryRow>('SELECT * FROM webhook_deliveries WHERE endpoint_id=? AND status=\'paused\'',id);for(const item of pending)store.run('UPDATE webhook_deliveries SET status=\'pending\',next_attempt_at=? WHERE id=?',store.now(),item.id);}});if(status==='active')store.scheduleWebhookAlarm?.();return{endpoint:endpointDto(store.one<EndpointRow>('SELECT * FROM webhook_endpoints WHERE id=?',id)!)};}
export function archiveWebhookEndpoint(store:LedgerStore,actor:{tenant_id:string},id:string){owner(actor);const found=store.one('SELECT id FROM webhook_endpoints WHERE id=? AND tenant_id=?',id,actor.tenant_id);if(!found)throw new ApiError(404,'not_found','Webhook endpoint not found.');store.transaction(()=>{store.run('UPDATE webhook_endpoints SET status=\'archived\',updated_at=? WHERE id=? AND tenant_id=?',store.now(),id,actor.tenant_id);store.run('UPDATE webhook_deliveries SET status=\'paused\',last_error=\'endpoint_archived\',locked_until=NULL,lease_token=NULL WHERE endpoint_id=? AND status IN (\'pending\',\'delivering\')',id);});return{endpoint:{id,status:'archived'}};}
export function rotateWebhookSecret(store:LedgerStore,actor:{tenant_id:string},id:string,environment:Environment=process.env){owner(actor);const endpoint=store.one<EndpointRow>('SELECT * FROM webhook_endpoints WHERE id=? AND tenant_id=?',id,actor.tenant_id);if(!endpoint)throw new ApiError(404,'not_found','Webhook endpoint not found.');const secret=`whsec_agora_${randomBytes(32).toString('base64url')}`;const now=store.now();store.run('UPDATE webhook_endpoints SET secret_ciphertext=?,secret_updated_at=?,updated_at=? WHERE id=? AND tenant_id=?',encryptWorkspaceSecret(secret,environment),now,now,id,actor.tenant_id);return{endpoint:endpointDto(store.one<EndpointRow>('SELECT * FROM webhook_endpoints WHERE id=?',id)!),signing_secret:secret};}
function cursorEncode(row:{created_at:string;id:string}){return Buffer.from(`${row.created_at}\n${row.id}`).toString('base64url');}
function cursorDecode(value:string){try{const [created,id]=Buffer.from(value,'base64url').toString().split('\n');if(!created||!id)throw 0;return{created,id};}catch{throw new ApiError(422,'invalid_cursor','The webhook cursor is invalid.');}}
export function listWebhookDeliveries(store:LedgerStore,actor:{tenant_id:string},endpointId:string,cursor?:string,requestedLimit=25){owner(actor);if(!store.one('SELECT id FROM webhook_endpoints WHERE id=? AND tenant_id=?',endpointId,actor.tenant_id))throw new ApiError(404,'not_found','Webhook endpoint not found.');const limit=Math.max(1,Math.min(100,Math.trunc(requestedLimit)||25));const values:(string|number|null|Uint8Array)[]=[endpointId];let where='endpoint_id=?';if(cursor){const c=cursorDecode(cursor);where+=' AND (created_at<? OR (created_at=? AND id<?))';values.push(c.created,c.created,c.id);}const rows=store.all<DeliveryRow>(`SELECT * FROM webhook_deliveries WHERE ${where} ORDER BY created_at DESC,id DESC LIMIT ?`,...values,limit+1);const hasMore=rows.length>limit;const data=rows.slice(0,limit).map(({id,event_id,event_type,status,attempt_count,next_attempt_at,last_attempt_at,last_http_status,last_error,created_at,delivered_at})=>({id,event_id,event_type,status,attempt_count,next_attempt_at,last_attempt_at,last_http_status,last_error,created_at,delivered_at}));return{data,next_cursor:hasMore&&data.length?cursorEncode(data.at(-1)!):null};}
export function webhookDeliveryDetail(store:LedgerStore,actor:{tenant_id:string},endpointId:string,deliveryId:string){owner(actor);const delivery=store.one<DeliveryRow>('SELECT * FROM webhook_deliveries WHERE id=? AND endpoint_id=? AND tenant_id=?',deliveryId,endpointId,actor.tenant_id);if(!delivery)throw new ApiError(404,'not_found','Webhook delivery not found.');const attempts=store.all<{attempt:number;started_at:string;finished_at:string|null;http_status:number|null;duration_ms:number|null;error:string|null;response_excerpt:string}>('SELECT attempt,started_at,finished_at,http_status,duration_ms,error,response_excerpt FROM webhook_attempts WHERE delivery_id=? ORDER BY attempt DESC',deliveryId);return{delivery:{id:delivery.id,event_id:delivery.event_id,event_type:delivery.event_type,status:delivery.status,attempt_count:delivery.attempt_count,next_attempt_at:delivery.next_attempt_at,last_attempt_at:delivery.last_attempt_at,last_http_status:delivery.last_http_status,last_error:delivery.last_error,created_at:delivery.created_at,delivered_at:delivery.delivered_at},attempts};}
export function replayWebhookDelivery(store:LedgerStore,actor:{tenant_id:string},endpointId:string,deliveryId:string){owner(actor);const old=store.one<DeliveryRow>('SELECT d.* FROM webhook_deliveries d JOIN webhook_endpoints e ON e.id=d.endpoint_id WHERE d.id=? AND d.endpoint_id=? AND d.tenant_id=? AND e.tenant_id=? AND e.status<>\'archived\'',deliveryId,endpointId,actor.tenant_id,actor.tenant_id);if(!old)throw new ApiError(404,'not_found','Webhook delivery not found.');const id=store.id('whd');const now=store.now();store.run('INSERT INTO webhook_deliveries(id,endpoint_id,event_id,event_type,tenant_id,payload,status,attempt_count,next_attempt_at,created_at) VALUES(?,?,?,?,?,?,\'pending\',0,?,?)',id,old.endpoint_id,old.event_id,old.event_type,old.tenant_id,old.payload,now,now);store.scheduleWebhookAlarm?.();return{delivery:{id,event_id:old.event_id,event_type:old.event_type,status:'pending',attempt_count:0,next_attempt_at:now}};}

function eventMode(store:LedgerStore,delivery:DeliveryRow):WebhookMode|null {const event=store.one<{object_id:string;type:string}>('SELECT object_id,type FROM events WHERE id=? AND tenant_id=?',delivery.event_id,delivery.tenant_id);if(!event)return null;let payment=store.one<{provider:string;provider_mode:string|null}>('SELECT provider,provider_mode FROM payments WHERE id=? AND tenant_id=?',event.object_id,delivery.tenant_id);if(!payment&&event.type==='approval.requested'){const approval=store.one<{payment_id:string}>('SELECT payment_id FROM approvals WHERE id=? AND tenant_id=?',event.object_id,delivery.tenant_id);if(approval)payment=store.one<{provider:string;provider_mode:string|null}>('SELECT provider,provider_mode FROM payments WHERE id=? AND tenant_id=?',approval.payment_id,delivery.tenant_id);}if(payment?.provider==='sandbox')return 'test';if(payment?.provider==='stripe'&&(payment.provider_mode==='test'||payment.provider_mode==='live'))return payment.provider_mode;return null;}
function errorCode(status:number){return `http_${status}`;}
export async function dispatchWebhookBatch(store:LedgerStore,environment:Environment=process.env,fetcher:typeof fetch=fetch,limit=10){
  const now=store.now();const jobs=store.transaction(()=>{const rows=store.all<DeliveryRow>("SELECT * FROM webhook_deliveries WHERE (status='pending' AND next_attempt_at<=?) OR (status='delivering' AND locked_until<=?) ORDER BY next_attempt_at LIMIT ?",now,now,Math.max(1,Math.min(limit,50)));const claimed:DeliveryRow[]=[];for(const row of rows){if(row.status==='delivering'){store.run("UPDATE webhook_attempts SET finished_at=?,error='worker_interrupted' WHERE delivery_id=? AND finished_at IS NULL",now,row.id);}const token=store.id('lease');const attempt=row.attempt_count+1;store.run("UPDATE webhook_deliveries SET status='delivering',attempt_count=?,last_attempt_at=?,lease_token=?,locked_until=? WHERE id=?",attempt,now,token,new Date(Date.now()+30000).toISOString(),row.id);store.run('INSERT INTO webhook_attempts(id,delivery_id,attempt,started_at) VALUES(?,?,?,?)',store.id('wha'),row.id,attempt,now);claimed.push({...row,status:'delivering',attempt_count:attempt,last_attempt_at:now,lease_token:token});}return claimed;});
  for(const job of jobs){const endpoint=store.one<EndpointRow>('SELECT * FROM webhook_endpoints WHERE id=? AND tenant_id=?',job.endpoint_id,job.tenant_id);if(!endpoint||endpoint.status==='archived'||endpoint.status==='paused'){store.transaction(()=>{store.run("UPDATE webhook_attempts SET finished_at=?,error='endpoint_unavailable' WHERE delivery_id=? AND attempt=?",store.now(),job.id,job.attempt_count);store.run("UPDATE webhook_deliveries SET status='paused',last_error='endpoint_unavailable',lease_token=NULL,locked_until=NULL WHERE id=? AND lease_token=?",job.id,job.lease_token);});continue;}const mode=eventMode(store,job);if(mode&&mode!==endpoint.provider_mode){store.transaction(()=>{store.run("UPDATE webhook_attempts SET finished_at=?,error='skipped_mode' WHERE delivery_id=? AND attempt=?",store.now(),job.id,job.attempt_count);store.run("UPDATE webhook_deliveries SET status='skipped_mode',last_error=NULL,lease_token=NULL,locked_until=NULL WHERE id=? AND lease_token=?",job.id,job.lease_token);});continue;}
    const secret=decryptWorkspaceSecret(endpoint.secret_ciphertext,environment);const timestamp=Math.floor(Date.now()/1000).toString();const signature=createHmac('sha256',secret).update(`${timestamp}.${job.payload}`).digest('hex');let status:number|null=null,error:string|null=null;const started=Date.now();
    try{const response=await fetcher(endpoint.url,{method:'POST',headers:{'Content-Type':'application/json','User-Agent':'Agora-Webhooks/1','Agora-Event-Id':job.event_id,'Agora-Delivery-Id':job.id,'Agora-Event-Type':job.event_type,'Agora-Timestamp':timestamp,'Agora-Signature':`v1=${signature}`},body:job.payload,redirect:'manual',signal:AbortSignal.timeout(10_000)});status=response.status;await response.body?.cancel();if(status<200||status>=300)error=errorCode(status);}catch{error='network_error';}
    const finished=store.now();const delivered=!error;const done=job.attempt_count>=maxAttempts;const delay=retrySeconds[Math.min(job.attempt_count-1,retrySeconds.length-1)];const next=delivered||done?job.next_attempt_at:new Date(Date.now()+delay*1000).toISOString();const finalStatus:DeliveryStatus=delivered?'delivered':done?'failed':'pending';store.transaction(()=>{store.run('UPDATE webhook_attempts SET finished_at=?,http_status=?,duration_ms=?,error=?,response_excerpt=\'\' WHERE delivery_id=? AND attempt=?',finished,status,Date.now()-started,error,job.id,job.attempt_count);store.run('UPDATE webhook_deliveries SET status=?,next_attempt_at=?,delivered_at=?,last_http_status=?,last_error=?,lease_token=NULL,locked_until=NULL WHERE id=? AND lease_token=?',finalStatus,next,delivered?finished:null,status,error,job.id,job.lease_token);});
  }
  const due=store.one<{next_attempt_at:string}>('SELECT MIN(next_attempt_at) AS next_attempt_at FROM webhook_deliveries WHERE status=\'pending\'');return{processed:jobs.length,next_attempt_at:due?.next_attempt_at||null};
}
export function signOutgoingWebhook(secret:string,timestamp:string,payload:string){return createHmac('sha256',secret).update(`${timestamp}.${payload}`).digest('hex');}
export function verifyOutgoingWebhook(secret:string,timestamp:string,payload:string,signature:string,nowSeconds=Math.floor(Date.now()/1000)){if(!/^\d+$/.test(timestamp)||Math.abs(nowSeconds-Number(timestamp))>300)return false;const expected=Buffer.from(`v1=${signOutgoingWebhook(secret,timestamp,payload)}`);const received=Buffer.from(signature);return expected.length===received.length&&timingSafeEqual(expected,received);}
