import { createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import type { LedgerStore } from './store';
import { ApiError } from './errors';
import { stripeApiKeyMatchesMode, verifyStripeWebhook, type StripeCheckout, type StripeCheckoutStatus, type StripeEvent } from './stripe';
import { authSession, beginAdminLogin, enrollAdminMfa, isAdminSession, pendingMfaStage, revokeAdminSession, setMfaCookie, verifyAdminMfa } from './admin-auth';
import type { Payment, Product, Credential, Approval, Event, Snapshot, Registration, PaymentActivityDay } from '../types';
import { acceptMerchantInvite, clearMerchantCookie, createMerchantInvite, enrollMerchantMfa, merchantActor, merchantAuthSession, merchantLogin, revokeMerchantSessions, setMerchantCookie, verifyMerchantMfa } from './merchant-auth';
import { migrateMfaSecrets } from './mfa-crypto';
export { ApiError } from './errors';
export type Actor={id:string;name:string;scopes:string[];tenant_id:string;credential?:Credential};
export type PaymentProviderReadiness={provider_status:'sandbox'|'ready'|'setup_required';checkout_enabled:boolean;provider_mode?:'test'|'live'};
export type PaymentProviderEnvironment={AGORA_DEPLOYMENT_ENV?:string;VERCEL_ENV?:string;NODE_ENV?:string;AGORA_PAYMENT_PROVIDER?:string;AGORA_STRIPE_MODE?:string;STRIPE_TEST_SECRET_KEY?:string;STRIPE_LIVE_SECRET_KEY?:string;STRIPE_TEST_WEBHOOK_SECRET?:string;STRIPE_LIVE_WEBHOOK_SECRET?:string;AGORA_PUBLIC_ORIGIN?:string};
function isProductionDeployment(env:PaymentProviderEnvironment=process.env){return env.AGORA_DEPLOYMENT_ENV==='production'||env.VERCEL_ENV==='production'||(env.NODE_ENV==='production'&&env.AGORA_DEPLOYMENT_ENV!=='qa');}
export function paymentProviderReadiness(env:PaymentProviderEnvironment=process.env):PaymentProviderReadiness{
 const provider=env.AGORA_PAYMENT_PROVIDER||'sandbox';
 if(provider==='sandbox')return isProductionDeployment(env)?{provider_status:'setup_required',checkout_enabled:false}:{provider_status:'sandbox',checkout_enabled:true};
 if(provider!=='stripe')return{provider_status:'setup_required',checkout_enabled:false};
 const mode=env.AGORA_STRIPE_MODE;
 if(mode!=='test'&&mode!=='live')return{provider_status:'setup_required',checkout_enabled:false};
 const key=mode==='live'?env.STRIPE_LIVE_SECRET_KEY:env.STRIPE_TEST_SECRET_KEY;
 const webhook=mode==='live'?env.STRIPE_LIVE_WEBHOOK_SECRET:env.STRIPE_TEST_WEBHOOK_SECRET;
 const validKey=stripeApiKeyMatchesMode(key,mode);
 if(!validKey||!webhook||!env.AGORA_PUBLIC_ORIGIN)return{provider_status:'setup_required',checkout_enabled:false};
 return{provider_status:'ready',checkout_enabled:true,provider_mode:mode};
}
export function requirePaymentProviderReady(){const state=paymentProviderReadiness();if(!state.checkout_enabled)throw new ApiError(503,'provider_not_configured','Payment acceptance is unavailable until a mode-matched processor API key, webhook secret, and public origin are configured.');return state;}
export const owner:Actor={id:'console_owner',name:'You',scopes:['*'],tenant_id:'owner'};
export function requireScope(actor:Actor,scope:string){if(!actor.scopes.includes('*')&&!actor.scopes.includes(scope))throw new ApiError(403,'permission_denied',`This key needs ${scope}.`)}
export function requireProviderMode(actor:Actor,mode:'sandbox'|'test'|'live'){if(actor.credential&&(actor.credential.provider_mode||'sandbox')!==mode)throw new ApiError(403,'key_mode_mismatch','This API key is restricted to a different payment mode. Issue a new key for the selected mode.');}
export function requirePaymentMode(store:LedgerStore,actor:Actor,paymentId:string){if(!actor.credential)return;const payment=store.one<{provider:string;provider_mode:string|null}>('SELECT provider,provider_mode FROM payments WHERE id=? AND tenant_id=?',paymentId,actor.tenant_id);if(!payment)throw new ApiError(404,'not_found','Payment not found.');const mode=payment.provider==='stripe'?(payment.provider_mode||'test'):'sandbox';if(mode!=='sandbox'&&mode!=='test'&&mode!=='live')throw new ApiError(409,'provider_mode_invalid','Payment mode is invalid.');requireProviderMode(actor,mode);}
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
const money=z.number().int().min(1).max(10000000);
const text=z.string().trim().min(1).max(120);
export const scopes=['products:read','products:write','payments:read','payments:write','refunds:write','events:read'] as const;
function parse<T>(schema:z.ZodType<T>,body:unknown):T { const parsed=schema.safeParse(body);if(!parsed.success)throw new ApiError(422,'invalid_request',parsed.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; '));return parsed.data; }
export function authenticateWith(store:LedgerStore,request:Request):Actor{const raw=request.headers.get('authorization')?.replace(/^Bearer /,'');if(!raw)throw new ApiError(401,'unauthorized','Provide an Agora API key as a Bearer token.');const key=store.one<Credential&{hash:string;scopes:string}>('SELECT * FROM credentials WHERE hash=? AND revoked=0',hash(raw));if(!key)throw new ApiError(401,'unauthorized','This key is invalid or revoked.');const tenantId=key.tenant_id||'owner';const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',tenantId);if(!tenant||tenant.status!=='approved')throw new ApiError(403,'merchant_pending','This merchant is not approved for API access.');const credential={...key,tenant_id:tenantId,scopes:JSON.parse(key.scopes as unknown as string)} as Credential;return{id:key.id,name:key.name,scopes:credential.scopes,tenant_id:tenantId,credential};}
export function hasAdminSession(store:LedgerStore,request:Request){return isAdminSession(store,request);}
export function setSessionCookie(response:Response,request:Request,session?:{value:string;expires:number}){return setMfaCookie(response,request,'owner',session);}
export function requireSameOrigin(request:Request,required=false){const host=request.headers.get('host');const origin=request.headers.get('origin');const configured=process.env.AGORA_PUBLIC_ORIGIN;if(configured){let expected:URL;try{expected=new URL(configured)}catch{throw new ApiError(503,'auth_not_configured','AGORA_PUBLIC_ORIGIN must be a valid origin.')}if(expected.origin!==configured.replace(/\/$/,''))throw new ApiError(503,'auth_not_configured','AGORA_PUBLIC_ORIGIN must contain only scheme and host.');if(required&&!origin)throw new ApiError(403,'origin_rejected','A same-origin request is required.');if(origin&&origin!==expected.origin)throw new ApiError(403,'origin_rejected','Use the configured same-origin console.');}else if(origin){let parsed:URL;try{parsed=new URL(origin)}catch{throw new ApiError(403,'origin_rejected','Use the same-origin console.')}if(!host||parsed.host!==host)throw new ApiError(403,'origin_rejected','Use the same-origin console.');}else if(required)throw new ApiError(403,'origin_rejected','A same-origin request is required.');if(request.headers.get('sec-fetch-site')==='cross-site')throw new ApiError(403,'origin_rejected','Cross-site console requests are rejected.');}
export function consoleActorWith(store:LedgerStore,request:Request,write=false){requireSameOrigin(request,write);if(process.env.NODE_ENV==='production'&&!process.env.AGORA_PUBLIC_ORIGIN)throw new ApiError(503,'auth_not_configured','Set AGORA_PUBLIC_ORIGIN to the canonical browser origin.');if(hasAdminSession(store,request))return owner;const actor=merchantActor(store,request);if(actor)return actor;throw new ApiError(401,'authentication_required','Sign in with MFA to access this workspace.');}
function canonical(value:unknown):string{if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical((value as Record<string,unknown>)[k])).join(',')+'}';return JSON.stringify(value);}
export function mutate<T>(store:LedgerStore,actor:Actor,route:string,key:string|null,body:unknown,fn:()=>T):T{if(!key||key.length>200)throw new ApiError(400,'idempotency_required','Provide an Idempotency-Key of 1–200 characters.');return store.transaction(()=>{if(actor.credential){const fresh=store.one<Credential>('SELECT * FROM credentials WHERE id=? AND revoked=0',actor.id);if(!fresh)throw new ApiError(401,'unauthorized','This key has been revoked.');const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',fresh.tenant_id);if(!tenant||tenant.status!=='approved')throw new ApiError(403,'merchant_pending','This merchant is not approved for API access.');actor.credential={...fresh,scopes:actor.scopes};}const fingerprint=hash(canonical(body));const prior=store.one<{hash:string;response:string}>('SELECT * FROM idempotency WHERE actor=? AND route=? AND key=?',actor.id,route,key);if(prior){if(prior.hash!==fingerprint)throw new ApiError(409,'idempotency_conflict','This idempotency key was used with a different request.');return JSON.parse(prior.response) as T;}const value=fn();store.run('INSERT INTO idempotency(actor,route,key,hash,response) VALUES(?,?,?,?,?)',actor.id,route,key,fingerprint,JSON.stringify(value));return value;});}
export function createProduct(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'products:write');const b=parse(z.object({name:text,description:z.string().trim().max(400).default(''),amount:money,currency:z.literal('usd').default('usd')}).strict(),body);const p={id:store.id('prod'),...b,created_at:store.now()};store.run('INSERT INTO products(id,name,description,amount,currency,created_at,tenant_id) VALUES(?,?,?,?,?,?,?)',p.id,p.name,p.description,p.amount,p.currency,p.created_at,actor.tenant_id);store.event('product.created',actor.name,p.id,{amount:p.amount},actor.tenant_id);return p;}
export function createPayment(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'payments:write');const b=parse(z.object({product_id:text,customer:z.string().trim().max(120).default('Guest')}).strict(),body);const p=store.one<Product>('SELECT * FROM products WHERE id=? AND tenant_id=?',b.product_id,actor.tenant_id);if(!p)throw new ApiError(404,'not_found','Product not found.');if(actor.credential&&p.amount>actor.credential.max_amount)throw new ApiError(403,'limit_exceeded','This price exceeds the key’s per-payment limit.');const payment:Payment={id:store.id('pay'),product_id:p.id,product_name:p.name,customer:b.customer||'Guest',amount:p.amount,refunded:0,currency:'usd',status:'pending',actor:actor.name,created_at:store.now(),checkout_token:randomBytes(24).toString('hex'),sample:0,tenant_id:actor.tenant_id};store.run('INSERT INTO payments(id,product_id,product_name,customer,amount,refunded,currency,status,actor,created_at,checkout_token,sample,tenant_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',payment.id,payment.product_id,payment.product_name,payment.customer,payment.amount,0,'usd','pending',actor.name,payment.created_at,payment.checkout_token,0,actor.tenant_id);store.event('payment.created',actor.name,payment.id,{amount:p.amount},actor.tenant_id);return payment;}
function refundable(store:LedgerStore,tenantId:string,pid:string,amount:number){const p=store.one<Payment&{provider?:string}>('SELECT * FROM payments WHERE id=? AND tenant_id=?',pid,tenantId);if(!p)throw new ApiError(404,'not_found','Payment not found.');const pending=p.provider==='stripe'?store.one<{amount:number|null}>("SELECT SUM(amount) AS amount FROM refunds WHERE payment_id=? AND tenant_id=? AND status='pending'",pid,tenantId)?.amount||0:0;if(p.status!=='succeeded'||amount>p.amount-p.refunded-pending)throw new ApiError(409,'not_refundable','The payment does not have enough refundable funds.');return p;}
function executeRefund(store:LedgerStore,actor:string,tenantId:string,pid:string,amount:number,reason:string,credentialId:string|null=null){const payment=refundable(store,tenantId,pid,amount);if(isProductionDeployment()&&payment.provider!=='stripe')throw new ApiError(503,'provider_not_configured','Sandbox refunds are disabled in production.');const refundId=store.id('ref');const createdAt=store.now();if(payment.provider==='stripe'){const mode=(payment as Payment&{provider_mode?:string|null}).provider_mode;if(mode!=='test'&&mode!=='live')throw new ApiError(409,'provider_mode_invalid','Stripe payment mode is missing.');store.run("INSERT INTO refunds(id,payment_id,amount,reason,actor,created_at,tenant_id,status,provider_mode,credential_id) VALUES(?,?,?,?,?,?,?,'pending',?,?)",refundId,pid,amount,reason,actor,createdAt,tenantId,mode,credentialId);store.event('refund.requested',actor,pid,{refund_id:refundId,amount},tenantId);return{id:refundId,payment_id:pid,amount,reason,status:'pending',provider:'stripe',provider_mode:mode,created_at:createdAt};}const refund={id:refundId,payment_id:pid,amount,reason,status:'succeeded',created_at:createdAt};store.run('UPDATE payments SET refunded=refunded+? WHERE id=? AND tenant_id=?',amount,pid,tenantId);store.run("INSERT INTO refunds(id,payment_id,amount,reason,actor,created_at,tenant_id,status,credential_id) VALUES(?,?,?,?,?,?,?,'succeeded',?)",refund.id,pid,amount,reason,actor,refund.created_at,tenantId,credentialId);store.journal(refund.id,-amount,'processor_receivable',tenantId);store.event('refund.succeeded',actor,pid,{refund_id:refund.id,amount,reason},tenantId);return refund;}
export function createRefund(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'refunds:write');const b=parse(z.object({payment_id:text,amount:money,reason:z.string().trim().min(3).max(400)}).strict(),body);const payment=refundable(store,actor.tenant_id,b.payment_id,b.amount);const paymentMode=payment.provider==='stripe'?payment.provider_mode||'test':'sandbox';requireProviderMode(actor,paymentMode as 'sandbox'|'test'|'live');if(isProductionDeployment()&&payment.provider!=='stripe')throw new ApiError(503,'provider_not_configured','Sandbox refunds are disabled in production.');const c=actor.credential;const pendingBudget=c?Number(store.one<{amount:number}>('SELECT COALESCE(SUM(amount),0) AS amount FROM refunds WHERE credential_id=? AND tenant_id=? AND status=\'pending\'',c.id,actor.tenant_id)?.amount||0):0;if(c&&b.amount>c.refund_budget-c.spent-pendingBudget){const a={id:store.id('apr'),...b,credential_id:c.id,actor:actor.name,status:'pending',created_at:store.now(),tenant_id:actor.tenant_id};store.run('INSERT INTO approvals(id,payment_id,amount,reason,credential_id,actor,status,created_at,tenant_id) VALUES(?,?,?,?,?,?,?,?,?)',a.id,a.payment_id,a.amount,a.reason,a.credential_id,a.actor,a.status,a.created_at,a.tenant_id);store.event('approval.requested',actor.name,a.id,{payment_id:a.payment_id,amount:a.amount},actor.tenant_id);return{...a,status:'requires_approval'};}const r=executeRefund(store,actor.name,actor.tenant_id,b.payment_id,b.amount,b.reason,c?.id||null);if(c&&r.status==='succeeded')store.run('UPDATE credentials SET spent=spent+? WHERE id=? AND tenant_id=?',b.amount,c.id,actor.tenant_id);return r;}
export function resolveApproval(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'*');if(actor.tenant_id!=='owner')throw new ApiError(403,'permission_denied','Only the workspace owner can resolve refund approvals.');const b=parse(z.object({approval_id:text,decision:z.enum(['approve','decline'])}).strict(),body);const a=store.one<Approval>('SELECT * FROM approvals WHERE id=?',b.approval_id);if(!a)throw new ApiError(404,'not_found','Approval not found.');if(a.status!=='pending')throw new ApiError(409,'already_resolved','This request has already been reviewed.');let refund:ReturnType<typeof executeRefund>|undefined;if(b.decision==='approve'){if(!store.one('SELECT id FROM credentials WHERE id=? AND revoked=0',a.credential_id))throw new ApiError(409,'key_revoked','The requesting key has been revoked. Decline this request.');refund=executeRefund(store,`${actor.name} approved ${a.actor}`,a.tenant_id||'owner',a.payment_id,a.amount,a.reason,a.credential_id);if(refund.status==='succeeded')store.run('UPDATE credentials SET spent=spent+? WHERE id=? AND tenant_id=?',a.amount,a.credential_id,a.tenant_id||'owner');}const status=b.decision==='approve'?'approved':'declined';store.run('UPDATE approvals SET status=? WHERE id=?',status,a.id);store.event(`approval.${status}`,actor.name,a.id,{amount:a.amount},a.tenant_id||'owner');return{...a,status,...(refund?.status==='pending'?{refund}:{})};}
export function createCredential(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'*');const b=parse(z.object({name:text,kind:z.enum(['agent','developer']),scopes:z.array(z.enum(scopes)).min(1),max_amount:money,refund_budget:z.number().int().min(0).max(10000000),tenant_id:text.optional()}).strict(),body);if(actor.tenant_id!=='owner'&&b.tenant_id&&b.tenant_id!==actor.tenant_id)throw new ApiError(404,'not_found','Merchant not found.');const tenantId=actor.tenant_id==='owner'?(b.tenant_id||'owner'):actor.tenant_id;const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',tenantId);if(!tenant||tenant.status!=='approved')throw new ApiError(409,'merchant_pending','Approve the merchant before issuing an API key.');const paymentProvider:string=process.env.AGORA_PAYMENT_PROVIDER||'sandbox';const configuredMode=process.env.AGORA_STRIPE_MODE;const readiness=paymentProviderReadiness();if(!readiness.checkout_enabled)throw new ApiError(503,'provider_not_configured','Payment provider setup is incomplete; issue keys only after the processor mode and webhook are configured.');const providerMode=paymentProvider==='stripe'&&(configuredMode==='test'||configuredMode==='live')?configuredMode:'sandbox';const secret=`ag_${providerMode==='live'?'live':'test'}_${randomBytes(24).toString('hex')}`;const c={id:store.id('key'),...b,tenant_id:tenantId,provider_mode:providerMode,prefix:secret.slice(0,16),spent:0,revoked:0,created_at:store.now()};store.run('INSERT INTO credentials(id,name,kind,prefix,hash,scopes,max_amount,refund_budget,spent,revoked,created_at,tenant_id,provider_mode) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',c.id,c.name,c.kind,c.prefix,hash(secret),JSON.stringify(c.scopes),c.max_amount,c.refund_budget,0,0,c.created_at,c.tenant_id,c.provider_mode);store.event('key.created',actor.name,c.id,{name:c.name,scopes:c.scopes,tenant_id:c.tenant_id,provider_mode:c.provider_mode},c.tenant_id);return{...c,secret};}
export function revokeCredential(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'*');const b=parse(z.object({key_id:text}).strict(),body);const credential=store.one<Credential>('SELECT id,tenant_id FROM credentials WHERE id=?',b.key_id);if(!credential)throw new ApiError(404,'not_found','Key not found.');if(actor.tenant_id!=='owner'&&credential.tenant_id!==actor.tenant_id)throw new ApiError(404,'not_found','Key not found.');store.run('UPDATE credentials SET revoked=1 WHERE id=?',b.key_id);store.event('key.revoked',actor.name,b.key_id,{tenant_id:credential.tenant_id},credential.tenant_id);return{id:b.key_id,revoked:true};}
export function registerMerchant(store:LedgerStore,body:unknown){const b=parse(z.object({business_name:text,owner_name:text,email:z.string().trim().email().max(254)}).strict(),body);const since=new Date(Date.now()-24*60*60*1000).toISOString();if(store.one('SELECT id FROM registrations WHERE lower(email)=lower(?) AND created_at>=?',b.email,since))throw new ApiError(409,'registration_exists','A recent registration already exists for this email.');const registrationId=store.id('reg');const tenantId=store.id('tn');const createdAt=store.now();store.transaction(()=>{store.run("INSERT INTO tenants(id,business_name,email,status,provider,provider_account_id,created_at,approved_at) VALUES(?,?,?,'pending','stripe',NULL,?,NULL)",tenantId,b.business_name,b.email,createdAt);store.run("INSERT INTO registrations(id,business_name,owner_name,email,provider,provider_account_id,status,tenant_id,created_at,reviewed_at,review_reason) VALUES(?,?,?,?,'stripe',NULL,'pending',?,?,NULL,NULL)",registrationId,b.business_name,b.owner_name,b.email,tenantId,createdAt);store.event('registration.created','Public registration',registrationId,{business_name:b.business_name,email:b.email},tenantId);});return{registration_id:registrationId,status:'pending' as const,provider_status:'not_connected' as const};}
export function reviewRegistration(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'*');if(actor.tenant_id!=='owner')throw new ApiError(403,'permission_denied','Only the workspace owner can review registrations.');const b=parse(z.object({registration_id:text,decision:z.enum(['approve','reject']),reason:z.string().trim().max(400).optional()}).strict(),body);const registration=store.one<Registration>('SELECT * FROM registrations WHERE id=?',b.registration_id);if(!registration)throw new ApiError(404,'not_found','Registration not found.');if(registration.status!=='pending')throw new ApiError(409,'already_reviewed','This registration has already been reviewed.');const status=b.decision==='approve'?'approved':'rejected';store.transaction(()=>{store.run('UPDATE registrations SET status=?,reviewed_at=?,review_reason=? WHERE id=? AND status=\'pending\'',status,store.now(),b.reason||null,b.registration_id);store.run('UPDATE tenants SET status=?,approved_at=? WHERE id=?',status==='approved'?'approved':'rejected',status==='approved'?store.now():null,registration.tenant_id);store.event(`registration.${status}`,actor.name,registration.id,{tenant_id:registration.tenant_id,reason:b.reason||null},'owner');});return{...registration,status,reviewed_at:store.now(),review_reason:b.reason||null,provider_status:'not_connected' as const};}

export function beginStripeConnect(store:LedgerStore,actor:Actor,tenantId:string,mode:'test'|'live',clientId:string,redirectUri:string){
 requireScope(actor,'*');
 if(actor.tenant_id!=='owner'&&actor.tenant_id!==tenantId)throw new ApiError(403,'permission_denied','You can only connect a provider account to your own merchant workspace.');
 const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',tenantId);
 if(!tenant||tenant.status!=='approved')throw new ApiError(409,'merchant_pending','Approve the merchant before connecting a provider account.');
 if(!/^ca_[A-Za-z0-9]+$/.test(clientId))throw new ApiError(503,'provider_not_configured','Stripe Connect is not configured for this mode.');
 let redirect:URL;try{redirect=new URL(redirectUri)}catch{throw new ApiError(503,'provider_not_configured','The Stripe callback URL is invalid.')}
 if(redirect.protocol!=='https:'&&redirect.hostname!=='localhost')throw new ApiError(503,'provider_not_configured','Stripe callback URLs must use HTTPS.');
 const state=randomBytes(32).toString('base64url');const created=store.now();const expires=new Date(Date.now()+10*60_000).toISOString();
 store.transaction(()=>{
  store.run("DELETE FROM provider_oauth_states WHERE expires_at<? OR used_at IS NOT NULL",created);
  store.run('INSERT INTO provider_oauth_states(state_hash,tenant_id,provider,mode,redirect_uri,expires_at,used_at,created_at) VALUES(?,?,?,?,?,?,NULL,?)',hash(state),tenantId,'stripe',mode,redirectUri,expires,created);
 });
 const authorize=new URL('https://connect.stripe.com/oauth/authorize');authorize.searchParams.set('response_type','code');authorize.searchParams.set('client_id',clientId);authorize.searchParams.set('scope','read_write');authorize.searchParams.set('redirect_uri',redirectUri);authorize.searchParams.set('state',state);
 return{state,authorize_url:authorize.toString(),expires_at:expires};
}

export function consumeStripeConnectState(store:LedgerStore,state:string,mode:'test'|'live',redirectUri:string){
 if(!/^[A-Za-z0-9_-]{40,60}$/.test(state))throw new ApiError(400,'invalid_oauth_state','Stripe account connection state is invalid.');
 return store.transaction(()=>{
  const row=store.one<{tenant_id:string;mode:string;redirect_uri:string;expires_at:string;used_at:string|null}>('SELECT tenant_id,mode,redirect_uri,expires_at,used_at FROM provider_oauth_states WHERE state_hash=? AND provider=\'stripe\'',hash(state));
  if(!row||row.used_at||row.mode!==mode||row.redirect_uri!==redirectUri||Date.parse(row.expires_at)<=Date.now())throw new ApiError(400,'invalid_oauth_state','Stripe account connection state is invalid or expired.');
  const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',row.tenant_id);
  if(!tenant||tenant.status!=='approved')throw new ApiError(403,'merchant_pending','This merchant is not approved for provider access.');
  store.run('UPDATE provider_oauth_states SET used_at=? WHERE state_hash=? AND used_at IS NULL',store.now(),hash(state));
  return{tenant_id:row.tenant_id};
 });
}

export function saveStripeConnectedAccount(store:LedgerStore,tenantId:string,mode:'test'|'live',account:{id:string;charges_enabled:boolean;payouts_enabled:boolean;details_submitted:boolean;capabilities:Record<string,string>}){
 if(!/^acct_[A-Za-z0-9]+$/.test(account.id))throw new ApiError(400,'provider_account_invalid','Stripe returned an invalid account identifier.');
 const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',tenantId);if(!tenant||tenant.status!=='approved')throw new ApiError(403,'merchant_pending','This merchant is not approved for provider access.');
 const occupied=store.one<{tenant_id:string}>('SELECT tenant_id FROM tenant_provider_accounts WHERE provider=\'stripe\' AND mode=? AND account_id=?',mode,account.id);if(occupied&&occupied.tenant_id!==tenantId)throw new ApiError(409,'provider_account_in_use','This Stripe account is already linked to another Agora merchant.');
 const status=account.charges_enabled?'connected':'charges_pending';
 store.transaction(()=>{
  store.run('INSERT INTO tenant_provider_accounts(tenant_id,provider,mode,account_id,status,charges_enabled,payouts_enabled,details_submitted,capabilities,connected_at) VALUES(?,\'stripe\',?,?,?,?,?,?,?,?) ON CONFLICT(tenant_id,provider,mode) DO UPDATE SET account_id=excluded.account_id,status=excluded.status,charges_enabled=excluded.charges_enabled,payouts_enabled=excluded.payouts_enabled,details_submitted=excluded.details_submitted,capabilities=excluded.capabilities,connected_at=excluded.connected_at',tenantId,mode,account.id,status,account.charges_enabled?1:0,account.payouts_enabled?1:0,account.details_submitted?1:0,JSON.stringify(account.capabilities),store.now());
  store.event('provider.stripe.connected','Stripe OAuth',account.id,{mode,status,charges_enabled:account.charges_enabled,payouts_enabled:account.payouts_enabled},tenantId);
 });
 return{account_id:account.id,mode,status,charges_enabled:account.charges_enabled,payouts_enabled:account.payouts_enabled,details_submitted:account.details_submitted,capabilities:account.capabilities};
}

export function stripeAccountForTenant(store:LedgerStore,tenantId:string,mode:'test'|'live'){
 const row=store.one<{account_id:string;status:string;charges_enabled:number;capabilities:string}>('SELECT account_id,status,charges_enabled,capabilities FROM tenant_provider_accounts WHERE tenant_id=? AND provider=\'stripe\' AND mode=?',tenantId,mode);
 return row?{account_id:row.account_id,status:row.status,charges_enabled:!!row.charges_enabled,capabilities:JSON.parse(row.capabilities) as Record<string,string>}:null;
}

export function disconnectStripeAccount(store:LedgerStore,actor:Actor,tenantId:string,mode:'test'|'live'){
 requireScope(actor,'*');if(actor.tenant_id!=='owner'&&actor.tenant_id!==tenantId)throw new ApiError(403,'permission_denied','You can only disconnect your own merchant provider account.');
 const account=store.one<{account_id:string}>('SELECT account_id FROM tenant_provider_accounts WHERE tenant_id=? AND provider=\'stripe\' AND mode=?',tenantId,mode);if(!account)return{disconnected:false};
 store.transaction(()=>{store.run("UPDATE tenant_provider_accounts SET status='disconnected',charges_enabled=0,payouts_enabled=0 WHERE tenant_id=? AND provider='stripe' AND mode=?",tenantId,mode);store.run('UPDATE credentials SET revoked=1 WHERE tenant_id=?',tenantId);store.event('provider.stripe.disconnected','Agora owner',account.account_id,{mode},tenantId);});
 return{disconnected:true,account_id:account.account_id,mode};
}
export function simulate(store:LedgerStore,token:string,body:unknown){const b=parse(z.object({outcome:z.enum(['succeeded','failed'])}).strict(),body);return store.transaction(()=>{const p=store.one<Payment&{provider?:string}>('SELECT * FROM payments WHERE checkout_token=? AND sample=0',token);if(!p)throw new ApiError(404,'not_found','Checkout not found.');if(p.provider==='stripe')throw new ApiError(409,'processor_checkout','Stripe checkouts must complete through Stripe; sandbox simulation is disabled.');if(isProductionDeployment())throw new ApiError(503,'provider_not_configured','Sandbox payment simulation is disabled in production.');if(p.status!=='pending'){if(p.status===b.outcome)return{status:p.status,id:p.id};throw new ApiError(409,'already_completed','This checkout has already completed.');}store.run('UPDATE payments SET status=? WHERE id=?',b.outcome,p.id);if(b.outcome==='succeeded')store.journal(p.id,p.amount,'processor_receivable',p.tenant_id||'owner');store.event(`payment.${b.outcome}`,'Sandbox checkout',p.id,{amount:p.amount},p.tenant_id||'owner');return{status:b.outcome,id:p.id};});}
export function prepareStripePayment(store:LedgerStore,paymentId:string,mode:'test'|'live',tenantId='owner',accountId:string|null=null){const current=store.one<{provider:string;provider_mode:string|null;provider_account_id:string|null;status:string}>('SELECT provider,provider_mode,provider_account_id,status FROM payments WHERE id=? AND tenant_id=?',paymentId,tenantId);if(!current||current.status!=='pending')throw new ApiError(409,'payment_not_pending','This payment is no longer pending.');if(current.provider==='stripe'&&current.provider_mode&&current.provider_mode!==mode)throw new ApiError(409,'provider_mode_conflict','This payment was started in a different Stripe mode.');store.run("UPDATE payments SET provider='stripe',provider_mode=?,provider_account_id=? WHERE id=? AND tenant_id=? AND status='pending'",mode,accountId,paymentId,tenantId);}
export function saveStripeSession(store:LedgerStore,paymentId:string,session:StripeCheckout,mode:'test'|'live',tenantId='owner',accountId:string|null=null){const current=store.one<{provider:string;provider_mode:string|null;provider_session_id:string|null;provider_account_id:string|null}>('SELECT provider,provider_mode,provider_session_id,provider_account_id FROM payments WHERE id=? AND tenant_id=?',paymentId,tenantId);if(!current||current.provider!=='stripe'||current.provider_mode!==mode||(current.provider_session_id&&current.provider_session_id!==session.id)||(current.provider_account_id||null)!==accountId)throw new ApiError(409,'provider_session_conflict','Stripe Checkout session does not match the pending payment attempt.');store.run("UPDATE payments SET provider_session_id=COALESCE(provider_session_id,?),provider_checkout_url=COALESCE(provider_checkout_url,?),provider_payment_intent=COALESCE(provider_payment_intent,?) WHERE id=? AND tenant_id=? AND provider='stripe' AND provider_mode=?",session.id,session.url,session.payment_intent,paymentId,tenantId,mode);}
export function stripePaymentReconcileContext(store:LedgerStore,paymentId:string,tenantId:string){const row=store.one<{id:string;tenant_id:string;amount:number;currency:string;status:Payment['status'];provider:string;provider_mode:string|null;provider_session_id:string|null;provider_payment_intent:string|null;provider_account_id:string|null}>('SELECT id,tenant_id,amount,currency,status,provider,provider_mode,provider_session_id,provider_payment_intent,provider_account_id FROM payments WHERE id=? AND tenant_id=?',paymentId,tenantId);if(!row||row.provider!=='stripe'||!row.provider_mode||!row.provider_session_id)throw new ApiError(404,'not_found','Stripe payment not found.');return row;}
export function reconcileStripePayment(store:LedgerStore,paymentId:string,tenantId:string,session:StripeCheckoutStatus){return store.transaction(()=>{const payment=stripePaymentReconcileContext(store,paymentId,tenantId);const mode=payment.provider_mode;if(mode!=='test'&&mode!=='live')throw new ApiError(409,'provider_mode_invalid','Stripe payment mode is missing.');if(session.id!==payment.provider_session_id||session.livemode!==(mode==='live')||session.amount_total!==payment.amount||session.currency!==payment.currency||session.client_reference_id!==payment.id||session.metadata.agora_payment_id!==payment.id||session.metadata.agora_tenant_id!==tenantId||(typeof session.payment_intent==='string'&&payment.provider_payment_intent&&session.payment_intent!==payment.provider_payment_intent))throw new ApiError(409,'provider_reconcile_mismatch','Stripe Checkout details do not match this Agora payment.');let next:Payment['status']|null=null;if(session.status==='complete'&&session.payment_status==='paid')next='succeeded';else if(session.status==='expired')next='failed';if(next&&payment.status==='pending'){store.run("UPDATE payments SET status=?,provider_payment_intent=COALESCE(provider_payment_intent,?) WHERE id=? AND tenant_id=? AND status='pending'",next,session.payment_intent,paymentId,tenantId);if(next==='succeeded')store.journal(paymentId,payment.amount,'processor_receivable',tenantId);store.event(`payment.${next}`,'Stripe reconciliation',paymentId,{provider_session_id:session.id},tenantId);return{id:paymentId,status:next,reconciled:true};}return{id:paymentId,status:payment.status,reconciled:false};});}
export function stripeRefundContext(store:LedgerStore,refundId:string){const row=store.one<{id:string;payment_id:string;tenant_id:string;amount:number;status:string;provider_mode:string;payment_intent:string|null;provider_account_id:string|null}>('SELECT refunds.id,refunds.payment_id,refunds.tenant_id,refunds.amount,refunds.status,refunds.provider_mode,payments.provider_payment_intent AS payment_intent,payments.provider_account_id FROM refunds JOIN payments ON payments.id=refunds.payment_id AND payments.tenant_id=refunds.tenant_id WHERE refunds.id=?',refundId);if(!row||row.status!=='pending'||!row.payment_intent)throw new ApiError(409,'refund_not_ready','Stripe refund is not ready to submit; payment confirmation may still be pending.');return row;}
export function stripeRefundResult(store:LedgerStore,refundId:string,tenantId:string){const row=store.one<{id:string;payment_id:string;tenant_id:string;amount:number;reason:string;status:string;provider_mode:string|null;provider_refund_id:string|null}>('SELECT id,payment_id,tenant_id,amount,reason,status,provider_mode,provider_refund_id FROM refunds WHERE id=? AND tenant_id=?',refundId,tenantId);if(!row)throw new ApiError(404,'refund_not_found','Refund request not found.');return row;}
export function recordStripeRefundResult(store:LedgerStore,refundId:string,providerRefundId:string|null,status:'pending'|'succeeded'|'failed'|'canceled'){
 const refund=store.one<{id:string;payment_id:string;tenant_id:string;amount:number;status:string;provider_mode:string;credential_id:string|null;provider_refund_id:string|null}>('SELECT * FROM refunds WHERE id=?',refundId);if(!refund)throw new ApiError(404,'refund_not_found','Refund request not found.');if(refund.provider_refund_id&&providerRefundId&&refund.provider_refund_id!==providerRefundId)throw new ApiError(409,'refund_provider_conflict','Stripe refund ID does not match the stored request.');if(refund.status==='succeeded'||refund.status==='failed')return{status:refund.status as 'succeeded'|'failed',id:refund.id,provider_refund_id:refund.provider_refund_id};const normalized=status==='canceled'?'failed':status;store.run('UPDATE refunds SET provider_refund_id=COALESCE(provider_refund_id,?),status=? WHERE id=? AND tenant_id=?',providerRefundId,normalized,refundId,refund.tenant_id);if(normalized==='succeeded'){
   const payment=store.one<Payment>('SELECT * FROM payments WHERE id=? AND tenant_id=?',refund.payment_id,refund.tenant_id);if(!payment||payment.status!=='succeeded'||payment.refunded+refund.amount>payment.amount)throw new ApiError(409,'refund_limit_changed','Processor refund exceeds the remaining refundable amount.');
   store.run('UPDATE payments SET refunded=refunded+? WHERE id=? AND tenant_id=?',refund.amount,refund.payment_id,refund.tenant_id);if(refund.credential_id)store.run('UPDATE credentials SET spent=spent+? WHERE id=? AND tenant_id=?',refund.amount,refund.credential_id,refund.tenant_id);store.journal(refund.id,-refund.amount,'processor_receivable',refund.tenant_id);store.event('refund.succeeded','Stripe webhook',refund.payment_id,{refund_id:refund.id,provider_refund_id:providerRefundId,amount:refund.amount},refund.tenant_id);
  }else if(normalized==='failed')store.event('refund.failed','Stripe webhook',refund.payment_id,{refund_id:refund.id,provider_refund_id:providerRefundId,amount:refund.amount},refund.tenant_id);
 return{status:normalized,id:refund.id,provider_refund_id:providerRefundId||refund.provider_refund_id};
}
function applyStripeEvent(store:LedgerStore,event:StripeEvent,mode:'test'|'live'){
 const obj=event.data.object;const metadata=(obj.metadata&&typeof obj.metadata==='object'?obj.metadata:{}) as Record<string,unknown>;
 if(store.one('SELECT id FROM stripe_webhook_events WHERE id=?',event.id))return{received:true,duplicate:true};
 if(event.type==='refund.updated'){
  const refundId=typeof metadata.agora_refund_id==='string'?metadata.agora_refund_id:null;const refund=refundId?store.one<{id:string;payment_id:string;amount:number;provider_mode:string;payment_intent:string|null;provider_account_id:string|null}>('SELECT refunds.id,refunds.payment_id,refunds.amount,refunds.provider_mode,payments.provider_payment_intent AS payment_intent,payments.provider_account_id FROM refunds JOIN payments ON payments.id=refunds.payment_id AND payments.tenant_id=refunds.tenant_id WHERE refunds.id=?',refundId):undefined;
  if(!refund||refund.provider_mode!==mode||(refund.provider_account_id||undefined)!==event.account||typeof obj.amount!=='number'||obj.amount!==refund.amount||typeof obj.payment_intent==='string'&&obj.payment_intent!==refund.payment_intent||typeof obj.id!=='string'||!['pending','succeeded','failed','canceled'].includes(String(obj.status)))throw new ApiError(400,'webhook_refund_mismatch','Stripe refund event does not match a pending Agora refund.');
  store.run('INSERT INTO stripe_webhook_events(id,livemode,received_at) VALUES(?,?,?)',event.id,mode==='live'?1:0,store.now());const status=obj.status as 'pending'|'succeeded'|'failed'|'canceled';const result=recordStripeRefundResult(store,refund.id,obj.id,status);return{received:true,duplicate:false,refund:result};
 }
 const paymentId=typeof metadata.agora_payment_id==='string'?metadata.agora_payment_id:typeof obj.client_reference_id==='string'?obj.client_reference_id:null;
 const tenantId=typeof metadata.agora_tenant_id==='string'?metadata.agora_tenant_id:null;
 if(!paymentId||!tenantId)throw new ApiError(400,'webhook_mapping_invalid','Stripe event is not mapped to an Agora payment.');
 const payment=store.one<Payment&{provider:string;provider_mode:string|null;provider_session_id:string|null;provider_payment_intent:string|null;provider_account_id:string|null}>('SELECT * FROM payments WHERE id=? AND tenant_id=?',paymentId,tenantId);
 if(!payment||payment.provider!=='stripe'||payment.provider_mode!==mode)throw new ApiError(404,'webhook_payment_not_found','Stripe event does not match an active payment in this mode.');
 if((payment.provider_account_id||undefined)!==event.account)throw new ApiError(400,'webhook_account_mismatch','Stripe account does not match the account linked to this payment.');
 if(typeof obj.id==='string'&&payment.provider_session_id&&payment.provider_session_id!==obj.id)throw new ApiError(400,'webhook_mapping_invalid','Stripe Checkout session does not match the payment.');
 if(['checkout.session.completed','checkout.session.async_payment_succeeded','checkout.session.async_payment_failed','checkout.session.expired'].includes(event.type)&&(!Number.isSafeInteger(obj.amount_total)||obj.amount_total!==payment.amount||obj.currency!==payment.currency))throw new ApiError(400,'webhook_amount_mismatch','Stripe event amount or currency does not match the payment.');
 if(typeof obj.payment_intent==='string'&&payment.provider_payment_intent&&payment.provider_payment_intent!==obj.payment_intent)throw new ApiError(400,'webhook_mapping_invalid','Stripe PaymentIntent does not match the payment.');
 if(typeof obj.amount_total==='number'&&obj.amount_total!==payment.amount)throw new ApiError(400,'webhook_amount_mismatch','Stripe event amount does not match the payment.');
 if(typeof obj.currency==='string'&&obj.currency!==payment.currency)throw new ApiError(400,'webhook_currency_mismatch','Stripe event currency does not match the payment.');
 store.run('INSERT INTO stripe_webhook_events(id,livemode,received_at) VALUES(?,?,?)',event.id,mode==='live'?1:0,store.now());
 let status:Payment['status']|null=null;
 if(event.type==='checkout.session.completed'&&obj.payment_status==='paid'||event.type==='checkout.session.async_payment_succeeded')status='succeeded';
 else if(event.type==='checkout.session.expired'||event.type==='checkout.session.async_payment_failed')status='failed';
 if(status&&payment.status==='pending'){
  store.run('UPDATE payments SET status=?,provider_session_id=COALESCE(provider_session_id,?),provider_payment_intent=COALESCE(provider_payment_intent,?) WHERE id=? AND tenant_id=? AND status=\'pending\'',status,typeof obj.id==='string'?obj.id:null,typeof obj.payment_intent==='string'?obj.payment_intent:null,paymentId,tenantId);
  if(status==='succeeded')store.journal(paymentId,payment.amount,'processor_receivable',tenantId);
  store.event(`payment.${status}`,'Stripe webhook',paymentId,{stripe_event_id:event.id},tenantId);
 }
 return{received:true,duplicate:false,status:status||payment.status};
}
export function handleStripeWebhook(store:LedgerStore,rawBody:string,signature:string){
 const candidates:[mode:'test'|'live',secret:string|undefined][]=[['test',process.env.STRIPE_TEST_WEBHOOK_SECRET],['live',process.env.STRIPE_LIVE_WEBHOOK_SECRET]];
 let verified:{event:StripeEvent;mode:'test'|'live'}|undefined;
 for(const [mode,secret] of candidates){if(!secret)continue;try{verified={event:verifyStripeWebhook(rawBody,signature,secret),mode};break;}catch(error){if(!(error instanceof ApiError)||error.code!=='invalid_webhook_signature')throw error;}}
 if(!verified)throw new ApiError(400,'invalid_webhook_signature','Stripe webhook signature is invalid or expired.');
 if(typeof verified.event.livemode!=='boolean'||verified.event.livemode!==(verified.mode==='live'))throw new ApiError(400,'webhook_mode_mismatch','Stripe webhook mode does not match its signing secret.');
 return store.transaction(()=>applyStripeEvent(store,verified!.event,verified!.mode));
}
export function snapshot(store:LedgerStore,tenantId='owner',environment:PaymentProviderEnvironment=process.env):Snapshot{
 const configuredProvider=environment.AGORA_PAYMENT_PROVIDER||'sandbox';
 const providerFilter=configuredProvider==='stripe'?'stripe':configuredProvider==='sandbox'?'sandbox':'__unconfigured__';
 const configuredMode=environment.AGORA_STRIPE_MODE;
 const paymentMode=providerFilter==='stripe'?(configuredMode==='test'||configuredMode==='live'?configuredMode:'__unconfigured__'):'sandbox';
 const mode=configuredProvider==='stripe'?'stripe':'sandbox';
 const readiness=paymentProviderReadiness(environment);
 const providerMode=readiness.provider_status==='ready'?readiness.provider_mode:undefined;
 const registrationMode=configuredMode==='live'?'live':'test';
 const today=new Date();const utcToday=Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),today.getUTCDate());
 const periodEnd=new Date(utcToday+24*60*60*1000).toISOString();const periodStart=new Date(utcToday-27*24*60*60*1000).toISOString();
 const observedDays=store.all<PaymentActivityDay>("SELECT substr(created_at,1,10) AS date,COUNT(*) AS successful_payments,COALESCE(SUM(amount),0) AS gross_amount,COALESCE(SUM(refunded),0) AS refunded_amount FROM payments WHERE tenant_id=? AND provider=? AND COALESCE(provider_mode,'sandbox')=? AND status='succeeded' AND sample=0 AND created_at>=? AND created_at<? GROUP BY substr(created_at,1,10) ORDER BY date",tenantId,providerFilter,paymentMode,periodStart,periodEnd);
 const byDay=new Map(observedDays.map((day)=>[day.date,day]));
 const daily=Array.from({length:28},(_,index)=>{const date=new Date(utcToday-27*24*60*60*1000+index*24*60*60*1000).toISOString().slice(0,10);return byDay.get(date)||{date,successful_payments:0,gross_amount:0,refunded_amount:0};});
 const activity={period_start:periodStart,period_end:periodEnd,successful_payments:daily.reduce((n,row)=>n+Number(row.successful_payments),0),gross_amount:daily.reduce((n,row)=>n+Number(row.gross_amount),0),refunded_amount:daily.reduce((n,row)=>n+Number(row.refunded_amount),0),daily};
 return {mode,provider_status:readiness.provider_status,checkout_enabled:readiness.checkout_enabled,...(providerMode?{provider_mode:providerMode}:{}),activity,products:store.all<Product>('SELECT * FROM products WHERE tenant_id=? ORDER BY created_at DESC',tenantId),payments:store.all<Payment>("SELECT * FROM payments WHERE tenant_id=? AND provider=? AND COALESCE(provider_mode,'sandbox')=? ORDER BY created_at DESC LIMIT 200",tenantId,providerFilter,paymentMode),credentials:store.all<Credential&{scopes:string}>('SELECT id,name,kind,prefix,scopes,max_amount,refund_budget,spent,revoked,created_at,tenant_id,provider_mode FROM credentials WHERE tenant_id=? ORDER BY created_at DESC',tenantId).map(c=>({...c,scopes:JSON.parse(c.scopes as unknown as string)})),approvals:store.all<Approval>('SELECT * FROM approvals WHERE tenant_id=? ORDER BY created_at DESC',tenantId),events:store.all<Event&{data:string}>('SELECT * FROM events WHERE tenant_id=? ORDER BY rowid DESC LIMIT 100',tenantId).map(e=>({...e,data:JSON.parse(e.data as unknown as string)})),registrations:tenantId==='owner'?store.all<Registration>('SELECT r.id,r.business_name,r.owner_name,r.email,r.status,r.tenant_id,r.created_at,r.reviewed_at,r.review_reason,COALESCE(a.status,\'not_connected\') AS provider_status,a.account_id AS provider_account_id,a.mode AS provider_mode FROM registrations r LEFT JOIN tenant_provider_accounts a ON a.tenant_id=r.tenant_id AND a.provider=\'stripe\' AND a.mode=? ORDER BY r.created_at DESC',registrationMode):[]};
}
export function createService(store:LedgerStore,environment:PaymentProviderEnvironment=process.env){return{
 migrateMfaEncryptionKeys:()=>migrateMfaSecrets(store),
 owner,
 paymentProviderReadiness:(env:PaymentProviderEnvironment=environment)=>paymentProviderReadiness(env),
 authenticate:(request:Request)=>authenticateWith(store,request),
 hasAdminSession:(request:Request)=>hasAdminSession(store,request),
 requirePaymentMode:(actor:Actor,paymentId:string)=>requirePaymentMode(store,actor,paymentId),
 logout:(request:Request)=>{revokeAdminSession(store,request);revokeMerchantSessions(store,request);},
 beginAdminLogin:(request:Request,body:unknown)=>beginAdminLogin(store,request,body),
 enrollAdminMfa:(request:Request,body:unknown)=>enrollAdminMfa(store,request,body),
 verifyAdminMfa:(request:Request,body:unknown)=>verifyAdminMfa(store,request,body),
 authSession:(request:Request)=>{const member=merchantAuthSession(store,request);return member||authSession(store,request);},
 consoleActor:(request:Request,write=false)=>consoleActorWith(store,request,write),
 createMerchantInvite:(actor:Actor,tenantId:string)=>{requireScope(actor,'*');if(actor.tenant_id!=='owner')throw new ApiError(403,'permission_denied','Only the owner can issue merchant invitations.');return createMerchantInvite(store,tenantId);},
 acceptMerchantInvite:(request:Request,body:unknown)=>acceptMerchantInvite(store,request,body),
 merchantLogin:(request:Request,body:unknown)=>merchantLogin(store,request,body),
 enrollMerchantMfa:(request:Request,body:unknown)=>enrollMerchantMfa(store,request,body),
 verifyMerchantMfa:(request:Request,body:unknown)=>verifyMerchantMfa(store,request,body),
 setMerchantCookie,
 clearMerchantCookie,
 mutate:<T>(actor:Actor,route:string,key:string|null,body:unknown,fn:()=>T)=>mutate(store,actor,route,key,body,fn),
 createProduct:(actor:Actor,body:unknown)=>createProduct(store,actor,body),
 createPayment:(actor:Actor,body:unknown)=>createPayment(store,actor,body),
 createRefund:(actor:Actor,body:unknown)=>createRefund(store,actor,body),
 resolveApproval:(actor:Actor,body:unknown)=>resolveApproval(store,actor,body),
 createCredential:(actor:Actor,body:unknown)=>createCredential(store,actor,body),
 revokeCredential:(actor:Actor,body:unknown)=>revokeCredential(store,actor,body),
	 registerMerchant:(body:unknown)=>registerMerchant(store,body),
	 reviewRegistration:(actor:Actor,body:unknown)=>reviewRegistration(store,actor,body),
 simulate:(token:string,body:unknown)=>simulate(store,token,body),
 prepareStripePayment:(paymentId:string,mode:'test'|'live',tenantId?:string,accountId?:string|null)=>prepareStripePayment(store,paymentId,mode,tenantId,accountId),
 saveStripeSession:(paymentId:string,session:StripeCheckout,mode:'test'|'live',tenantId?:string,accountId?:string|null)=>saveStripeSession(store,paymentId,session,mode,tenantId,accountId),
 stripePaymentReconcileContext:(paymentId:string,tenantId:string)=>stripePaymentReconcileContext(store,paymentId,tenantId),
 reconcileStripePayment:(paymentId:string,tenantId:string,session:StripeCheckoutStatus)=>reconcileStripePayment(store,paymentId,tenantId,session),
 beginStripeConnect:(actor:Actor,tenantId:string,mode:'test'|'live',clientId:string,redirectUri:string)=>beginStripeConnect(store,actor,tenantId,mode,clientId,redirectUri),
 consumeStripeConnectState:(state:string,mode:'test'|'live',redirectUri:string)=>consumeStripeConnectState(store,state,mode,redirectUri),
 saveStripeConnectedAccount:(tenantId:string,mode:'test'|'live',account:Parameters<typeof saveStripeConnectedAccount>[3])=>saveStripeConnectedAccount(store,tenantId,mode,account),
 stripeAccountForTenant:(tenantId:string,mode:'test'|'live')=>stripeAccountForTenant(store,tenantId,mode),
 disconnectStripeAccount:(actor:Actor,tenantId:string,mode:'test'|'live')=>disconnectStripeAccount(store,actor,tenantId,mode),
 stripeRefundContext:(refundId:string)=>stripeRefundContext(store,refundId),
 stripeRefundResult:(refundId:string,tenantId:string)=>stripeRefundResult(store,refundId,tenantId),
 recordStripeRefundResult:(refundId:string,providerRefundId:string|null,status:'pending'|'succeeded'|'failed'|'canceled')=>recordStripeRefundResult(store,refundId,providerRefundId,status),
 handleStripeWebhook:(rawBody:string,signature:string)=>handleStripeWebhook(store,rawBody,signature),
 snapshot:(tenantId='owner')=>snapshot(store,tenantId,environment),
};}
export async function bodyOf(request:Request){const raw=await request.text();if(raw.length>16000)throw new ApiError(413,'payload_too_large','Request body must be under 16 KB.');try{return JSON.parse(raw)}catch{throw new ApiError(400,'invalid_json','Send a JSON request body.')}}
export function responseError(error:unknown,requestId:string){const e=error instanceof ApiError?error:new ApiError(500,'internal_error','An internal error occurred.');if(!(error instanceof ApiError))console.error('Agora server error',error instanceof Error?error.message:'Unknown');return Response.json({error:{code:e.code,message:e.message,request_id:requestId}},{status:e.status,headers:{'X-Request-Id':requestId,'Cache-Control':'no-store'}});}
