import { createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import type { LedgerStore } from './store';
import { ApiError } from './errors';
import { authSession, beginAdminLogin, enrollAdminMfa, isAdminSession, pendingMfaStage, setMfaCookie, verifyAdminMfa } from './admin-auth';
import type { Payment, Product, Credential, Approval, Event, Snapshot, Registration } from '../types';
export { ApiError } from './errors';
export type Actor={id:string;name:string;scopes:string[];tenant_id:string;credential?:Credential};
export const owner:Actor={id:'console_owner',name:'You',scopes:['*'],tenant_id:'owner'};
export function requireScope(actor:Actor,scope:string){if(!actor.scopes.includes('*')&&!actor.scopes.includes(scope))throw new ApiError(403,'permission_denied',`This key needs ${scope}.`)}
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
const money=z.number().int().min(1).max(10000000);
const text=z.string().trim().min(1).max(120);
export const scopes=['products:read','products:write','payments:read','payments:write','refunds:write','events:read'] as const;
function parse<T>(schema:z.ZodType<T>,body:unknown):T { const parsed=schema.safeParse(body);if(!parsed.success)throw new ApiError(422,'invalid_request',parsed.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; '));return parsed.data; }
export function authenticateWith(store:LedgerStore,request:Request):Actor{const raw=request.headers.get('authorization')?.replace(/^Bearer /,'');if(!raw)throw new ApiError(401,'unauthorized','Provide an Agora API key as a Bearer token.');const key=store.one<Credential&{hash:string;scopes:string}>('SELECT * FROM credentials WHERE hash=? AND revoked=0',hash(raw));if(!key)throw new ApiError(401,'unauthorized','This key is invalid or revoked.');const tenantId=key.tenant_id||'owner';const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',tenantId);if(!tenant||tenant.status!=='approved')throw new ApiError(403,'merchant_pending','This merchant is not approved for API access.');const credential={...key,tenant_id:tenantId,scopes:JSON.parse(key.scopes as unknown as string)} as Credential;return{id:key.id,name:key.name,scopes:credential.scopes,tenant_id:tenantId,credential};}
export const hasAdminSession=isAdminSession;
export function setSessionCookie(response:Response,request:Request,session?:{value:string;expires:number}){return setMfaCookie(response,request,'owner',session);}
export function requireSameOrigin(request:Request,required=false){const host=request.headers.get('host');const origin=request.headers.get('origin');const configured=process.env.AGORA_PUBLIC_ORIGIN;if(configured){let expected:URL;try{expected=new URL(configured)}catch{throw new ApiError(503,'auth_not_configured','AGORA_PUBLIC_ORIGIN must be a valid origin.')}if(expected.origin!==configured.replace(/\/$/,''))throw new ApiError(503,'auth_not_configured','AGORA_PUBLIC_ORIGIN must contain only scheme and host.');if(required&&!origin)throw new ApiError(403,'origin_rejected','A same-origin request is required.');if(origin&&origin!==expected.origin)throw new ApiError(403,'origin_rejected','Use the configured same-origin console.');}else if(origin){let parsed:URL;try{parsed=new URL(origin)}catch{throw new ApiError(403,'origin_rejected','Use the same-origin console.')}if(!host||parsed.host!==host)throw new ApiError(403,'origin_rejected','Use the same-origin console.');}else if(required)throw new ApiError(403,'origin_rejected','A same-origin request is required.');if(request.headers.get('sec-fetch-site')==='cross-site')throw new ApiError(403,'origin_rejected','Cross-site console requests are rejected.');}
export function consoleAuth(request:Request,write=false){requireSameOrigin(request,write);if(process.env.NODE_ENV==='production'&&!process.env.AGORA_PUBLIC_ORIGIN)throw new ApiError(503,'auth_not_configured','Set AGORA_PUBLIC_ORIGIN to the canonical browser origin.');const url=new URL(request.url);const host=request.headers.get('host')?.split(':')[0]||url.hostname;const local=host==='localhost'||host==='127.0.0.1'||host==='agora.localhost';if(process.env.NODE_ENV==='development'&&local)return owner;if(hasAdminSession(request))return owner;throw new ApiError(401,'authentication_required','Sign in with MFA to access the owner console.');}
function canonical(value:unknown):string{if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical((value as Record<string,unknown>)[k])).join(',')+'}';return JSON.stringify(value);}
export function mutate<T>(store:LedgerStore,actor:Actor,route:string,key:string|null,body:unknown,fn:()=>T):T{if(!key||key.length>200)throw new ApiError(400,'idempotency_required','Provide an Idempotency-Key of 1–200 characters.');return store.transaction(()=>{if(actor.credential){const fresh=store.one<Credential>('SELECT * FROM credentials WHERE id=? AND revoked=0',actor.id);if(!fresh)throw new ApiError(401,'unauthorized','This key has been revoked.');const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',fresh.tenant_id);if(!tenant||tenant.status!=='approved')throw new ApiError(403,'merchant_pending','This merchant is not approved for API access.');actor.credential={...fresh,scopes:actor.scopes};}const fingerprint=hash(canonical(body));const prior=store.one<{hash:string;response:string}>('SELECT * FROM idempotency WHERE actor=? AND route=? AND key=?',actor.id,route,key);if(prior){if(prior.hash!==fingerprint)throw new ApiError(409,'idempotency_conflict','This idempotency key was used with a different request.');return JSON.parse(prior.response) as T;}const value=fn();store.run('INSERT INTO idempotency(actor,route,key,hash,response) VALUES(?,?,?,?,?)',actor.id,route,key,fingerprint,JSON.stringify(value));return value;});}
export function createProduct(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'products:write');const b=parse(z.object({name:text,description:z.string().trim().max(400).default(''),amount:money,currency:z.literal('usd').default('usd')}).strict(),body);const p={id:store.id('prod'),...b,created_at:store.now()};store.run('INSERT INTO products(id,name,description,amount,currency,created_at,tenant_id) VALUES(?,?,?,?,?,?,?)',p.id,p.name,p.description,p.amount,p.currency,p.created_at,actor.tenant_id);store.event('product.created',actor.name,p.id,{amount:p.amount},actor.tenant_id);return p;}
export function createPayment(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'payments:write');const b=parse(z.object({product_id:text,customer:z.string().trim().max(120).default('Guest')}).strict(),body);const p=store.one<Product>('SELECT * FROM products WHERE id=? AND tenant_id=?',b.product_id,actor.tenant_id);if(!p)throw new ApiError(404,'not_found','Product not found.');if(actor.credential&&p.amount>actor.credential.max_amount)throw new ApiError(403,'limit_exceeded','This price exceeds the key’s per-payment limit.');const payment:Payment={id:store.id('pay'),product_id:p.id,product_name:p.name,customer:b.customer||'Guest',amount:p.amount,refunded:0,currency:'usd',status:'pending',actor:actor.name,created_at:store.now(),checkout_token:randomBytes(24).toString('hex'),sample:0,tenant_id:actor.tenant_id};store.run('INSERT INTO payments(id,product_id,product_name,customer,amount,refunded,currency,status,actor,created_at,checkout_token,sample,tenant_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',payment.id,payment.product_id,payment.product_name,payment.customer,payment.amount,0,'usd','pending',actor.name,payment.created_at,payment.checkout_token,0,actor.tenant_id);store.event('payment.created',actor.name,payment.id,{amount:p.amount},actor.tenant_id);return payment;}
function refundable(store:LedgerStore,tenantId:string,pid:string,amount:number){const p=store.one<Payment>('SELECT * FROM payments WHERE id=? AND tenant_id=?',pid,tenantId);if(!p)throw new ApiError(404,'not_found','Payment not found.');if(p.status!=='succeeded'||amount>p.amount-p.refunded)throw new ApiError(409,'not_refundable','The payment does not have enough refundable funds.');return p;}
function executeRefund(store:LedgerStore,actor:string,tenantId:string,pid:string,amount:number,reason:string){refundable(store,tenantId,pid,amount);const refund={id:store.id('ref'),payment_id:pid,amount,reason,status:'succeeded',created_at:store.now()};store.run('UPDATE payments SET refunded=refunded+? WHERE id=? AND tenant_id=?',amount,pid,tenantId);store.run('INSERT INTO refunds(id,payment_id,amount,reason,actor,created_at,tenant_id) VALUES(?,?,?,?,?,?,?)',refund.id,pid,amount,reason,actor,refund.created_at,tenantId);store.journal(refund.id,-amount,'processor_receivable',tenantId);store.event('refund.succeeded',actor,pid,{refund_id:refund.id,amount,reason},tenantId);return refund;}
export function createRefund(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'refunds:write');const b=parse(z.object({payment_id:text,amount:money,reason:z.string().trim().min(3).max(400)}).strict(),body);refundable(store,actor.tenant_id,b.payment_id,b.amount);const c=actor.credential;if(c&&b.amount>c.refund_budget-c.spent){const a={id:store.id('apr'),...b,credential_id:c.id,actor:actor.name,status:'pending',created_at:store.now(),tenant_id:actor.tenant_id};store.run('INSERT INTO approvals(id,payment_id,amount,reason,credential_id,actor,status,created_at,tenant_id) VALUES(?,?,?,?,?,?,?,?,?)',a.id,a.payment_id,a.amount,a.reason,a.credential_id,a.actor,a.status,a.created_at,a.tenant_id);store.event('approval.requested',actor.name,a.id,{payment_id:a.payment_id,amount:a.amount},actor.tenant_id);return{...a,status:'requires_approval'};}const r=executeRefund(store,actor.name,actor.tenant_id,b.payment_id,b.amount,b.reason);if(c)store.run('UPDATE credentials SET spent=spent+? WHERE id=? AND tenant_id=?',b.amount,c.id,actor.tenant_id);return r;}
export function resolveApproval(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'*');const b=parse(z.object({approval_id:text,decision:z.enum(['approve','decline'])}).strict(),body);const a=actor.tenant_id==='owner'?store.one<Approval>('SELECT * FROM approvals WHERE id=?',b.approval_id):store.one<Approval>('SELECT * FROM approvals WHERE id=? AND tenant_id=?',b.approval_id,actor.tenant_id);if(!a)throw new ApiError(404,'not_found','Approval not found.');if(a.status!=='pending')throw new ApiError(409,'already_resolved','This request has already been reviewed.');if(b.decision==='approve'){if(!store.one('SELECT id FROM credentials WHERE id=? AND revoked=0',a.credential_id))throw new ApiError(409,'key_revoked','The requesting key has been revoked. Decline this request.');executeRefund(store,`${actor.name} approved ${a.actor}`,a.tenant_id||'owner',a.payment_id,a.amount,a.reason);}const status=b.decision==='approve'?'approved':'declined';store.run('UPDATE approvals SET status=? WHERE id=?',status,a.id);store.event(`approval.${status}`,actor.name,a.id,{amount:a.amount},a.tenant_id||'owner');return{...a,status};}
export function createCredential(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'*');const b=parse(z.object({name:text,kind:z.enum(['agent','developer']),scopes:z.array(z.enum(scopes)).min(1),max_amount:money,refund_budget:z.number().int().min(0).max(10000000),tenant_id:text.optional()}).strict(),body);const tenantId=b.tenant_id||actor.tenant_id;const tenant=store.one<{status:string}>('SELECT status FROM tenants WHERE id=?',tenantId);if(!tenant||tenant.status!=='approved')throw new ApiError(409,'merchant_pending','Approve the merchant before issuing an API key.');const secret='ag_test_'+randomBytes(24).toString('hex');const c={id:store.id('key'),...b,tenant_id:tenantId,prefix:secret.slice(0,16),spent:0,revoked:0,created_at:store.now()};store.run('INSERT INTO credentials(id,name,kind,prefix,hash,scopes,max_amount,refund_budget,spent,revoked,created_at,tenant_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',c.id,c.name,c.kind,c.prefix,hash(secret),JSON.stringify(c.scopes),c.max_amount,c.refund_budget,0,0,c.created_at,c.tenant_id);store.event('key.created',actor.name,c.id,{name:c.name,scopes:c.scopes,tenant_id:c.tenant_id},c.tenant_id);return{...c,secret};}
export function revokeCredential(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'*');const b=parse(z.object({key_id:text}).strict(),body);const credential=store.one<Credential>('SELECT id,tenant_id FROM credentials WHERE id=?',b.key_id);if(!credential)throw new ApiError(404,'not_found','Key not found.');if(actor.tenant_id!=='owner'&&credential.tenant_id!==actor.tenant_id)throw new ApiError(404,'not_found','Key not found.');store.run('UPDATE credentials SET revoked=1 WHERE id=?',b.key_id);store.event('key.revoked',actor.name,b.key_id,{tenant_id:credential.tenant_id},credential.tenant_id);return{id:b.key_id,revoked:true};}
export function registerMerchant(store:LedgerStore,body:unknown){const b=parse(z.object({business_name:text,owner_name:text,email:z.string().trim().email().max(254)}).strict(),body);const since=new Date(Date.now()-24*60*60*1000).toISOString();if(store.one('SELECT id FROM registrations WHERE lower(email)=lower(?) AND created_at>=?',b.email,since))throw new ApiError(409,'registration_exists','A recent registration already exists for this email.');const registrationId=store.id('reg');const tenantId=store.id('tn');const createdAt=store.now();store.transaction(()=>{store.run("INSERT INTO tenants(id,business_name,email,status,provider,provider_account_id,created_at,approved_at) VALUES(?,?,?,'pending','stripe',NULL,?,NULL)",tenantId,b.business_name,b.email,createdAt);store.run("INSERT INTO registrations(id,business_name,owner_name,email,provider,provider_account_id,status,tenant_id,created_at,reviewed_at,review_reason) VALUES(?,?,?,?,'stripe',NULL,'pending',?,?,NULL,NULL)",registrationId,b.business_name,b.owner_name,b.email,tenantId,createdAt);store.event('registration.created','Public registration',registrationId,{business_name:b.business_name,email:b.email},tenantId);});return{registration_id:registrationId,status:'pending' as const,provider_status:'not_connected' as const};}
export function reviewRegistration(store:LedgerStore,actor:Actor,body:unknown){requireScope(actor,'*');const b=parse(z.object({registration_id:text,decision:z.enum(['approve','reject']),reason:z.string().trim().max(400).optional()}).strict(),body);const registration=store.one<Registration>('SELECT * FROM registrations WHERE id=?',b.registration_id);if(!registration)throw new ApiError(404,'not_found','Registration not found.');if(registration.status!=='pending')throw new ApiError(409,'already_reviewed','This registration has already been reviewed.');const status=b.decision==='approve'?'approved':'rejected';store.transaction(()=>{store.run('UPDATE registrations SET status=?,reviewed_at=?,review_reason=? WHERE id=? AND status=\'pending\'',status,store.now(),b.reason||null,b.registration_id);store.run('UPDATE tenants SET status=?,approved_at=? WHERE id=?',status==='approved'?'approved':'rejected',status==='approved'?store.now():null,registration.tenant_id);store.event(`registration.${status}`,actor.name,registration.id,{tenant_id:registration.tenant_id,reason:b.reason||null},'owner');});return{...registration,status,reviewed_at:store.now(),review_reason:b.reason||null,provider_status:'not_connected' as const};}
export function simulate(store:LedgerStore,token:string,body:unknown){const b=parse(z.object({outcome:z.enum(['succeeded','failed'])}).strict(),body);return store.transaction(()=>{const p=store.one<Payment>('SELECT * FROM payments WHERE checkout_token=? AND sample=0',token);if(!p)throw new ApiError(404,'not_found','Checkout not found.');if(p.status!=='pending'){if(p.status===b.outcome)return{status:p.status,id:p.id};throw new ApiError(409,'already_completed','This checkout has already completed.');}store.run('UPDATE payments SET status=? WHERE id=?',b.outcome,p.id);if(b.outcome==='succeeded')store.journal(p.id,p.amount,'processor_receivable',p.tenant_id||'owner');store.event(`payment.${b.outcome}`,'Sandbox checkout',p.id,{amount:p.amount},p.tenant_id||'owner');return{status:b.outcome,id:p.id};});}
export function snapshot(store:LedgerStore):Snapshot{return {mode:'sandbox',products:store.all<Product>('SELECT * FROM products ORDER BY created_at DESC'),payments:store.all<Payment>('SELECT * FROM payments ORDER BY created_at DESC LIMIT 200'),credentials:store.all<Credential&{scopes:string}>('SELECT id,name,kind,prefix,scopes,max_amount,refund_budget,spent,revoked,created_at,tenant_id FROM credentials ORDER BY created_at DESC').map(c=>({...c,scopes:JSON.parse(c.scopes as unknown as string)})),approvals:store.all<Approval>('SELECT * FROM approvals ORDER BY created_at DESC'),events:store.all<Event&{data:string}>('SELECT * FROM events ORDER BY rowid DESC LIMIT 100').map(e=>({...e,data:JSON.parse(e.data as unknown as string)})),registrations:store.all<Registration>('SELECT id,business_name,owner_name,email,status,tenant_id,created_at,reviewed_at,review_reason FROM registrations ORDER BY created_at DESC').map(r=>({...r,provider_status:'not_connected'}))};}
export function createService(store:LedgerStore){return{
 owner,
 authenticate:(request:Request)=>authenticateWith(store,request),
 beginAdminLogin:(request:Request,body:unknown)=>beginAdminLogin(store,request,body),
 enrollAdminMfa:(request:Request,body:unknown)=>enrollAdminMfa(store,request,body),
 verifyAdminMfa:(request:Request,body:unknown)=>verifyAdminMfa(store,request,body),
 authSession:(request:Request)=>authSession(request),
 mutate:<T>(actor:Actor,route:string,key:string|null,body:unknown,fn:()=>T)=>mutate(store,actor,route,key,body,fn),
 createProduct:(actor:Actor,body:unknown)=>createProduct(store,actor,body),
 createPayment:(actor:Actor,body:unknown)=>createPayment(store,actor,body),
 createRefund:(actor:Actor,body:unknown)=>createRefund(store,actor,body),
 resolveApproval:(actor:Actor,body:unknown)=>resolveApproval(store,actor,body),
 createCredential:(actor:Actor,body:unknown)=>createCredential(store,actor,body),
 revokeCredential:(actor:Actor,body:unknown)=>revokeCredential(store,actor,body),
	 registerMerchant:(body:unknown)=>registerMerchant(store,body),
	 reviewRegistration:(actor:Actor,body:unknown)=>reviewRegistration(store,actor,body),
 simulate:(token:string,body:unknown)=>simulate(store,token,body),
 snapshot:()=>snapshot(store),
};}
export async function bodyOf(request:Request){const raw=await request.text();if(raw.length>16000)throw new ApiError(413,'payload_too_large','Request body must be under 16 KB.');try{return JSON.parse(raw)}catch{throw new ApiError(400,'invalid_json','Send a JSON request body.')}}
export function responseError(error:unknown,requestId:string){const e=error instanceof ApiError?error:new ApiError(500,'internal_error','An internal error occurred.');if(!(error instanceof ApiError))console.error('Agora server error',error instanceof Error?error.message:'Unknown');return Response.json({error:{code:e.code,message:e.message,request_id:requestId}},{status:e.status,headers:{'X-Request-Id':requestId,'Cache-Control':'no-store'}});}
