import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHmac} from 'node:crypto';
import {createServer} from 'node:http';
const dir=mkdtempSync(join(tmpdir(),'agora-outbox-'));
const env=process.env as Record<string,string|undefined>;env.AGORA_DATABASE_PATH=join(dir,'outbox.sqlite');env.AGORA_SEED='false';env.AGORA_DEPLOYMENT_ENV='qa';env.AGORA_SECRETS_ENCRYPTION_KEY=Buffer.alloc(32,77).toString('base64');env.AGORA_ALLOW_LOCAL_WEBHOOKS='true';env.NODE_ENV='test';
const local=await import('../lib/server/local');const db=await import('../lib/server/db');const outbox=await import('../lib/server/outgoing-webhooks');
const owner=local.owner;const testEndpoint=local.createWebhookEndpoint(owner,{url:'http://127.0.0.1:8787/hook',mode:'test',event_types:['payment.succeeded']});const liveEndpoint=local.createWebhookEndpoint(owner,{url:'http://127.0.0.1:8788/hook',mode:'live',event_types:['payment.succeeded']});
const paymentId='pay_outbox_test';db.run("INSERT INTO products(id,name,description,amount,currency,created_at,tenant_id) VALUES('prod_outbox','Item','',100,'usd',?,'owner')",db.now());db.run("INSERT INTO payments(id,product_id,product_name,customer,amount,refunded,currency,status,actor,created_at,checkout_token,sample,tenant_id,provider,provider_mode) VALUES(?,?,?,'Guest',100,0,'usd','succeeded','You',?,'token',0,'owner','stripe','test')",paymentId,'prod_outbox','Item',db.now());
const eventId=db.event('payment.succeeded','Stripe webhook',paymentId,{amount:100},'owner');
await test('durable outbox signs exact body, retries with stable event and delivery ids, and isolates modes',async()=>{
 const deliveries=db.all<{id:string;endpoint_id:string;status:string;payload:string}>('SELECT id,endpoint_id,status,payload FROM webhook_deliveries ORDER BY endpoint_id');assert.equal(deliveries.length,2);
 let firstBody='';let firstHeaders:Headers|undefined;let calls=0;
 const fetcher:typeof fetch=async(_input,init)=>{calls++;assert.equal(init?.redirect,'manual');firstBody=String(init?.body);firstHeaders=new Headers(init?.headers);return new Response('',{status:calls===1?500:204});};
 const processed=await outbox.dispatchWebhookBatch(db.localStore,{AGORA_SECRETS_ENCRYPTION_KEY:process.env.AGORA_SECRETS_ENCRYPTION_KEY,AGORA_ALLOW_LOCAL_WEBHOOKS:'true'},fetcher,10);assert.equal(processed.processed,2);assert.equal(calls,1,'live endpoint must not receive test-mode payment event');
 const testDelivery=deliveries.find(row=>row.endpoint_id===testEndpoint.endpoint.id)!;const liveDelivery=deliveries.find(row=>row.endpoint_id===liveEndpoint.endpoint.id)!;assert.equal(db.one<{status:string}>('SELECT status FROM webhook_deliveries WHERE id=?',liveDelivery.id)?.status,'skipped_mode');
 assert.equal(firstHeaders?.get('Agora-Event-Id'),eventId);assert.equal(firstHeaders?.get('Agora-Delivery-Id'),testDelivery.id);const timestamp=firstHeaders?.get('Agora-Timestamp')||'';const signature=firstHeaders?.get('Agora-Signature')||'';assert.equal(outbox.verifyOutgoingWebhook(testEndpoint.signing_secret,timestamp,firstBody,signature),true);assert.equal(JSON.parse(firstBody).id,eventId);
 const raw=db.one<{secret_ciphertext:string}>('SELECT secret_ciphertext FROM webhook_endpoints WHERE id=?',testEndpoint.endpoint.id)!.secret_ciphertext;assert.equal(raw.includes(testEndpoint.signing_secret),false);
 db.run("UPDATE webhook_deliveries SET next_attempt_at=? WHERE id=?",new Date(Date.now()-1000).toISOString(),testDelivery.id);let retryBody='';let retryHeaders:Headers|undefined;const ok:typeof fetch=async(_input,init)=>{retryBody=String(init?.body);retryHeaders=new Headers(init?.headers);return new Response(null,{status:204});};await outbox.dispatchWebhookBatch(db.localStore,{AGORA_SECRETS_ENCRYPTION_KEY:process.env.AGORA_SECRETS_ENCRYPTION_KEY},ok,10);assert.equal(retryBody,firstBody);assert.equal(retryHeaders?.get('Agora-Event-Id'),eventId);assert.equal(retryHeaders?.get('Agora-Delivery-Id'),testDelivery.id);assert.equal(db.one<{status:string;attempt_count:number}>('SELECT status,attempt_count FROM webhook_deliveries WHERE id=?',testDelivery.id)?.status,'delivered');assert.equal(db.one<{attempt_count:number}>('SELECT attempt_count FROM webhook_deliveries WHERE id=?',testDelivery.id)?.attempt_count,2);
 const attemptCount=db.one<{n:number}>('SELECT COUNT(*) AS n FROM webhook_attempts WHERE delivery_id=?',testDelivery.id)?.n;assert.equal(attemptCount,2);assert.equal(db.one<{response_excerpt:string}>('SELECT response_excerpt FROM webhook_attempts WHERE delivery_id=? ORDER BY attempt DESC LIMIT 1',testDelivery.id)?.response_excerpt,'');
});
await test('endpoint rejects non-HTTPS public targets and supports pause/archive without deleting history',()=>{assert.throws(()=>local.createWebhookEndpoint(owner,{url:'http://example.com/x',mode:'test',event_types:['payment.created']}));const id=testEndpoint.endpoint.id;local.updateWebhookEndpoint(owner,id,{status:'paused'});assert.equal(db.one<{status:string}>('SELECT status FROM webhook_endpoints WHERE id=?',id)?.status,'paused');local.archiveWebhookEndpoint(owner,liveEndpoint.endpoint.id);assert.equal(db.one<{status:string}>('SELECT status FROM webhook_endpoints WHERE id=?',liveEndpoint.endpoint.id)?.status,'archived');assert.equal(db.one<{n:number}>('SELECT COUNT(*) AS n FROM webhook_deliveries WHERE endpoint_id=?',liveEndpoint.endpoint.id)?.n,1);});
await test('real local HTTP receiver gets signed bytes; retry preserves body and recovery closes abandoned attempt',async()=>{
 let count=0;const received:{body:string;event:string|null;delivery:string|null;signature:string|null;timestamp:string|null}[]=[];const header=(value:string|string[]|undefined)=>Array.isArray(value)?value[0]||null:value||null;const server=createServer((req,res)=>{let body='';req.setEncoding('utf8');req.on('data',chunk=>body+=chunk);req.on('end',()=>{received.push({body,event:header(req.headers['agora-event-id']),delivery:header(req.headers['agora-delivery-id']),signature:header(req.headers['agora-signature']),timestamp:header(req.headers['agora-timestamp'])});count++;res.statusCode=count===1?503:204;res.end();});});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();assert.ok(address&&typeof address!=='string');const endpoint=local.createWebhookEndpoint(owner,{url:`http://127.0.0.1:${address.port}/hook`,mode:'test',event_types:['payment.succeeded']});const retryEventId=db.event('payment.succeeded','Stripe webhook',paymentId,{amount:100},'owner');db.run("UPDATE webhook_deliveries SET status='delivering',attempt_count=0,locked_until=?,lease_token='expired' WHERE endpoint_id=?",new Date(Date.now()-1000).toISOString(),endpoint.endpoint.id);db.run("INSERT INTO webhook_attempts(id,delivery_id,attempt,started_at) SELECT 'abandoned',id,0,? FROM webhook_deliveries WHERE endpoint_id=?",db.now(),endpoint.endpoint.id);try{await outbox.dispatchWebhookBatch(db.localStore,env,fetch,10);let row=db.one<{id:string;status:string;next_attempt_at:string}>('SELECT id,status,next_attempt_at FROM webhook_deliveries WHERE endpoint_id=?',endpoint.endpoint.id)!;assert.equal(row.status,'pending');db.run('UPDATE webhook_deliveries SET next_attempt_at=? WHERE id=?',new Date(Date.now()-1000).toISOString(),row.id);await outbox.dispatchWebhookBatch(db.localStore,env,fetch,10);row=db.one<{id:string;status:string;next_attempt_at:string}>('SELECT id,status,next_attempt_at FROM webhook_deliveries WHERE endpoint_id=?',endpoint.endpoint.id)!;assert.equal(row.status,'delivered');assert.equal(received.length,2);assert.equal(received[0].body,received[1].body);assert.equal(received[0].event,received[1].event);assert.equal(received[0].delivery,received[1].delivery);assert.equal(received[0].event,retryEventId);assert.equal(outbox.verifyOutgoingWebhook(endpoint.signing_secret,received[0].timestamp||'',received[0].body,received[0].signature||''),true);const attempts=db.all<{error:string|null;http_status:number|null}>('SELECT error,http_status FROM webhook_attempts WHERE delivery_id=? ORDER BY attempt',row.id);assert.equal(attempts[0].error,'worker_interrupted');assert.equal(attempts[1].error,'http_503');assert.equal(attempts[2].http_status,204);}finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}
});
await test('HMAC verifier rejects stale timestamps and altered bytes',()=>{const timestamp='1';const body='{}';const signature=`v1=${createHmac('sha256',testEndpoint.signing_secret).update(`${timestamp}.${body}`).digest('hex')}`;assert.equal(outbox.verifyOutgoingWebhook(testEndpoint.signing_secret,timestamp,body,signature),false);assert.equal(outbox.verifyOutgoingWebhook(testEndpoint.signing_secret,String(Math.floor(Date.now()/1000)),body,signature),false);});
rmSync(dir,{recursive:true,force:true});
