import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash, createHmac } from 'node:crypto';
const dir=mkdtempSync(join(tmpdir(),'agora-test-'));process.env.AGORA_DATABASE_PATH=join(dir,'test.sqlite');process.env.AGORA_SEED='false';process.env.AGORA_DEPLOYMENT_ENV='qa';
const s=await import('../lib/server/local');const d=await import('../lib/server/db');const cfg=await import('../lib/server/stripe-config');
const write=<T>(route:string,key:string,body:unknown,fn:()=>T,actor=s.owner)=>s.mutate(actor,route,key,body,fn);
const product=write('product','p1',{},()=>s.createProduct(s.owner,{name:'Test',amount:5000}));
const payment=write('payment','pay1',{},()=>s.createPayment(s.owner,{product_id:product.id}));
function key(name:string,budget:number,permissions:string[]=s.scopes as unknown as string[]){const c=write('key',name,{},()=>s.createCredential(s.owner,{name,kind:'agent',scopes:permissions,max_amount:10000,refund_budget:budget}));return{...c,actor:s.authenticate(new Request('http://localhost',{headers:{Authorization:`Bearer ${c.secret}`}}))}}
await test('same idempotency key creates only one payment; changed payload conflicts',()=>{const replay=write('payment','pay1',{},()=>s.createPayment(s.owner,{product_id:product.id}));assert.equal(replay.id,payment.id);assert.equal(d.all('SELECT * FROM payments').length,1);assert.throws(()=>write('payment','pay1',{changed:true},()=>null),(e:unknown)=>e instanceof s.ApiError&&e.status===409)});
await test('checkout success replay journals once, conflicting outcome is rejected',()=>{s.simulate(payment.checkout_token,{outcome:'succeeded'});s.simulate(payment.checkout_token,{outcome:'succeeded'});assert.equal(d.all('SELECT * FROM journal').length,2);assert.throws(()=>s.simulate(payment.checkout_token,{outcome:'failed'}));assert.equal(d.one<{sum:number}>('SELECT SUM(amount) AS sum FROM journal')?.sum,0)});
await test('limited agent needs human approval; replay does not duplicate request',()=>{const k=key('Limited',0);const b={payment_id:payment.id,amount:1000,reason:'Customer request'};const a=write('refund','r1',b,()=>s.createRefund(k.actor,b),k.actor);const again=write('refund','r1',b,()=>s.createRefund(k.actor,b),k.actor);assert.equal(a.id,again.id);assert.equal(a.status,'requires_approval');assert.equal(d.one<{refunded:number}>('SELECT refunded FROM payments WHERE id=?',payment.id)?.refunded,0);write('approve','a1',{},()=>s.resolveApproval(s.owner,{approval_id:a.id,decision:'approve'}));assert.equal(d.one<{refunded:number}>('SELECT refunded FROM payments WHERE id=?',payment.id)?.refunded,1000);assert.throws(()=>write('approve','a2',{},()=>s.resolveApproval(s.owner,{approval_id:a.id,decision:'approve'})));});
await test('cumulative allowance cannot be exceeded by splitting refunds',()=>{const k=key('Budget',1000);const b={payment_id:payment.id,amount:600,reason:'Partial return'};assert.equal(write('refund','b1',b,()=>s.createRefund(k.actor,b),k.actor).status,'succeeded');assert.equal(write('refund','b2',b,()=>s.createRefund(k.actor,b),k.actor).status,'requires_approval');assert.equal(d.one<{spent:number}>('SELECT spent FROM credentials WHERE id=?',k.id)?.spent,600)});
await test('read-only keys and amount limits are enforced',()=>{const k=key('Reader',0,['payments:read']);assert.throws(()=>write('refund','x1',{},()=>s.createRefund(k.actor,{payment_id:payment.id,amount:1,reason:'Test'}),k.actor),(e:unknown)=>e instanceof s.ApiError&&e.status===403);const expensive=write('product','p2',{},()=>s.createProduct(s.owner,{name:'Expensive',amount:20000}));const full=key('Small limit',0);assert.throws(()=>write('payment','high',{},()=>s.createPayment(full.actor,{product_id:expensive.id}),full.actor));});
await test('API keys are pinned to their creation mode and cannot cross test/live',()=>{const env=process.env as Record<string,string|undefined>;const before={provider:env.AGORA_PAYMENT_PROVIDER,mode:env.AGORA_STRIPE_MODE,webhook:env.STRIPE_TEST_WEBHOOK_SECRET,key:env.STRIPE_TEST_SECRET_KEY,origin:env.AGORA_PUBLIC_ORIGIN};env.AGORA_PAYMENT_PROVIDER='stripe';env.AGORA_STRIPE_MODE='test';env.STRIPE_TEST_WEBHOOK_SECRET='whsec_mode_key_test';env.STRIPE_TEST_SECRET_KEY='sk_test_localfixture123';env.AGORA_PUBLIC_ORIGIN='https://agora.example';cfg.markWebhookVerified(d.localStore,'test',env.STRIPE_TEST_WEBHOOK_SECRET);try{const created=write('mode-key','mode-key-1',{},()=>s.createCredential(s.owner,{name:'Mode test key',kind:'developer',scopes:['payments:write','refunds:write'],max_amount:10000,refund_budget:1000}));assert.equal(created.provider_mode,'test');assert.match(created.secret,/^ag_test_/);const actor=s.authenticate(new Request('https://api.example',{headers:{Authorization:`Bearer ${created.secret}`}}));s.requireProviderMode(actor,'test');assert.throws(()=>s.requireProviderMode(actor,'live'),(e:unknown)=>e instanceof s.ApiError&&e.code==='key_mode_mismatch');assert.throws(()=>s.createRefund(actor,{payment_id:payment.id,amount:100,reason:'Wrong mode'}),(e:unknown)=>e instanceof s.ApiError&&e.code==='key_mode_mismatch');}finally{if(before.provider===undefined)delete env.AGORA_PAYMENT_PROVIDER;else env.AGORA_PAYMENT_PROVIDER=before.provider;if(before.mode===undefined)delete env.AGORA_STRIPE_MODE;else env.AGORA_STRIPE_MODE=before.mode;if(before.webhook===undefined)delete env.STRIPE_TEST_WEBHOOK_SECRET;else env.STRIPE_TEST_WEBHOOK_SECRET=before.webhook;if(before.key===undefined)delete env.STRIPE_TEST_SECRET_KEY;else env.STRIPE_TEST_SECRET_KEY=before.key;if(before.origin===undefined)delete env.AGORA_PUBLIC_ORIGIN;else env.AGORA_PUBLIC_ORIGIN=before.origin;}});
await test('provider readiness accepts an explicit deployment environment without mutating process env',()=>{
 const env={AGORA_DEPLOYMENT_ENV:'production',AGORA_PAYMENT_PROVIDER:'stripe',AGORA_STRIPE_MODE:'live',STRIPE_LIVE_SECRET_KEY:'rk_live_fixture',STRIPE_LIVE_WEBHOOK_SECRET:'whsec_fixture',AGORA_PUBLIC_ORIGIN:'https://agora.example'};
 assert.deepEqual(s.paymentProviderReadiness(env),{provider_status:'setup_required',checkout_enabled:false});cfg.markWebhookVerified(d.localStore,'live',env.STRIPE_LIVE_WEBHOOK_SECRET);
 assert.deepEqual(s.paymentProviderReadiness(env),{provider_status:'ready',checkout_enabled:true,provider_mode:'live'});
 assert.deepEqual(s.paymentProviderReadiness({...env,STRIPE_LIVE_SECRET_KEY:'rk_test_wrong_mode'}),{provider_status:'setup_required',checkout_enabled:false});
 assert.deepEqual(s.paymentProviderReadiness({AGORA_DEPLOYMENT_ENV:'production',AGORA_PAYMENT_PROVIDER:'sandbox'}),{provider_status:'setup_required',checkout_enabled:false});
});
await test('snapshot activity aggregates every in-window payment while enforcing tenant and mode scope',()=>{
 const env=process.env as Record<string,string|undefined>;const before={provider:env.AGORA_PAYMENT_PROVIDER,mode:env.AGORA_STRIPE_MODE,deployment:env.AGORA_DEPLOYMENT_ENV};env.AGORA_PAYMENT_PROVIDER='stripe';env.AGORA_STRIPE_MODE='test';env.AGORA_DEPLOYMENT_ENV='qa';
 try{
  const rows=Array.from({length:205},(_,i)=>s.createPayment(s.owner,{product_id:product.id}));for(const row of rows)d.run("UPDATE payments SET status='succeeded',provider='stripe',provider_mode='test' WHERE id=?",row.id);
  const now=new Date(),endMs=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())+24*60*60*1000,startMs=endMs-28*24*60*60*1000;const start=new Date(startMs).toISOString(),end=new Date(endMs).toISOString();
  d.run('UPDATE payments SET created_at=? WHERE id=?',new Date(startMs-1).toISOString(),rows[0].id);
  d.run('UPDATE payments SET created_at=?,refunded=1000 WHERE id=?',start,rows[1].id);
  d.run('UPDATE payments SET created_at=?,refunded=500 WHERE id=?',new Date(endMs-1).toISOString(),rows[2].id);
  d.run('UPDATE payments SET created_at=? WHERE id=?',end,rows[3].id);
  const live=s.createPayment(s.owner,{product_id:product.id});d.run("UPDATE payments SET status='succeeded',provider='stripe',provider_mode='live' WHERE id=?",live.id);
  const sandbox=s.createPayment(s.owner,{product_id:product.id});d.run("UPDATE payments SET status='succeeded',provider='sandbox',provider_mode='sandbox' WHERE id=?",sandbox.id);
  const merchantReg=s.registerMerchant({business_name:'Activity Merchant',owner_name:'Member',email:'activity@example.test'});const tenant=d.one<{tenant_id:string}>('SELECT tenant_id FROM registrations WHERE id=?',merchantReg.registration_id)!.tenant_id;s.reviewRegistration(s.owner,{registration_id:merchantReg.registration_id,decision:'approve'});const merchantProduct=s.createProduct({...s.owner,tenant_id:tenant},{name:'Merchant activity item',amount:700});const merchantPayment=s.createPayment({...s.owner,tenant_id:tenant},{product_id:merchantProduct.id});d.run("UPDATE payments SET status='succeeded',provider='stripe',provider_mode='test' WHERE id=?",merchantPayment.id);
  const ownerSnapshot=s.snapshot('owner');assert.equal(ownerSnapshot.payments.length,200);assert.ok(ownerSnapshot.payments.every((row)=>row.tenant_id==='owner'&&row.provider==='stripe'&&row.provider_mode==='test'));assert.equal(ownerSnapshot.activity.period_start,start);assert.equal(ownerSnapshot.activity.period_end,end);assert.equal(ownerSnapshot.activity.successful_payments,203);assert.equal(ownerSnapshot.activity.gross_amount,203*product.amount);assert.equal(ownerSnapshot.activity.refunded_amount,1500);assert.equal(ownerSnapshot.activity.daily.length,28);assert.deepEqual(ownerSnapshot.activity.daily.map((day)=>day.date),Array.from({length:28},(_,index)=>new Date(startMs+index*24*60*60*1000).toISOString().slice(0,10)));assert.equal(ownerSnapshot.activity.daily.find((day)=>day.date===start.slice(0,10))?.successful_payments,1);assert.ok(ownerSnapshot.activity.daily.some((day)=>day.successful_payments===0));
  const merchantSnapshot=s.snapshot(tenant);assert.equal(merchantSnapshot.activity.successful_payments,1);assert.equal(merchantSnapshot.activity.gross_amount,700);assert.equal(merchantSnapshot.payments.length,1);assert.equal(merchantSnapshot.payments[0].tenant_id,tenant);assert.equal(merchantSnapshot.activity.daily.find((day)=>day.date===start.slice(0,10))?.successful_payments,0);
 }finally{if(before.provider===undefined)delete env.AGORA_PAYMENT_PROVIDER;else env.AGORA_PAYMENT_PROVIDER=before.provider;if(before.mode===undefined)delete env.AGORA_STRIPE_MODE;else env.AGORA_STRIPE_MODE=before.mode;if(before.deployment===undefined)delete env.AGORA_DEPLOYMENT_ENV;else env.AGORA_DEPLOYMENT_ENV=before.deployment;}
});
await test('production sandbox setup fails closed for keys, payments, and refunds',()=>{
 const env=process.env as Record<string,string|undefined>;const prior={deployment:env.AGORA_DEPLOYMENT_ENV,node:env.NODE_ENV,provider:env.AGORA_PAYMENT_PROVIDER};env.AGORA_DEPLOYMENT_ENV='production';env.NODE_ENV='production';env.AGORA_PAYMENT_PROVIDER='sandbox';
 try{assert.deepEqual(s.paymentProviderReadiness(),{provider_status:'setup_required',checkout_enabled:false});assert.throws(()=>s.createCredential(s.owner,{name:'No production sandbox key',kind:'developer',scopes:['payments:write'],max_amount:1000,refund_budget:0}),(e:unknown)=>e instanceof s.ApiError&&e.code==='provider_not_configured');assert.throws(()=>s.simulate(payment.checkout_token,{outcome:'succeeded'}),(e:unknown)=>e instanceof s.ApiError&&e.code==='provider_not_configured');assert.throws(()=>s.createRefund(s.owner,{payment_id:payment.id,amount:100,reason:'No fake production refund'}),(e:unknown)=>e instanceof s.ApiError&&e.code==='provider_not_configured');assert.equal(s.snapshot('owner').provider_status,'setup_required');assert.equal(s.snapshot('owner').checkout_enabled,false);assert.equal(s.snapshot('owner').provider_mode,undefined);}
 finally{if(prior.deployment===undefined)delete env.AGORA_DEPLOYMENT_ENV;else env.AGORA_DEPLOYMENT_ENV=prior.deployment;if(prior.node===undefined)delete env.NODE_ENV;else env.NODE_ENV=prior.node;if(prior.provider===undefined)delete env.AGORA_PAYMENT_PROVIDER;else env.AGORA_PAYMENT_PROVIDER=prior.provider;}
});
await test('Stripe restricted keys are mode-pinned for provider use and Agora credentials',()=>{
 const env=process.env as Record<string,string|undefined>;const before={provider:env.AGORA_PAYMENT_PROVIDER,mode:env.AGORA_STRIPE_MODE,key:env.STRIPE_LIVE_SECRET_KEY,webhook:env.STRIPE_LIVE_WEBHOOK_SECRET,origin:env.AGORA_PUBLIC_ORIGIN,deployment:env.AGORA_DEPLOYMENT_ENV};env.AGORA_DEPLOYMENT_ENV='qa';env.AGORA_PAYMENT_PROVIDER='stripe';env.AGORA_STRIPE_MODE='live';env.STRIPE_LIVE_SECRET_KEY='rk_live_restrictedfixture';env.STRIPE_LIVE_WEBHOOK_SECRET='whsec_live_fixture';env.AGORA_PUBLIC_ORIGIN='https://agora.example';cfg.markWebhookVerified(d.localStore,'live',env.STRIPE_LIVE_WEBHOOK_SECRET);
 try{assert.deepEqual(s.paymentProviderReadiness(),{provider_status:'ready',checkout_enabled:true,provider_mode:'live'});const issued=s.createCredential(s.owner,{name:'Live mode credential fixture',kind:'developer',scopes:['payments:write'],max_amount:10000,refund_budget:0});assert.equal(issued.provider_mode,'live');assert.match(issued.secret,/^ag_live_/);const actor=s.authenticate(new Request('https://api.example',{headers:{Authorization:`Bearer ${issued.secret}`}}));assert.throws(()=>s.requireProviderMode(actor,'test'),(e:unknown)=>e instanceof s.ApiError&&e.code==='key_mode_mismatch');}
 finally{if(before.provider===undefined)delete env.AGORA_PAYMENT_PROVIDER;else env.AGORA_PAYMENT_PROVIDER=before.provider;if(before.mode===undefined)delete env.AGORA_STRIPE_MODE;else env.AGORA_STRIPE_MODE=before.mode;if(before.key===undefined)delete env.STRIPE_LIVE_SECRET_KEY;else env.STRIPE_LIVE_SECRET_KEY=before.key;if(before.webhook===undefined)delete env.STRIPE_LIVE_WEBHOOK_SECRET;else env.STRIPE_LIVE_WEBHOOK_SECRET=before.webhook;if(before.origin===undefined)delete env.AGORA_PUBLIC_ORIGIN;else env.AGORA_PUBLIC_ORIGIN=before.origin;if(before.deployment===undefined)delete env.AGORA_DEPLOYMENT_ENV;else env.AGORA_DEPLOYMENT_ENV=before.deployment;}
});
await test('revocation invalidates keys and prevents pending approval execution',()=>{const k=key('Revoke me',0);const b={payment_id:payment.id,amount:100,reason:'Return'};const a=write('refund','rev1',b,()=>s.createRefund(k.actor,b),k.actor);write('revoke','rev',{},()=>s.revokeCredential(s.owner,{key_id:k.id}));assert.throws(()=>s.authenticate(new Request('http://localhost',{headers:{Authorization:`Bearer ${k.secret}`}})));assert.throws(()=>write('approve','revapprove',{},()=>s.resolveApproval(s.owner,{approval_id:a.id,decision:'approve'})));assert.throws(()=>write('refund','rev1',b,()=>s.createRefund(k.actor,b),k.actor));});
await test('over-refunds roll back without additional journal or event effects',()=>{const before=d.all('SELECT * FROM events').length;assert.throws(()=>write('refund','too-much',{},()=>s.createRefund(s.owner,{payment_id:payment.id,amount:5000,reason:'Over refund'})));assert.equal(d.all('SELECT * FROM events').length,before);assert.equal(d.one<{sum:number}>('SELECT SUM(amount) AS sum FROM journal')?.sum,0);assert.equal(d.all('SELECT * FROM idempotency WHERE key=?','too-much').length,0)});
await test('raw card-like fields and decimal amounts are rejected',()=>{assert.throws(()=>write('product','bad',{},()=>s.createProduct(s.owner,{name:'Bad',amount:1.5})));assert.throws(()=>write('payment','pan',{},()=>s.createPayment(s.owner,{product_id:product.id,card_number:'test'})));});
await test('pending merchant registration is blocked, then receives a tenant-isolated key after owner review',()=>{
 const registration=s.registerMerchant({business_name:'Merchant Two',owner_name:'Owner Two',email:'merchant-two@example.test'});
 assert.equal(registration.status,'pending');assert.equal(registration.provider_status,'not_connected');
 const row=d.one<{tenant_id:string}>('SELECT tenant_id FROM registrations WHERE id=?',registration.registration_id)!;
 assert.throws(()=>s.createCredential(s.owner,{name:'Pending key',kind:'developer',scopes:['products:read'],max_amount:1000,refund_budget:0,tenant_id:row.tenant_id}),(e:unknown)=>e instanceof s.ApiError&&e.code==='merchant_pending');
 s.reviewRegistration(s.owner,{registration_id:registration.registration_id,decision:'approve'});
 const secondKey=write('key','merchant-key',{},()=>s.createCredential(s.owner,{name:'Merchant key',kind:'developer',scopes:['products:read','payments:write'],max_amount:10000,refund_budget:0,tenant_id:row.tenant_id}));
 const merchant=s.authenticate(new Request('http://localhost',{headers:{Authorization:`Bearer ${secondKey.secret}`}}));
 assert.equal(merchant.tenant_id,row.tenant_id);
 assert.throws(()=>s.createPayment(merchant,{product_id:product.id}),(e:unknown)=>e instanceof s.ApiError&&e.status===404);
 assert.throws(()=>s.createCredential(merchant,{name:'Cross tenant',kind:'developer',scopes:['products:read'],max_amount:1000,refund_budget:0,tenant_id:'owner'}),(e:unknown)=>e instanceof s.ApiError&&e.status===403);
});
await test('merchant invite is single use; password + MFA enrollment unlock only the approved tenant',async()=>{
 const env=process.env as Record<string,string|undefined>;const prior={origin:env.AGORA_PUBLIC_ORIGIN,token:env.AGORA_ADMIN_TOKEN,mfa:env.AGORA_MFA_ENCRYPTION_KEY,mfaPrevious:env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS};env.AGORA_PUBLIC_ORIGIN='https://agora.example';env.AGORA_ADMIN_TOKEN='merchant-session-key-long-enough-for-tests';env.AGORA_MFA_ENCRYPTION_KEY=Buffer.alloc(32,9).toString('base64');delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;
 try{
  const registration=s.registerMerchant({business_name:'Invited Merchant',owner_name:'Member',email:'invite@example.test'});const tenant=d.one<{tenant_id:string}>('SELECT tenant_id FROM registrations WHERE id=?',registration.registration_id)!.tenant_id;s.reviewRegistration(s.owner,{registration_id:registration.registration_id,decision:'approve'});
  const invite=s.createMerchantInvite(s.owner,tenant);assert.equal(d.one<{token_hash:string}>('SELECT token_hash FROM merchant_invites WHERE tenant_id=?',tenant)?.token_hash,createHash('sha256').update(invite.token).digest('hex'));
  const req=new Request('https://agora.example/api/auth/invite/accept',{method:'POST',headers:{origin:'https://agora.example'}});const result=await s.acceptMerchantInvite(req,{token:invite.token,password:'a secure merchant password'});assert.equal(result.stage,'enroll');assert.equal(result.email,'invite@example.test');
  const hash=d.one<{password_hash:string}>('SELECT password_hash FROM merchant_users WHERE tenant_id=?',tenant)?.password_hash;assert.match(hash||'',/^scrypt\$65536\$8\$2\$[A-Za-z0-9_-]{43}$/);
  const previousKey=env.AGORA_MFA_ENCRYPTION_KEY!,nextKey=Buffer.alloc(32,10).toString('base64');env.AGORA_MFA_ENCRYPTION_KEY=nextKey;env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS=previousKey;assert.deepEqual(s.migrateMfaEncryptionKeys(),{migrated:1,remaining_old:0});delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;
  const pending=new Request('https://agora.example/api/auth/merchant/mfa/enroll',{method:'POST',headers:{origin:'https://agora.example',cookie:`agora_merchant_pending=${result.cookie.value}`}});assert.equal(s.authSession(pending).authenticated,false);assert.match(s.setMerchantCookie(new Response(null),pending,'pending',result.cookie).headers.get('set-cookie')||'',/SameSite=Strict/);
  const enrolled=s.enrollMerchantMfa(pending,{code:totp(result.secret)});assert.equal(enrolled.recovery_codes.length,10);
  const session=new Request('https://agora.example/api/console',{headers:{origin:'https://agora.example',cookie:`agora_merchant_session=${enrolled.cookie.value}`}});const actor=s.consoleAuth(session);assert.equal(actor.tenant_id,tenant);assert.equal(s.authSession(session).role,'merchant');assert.match(s.setMerchantCookie(new Response(null),session,'member',enrolled.cookie).headers.get('set-cookie')||'',/SameSite=Lax/);
  const own=s.createProduct(actor,{name:'Member product',amount:700});assert.equal(own.name,'Member product');assert.equal(s.snapshot(actor.tenant_id).products.some((p)=>p.id===product.id),false);assert.equal(s.snapshot(actor.tenant_id).registrations.length,0);s.logout(session);assert.equal(s.authSession(session).authenticated,false);assert.throws(()=>s.consoleAuth(session));
  assert.throws(()=>s.createMerchantInvite(actor,tenant),(e:unknown)=>e instanceof s.ApiError&&e.code==='permission_denied');
  assert.equal(s.snapshot(tenant).payments.some((entry)=>entry.id===payment.id),false);
  assert.throws(()=>s.createRefund(actor,{payment_id:payment.id,amount:100,reason:'Cross tenant attempt'}),(e:unknown)=>e instanceof s.ApiError&&e.status===404);
  assert.throws(()=>s.reviewRegistration(actor,{registration_id:registration.registration_id,decision:'reject'}),(e:unknown)=>e instanceof s.ApiError&&e.status===403);
  assert.throws(()=>s.beginStripeConnect(actor,'owner','test','ca_fixture','https://agora.example/api/provider/stripe/callback'),(e:unknown)=>e instanceof s.ApiError&&e.status===403);
  assert.throws(()=>s.resolveApproval(actor,{approval_id:'owner-approval',decision:'approve'}),(e:unknown)=>e instanceof s.ApiError&&e.status===403);
  const apiKey=write('revocation-fixture','revocation-fixture',{},()=>s.createCredential(s.owner,{name:'Revocation fixture',kind:'developer',scopes:['payments:read','refunds:write'],max_amount:10000,refund_budget:1000,tenant_id:tenant})) as ReturnType<typeof s.createCredential>&{secret:string};
  const revokedActor=s.authenticate(new Request('https://api.example',{headers:{Authorization:`Bearer ${apiKey.secret}`}}));
  d.run("UPDATE tenants SET status='rejected' WHERE id=?",tenant);
  assert.throws(()=>s.consoleAuth(session),(e:unknown)=>e instanceof s.ApiError&&e.status===401);
  assert.throws(()=>s.authenticate(new Request('https://api.example',{headers:{Authorization:`Bearer ${apiKey.secret}`}})),(e:unknown)=>e instanceof s.ApiError&&e.code==='merchant_pending');
  assert.throws(()=>s.mutate(revokedActor,'payments','revoked-tenant',{x:1},()=>true),(e:unknown)=>e instanceof s.ApiError&&e.code==='merchant_pending');
  d.run("UPDATE tenants SET status='approved' WHERE id=?",tenant);
  await assert.rejects(()=>s.acceptMerchantInvite(req,{token:invite.token,password:'a different long password'}),(e:unknown)=>e instanceof s.ApiError&&e.code==='invite_invalid');
  const login=await s.merchantLogin(new Request('https://agora.example/api/auth/login',{method:'POST',headers:{origin:'https://agora.example'}}),{email:'invite@example.test',password:'a secure merchant password'});assert.equal(login.stage,'verify');
  d.run('DELETE FROM merchant_users WHERE tenant_id=?',tenant);
 }finally{if(prior.origin===undefined)delete env.AGORA_PUBLIC_ORIGIN;else env.AGORA_PUBLIC_ORIGIN=prior.origin;if(prior.token===undefined)delete env.AGORA_ADMIN_TOKEN;else env.AGORA_ADMIN_TOKEN=prior.token;if(prior.mfa===undefined)delete env.AGORA_MFA_ENCRYPTION_KEY;else env.AGORA_MFA_ENCRYPTION_KEY=prior.mfa;if(prior.mfaPrevious===undefined)delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;else env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS=prior.mfaPrevious;}
});
await test('valid invite password KDF submissions are rate-limited and serialized before expensive work',async()=>{
 const env=process.env as Record<string,string|undefined>;const prior={origin:env.AGORA_PUBLIC_ORIGIN,token:env.AGORA_ADMIN_TOKEN,mfa:env.AGORA_MFA_ENCRYPTION_KEY,mfaPrevious:env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS};env.AGORA_PUBLIC_ORIGIN='https://agora.example';env.AGORA_ADMIN_TOKEN='merchant-session-key-long-enough-for-tests';env.AGORA_MFA_ENCRYPTION_KEY=Buffer.alloc(32,11).toString('base64');delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;
 let tenant:string|undefined;
 try{
  const registration=s.registerMerchant({business_name:'Rate Limited Merchant',owner_name:'Member',email:'rate-invite@example.test'});tenant=d.one<{tenant_id:string}>('SELECT tenant_id FROM registrations WHERE id=?',registration.registration_id)!.tenant_id;s.reviewRegistration(s.owner,{registration_id:registration.registration_id,decision:'approve'});const invite=s.createMerchantInvite(s.owner,tenant);
  const attempts=await Promise.allSettled(Array.from({length:6},()=>s.acceptMerchantInvite(new Request('https://agora.example/api/auth/invite/accept',{method:'POST',headers:{origin:'https://agora.example'}}),{token:invite.token,password:'a sufficiently long fixture password'})));
  const completed=attempts.filter((result)=>result.status==='fulfilled');const rejected=attempts.filter((result)=>result.status==='rejected');assert.equal(completed.length,1);assert.ok(rejected.some((result)=>result.status==='rejected'&&result.reason instanceof s.ApiError&&result.reason.status===429));assert.equal(d.all('SELECT id FROM merchant_users WHERE tenant_id=?',tenant).length,1);
 }finally{if(tenant){d.run('DELETE FROM merchant_users WHERE tenant_id=?',tenant);d.run('DELETE FROM merchant_invites WHERE tenant_id=?',tenant);d.run('DELETE FROM registrations WHERE tenant_id=?',tenant);d.run('DELETE FROM tenants WHERE id=?',tenant);}if(prior.origin===undefined)delete env.AGORA_PUBLIC_ORIGIN;else env.AGORA_PUBLIC_ORIGIN=prior.origin;if(prior.token===undefined)delete env.AGORA_ADMIN_TOKEN;else env.AGORA_ADMIN_TOKEN=prior.token;if(prior.mfa===undefined)delete env.AGORA_MFA_ENCRYPTION_KEY;else env.AGORA_MFA_ENCRYPTION_KEY=prior.mfa;if(prior.mfaPrevious===undefined)delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;else env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS=prior.mfaPrevious;}
});
await test('Stripe pending refunds reserve each credential’s cumulative budget',()=>{
 const env=process.env as Record<string,string|undefined>;const before={provider:env.AGORA_PAYMENT_PROVIDER,mode:env.AGORA_STRIPE_MODE,secret:env.STRIPE_TEST_WEBHOOK_SECRET,key:env.STRIPE_TEST_SECRET_KEY,origin:env.AGORA_PUBLIC_ORIGIN};env.AGORA_PAYMENT_PROVIDER='stripe';env.AGORA_STRIPE_MODE='test';env.STRIPE_TEST_WEBHOOK_SECRET='whsec_budget_test';env.STRIPE_TEST_SECRET_KEY='sk_test_budgetfixture123';env.AGORA_PUBLIC_ORIGIN='https://agora.example';
 try{
  const p=write('budget-stripe-payment', 'budget-stripe-payment',{},()=>s.createPayment(s.owner,{product_id:product.id}));s.prepareStripePayment(p.id,'test');s.saveStripeSession(p.id,{id:'cs_test_budget',url:'https://checkout.stripe.com/c/pay',payment_intent:'pi_test_budget',status:'open'},'test');
  const event={id:'evt_budget_paid',type:'checkout.session.completed',livemode:false,data:{object:{id:'cs_test_budget',payment_status:'paid',amount_total:p.amount,currency:'usd',payment_intent:'pi_test_budget',metadata:{agora_payment_id:p.id,agora_tenant_id:'owner'}}}};const raw=JSON.stringify(event),timestamp=Math.floor(Date.now()/1000),sig=createHmac('sha256',env.STRIPE_TEST_WEBHOOK_SECRET!).update(`${timestamp}.${raw}`).digest('hex');s.handleStripeWebhook(raw,`t=${timestamp},v1=${sig}`);
  const c=write('budget-key','budget-key',{},()=>s.createCredential(s.owner,{name:'Budget reservation',kind:'agent',scopes:['refunds:write'],max_amount:10000,refund_budget:1000}));const actor=s.authenticate(new Request('https://api.example',{headers:{Authorization:`Bearer ${c.secret}`}}));
  const first=s.createRefund(actor,{payment_id:p.id,amount:700,reason:'Reserve provider refund'});assert.equal(first.status,'pending');
  const second=s.createRefund(actor,{payment_id:p.id,amount:400,reason:'Exceeds pending reserve'});assert.equal(second.status,'requires_approval');
 }finally{if(before.provider===undefined)delete env.AGORA_PAYMENT_PROVIDER;else env.AGORA_PAYMENT_PROVIDER=before.provider;if(before.mode===undefined)delete env.AGORA_STRIPE_MODE;else env.AGORA_STRIPE_MODE=before.mode;if(before.secret===undefined)delete env.STRIPE_TEST_WEBHOOK_SECRET;else env.STRIPE_TEST_WEBHOOK_SECRET=before.secret;if(before.key===undefined)delete env.STRIPE_TEST_SECRET_KEY;else env.STRIPE_TEST_SECRET_KEY=before.key;if(before.origin===undefined)delete env.AGORA_PUBLIC_ORIGIN;else env.AGORA_PUBLIC_ORIGIN=before.origin;}
});
await test('Stripe webhook arriving before session persistence does not lose the Checkout mapping',()=>{
 const env=process.env as Record<string,string|undefined>;const previous=env.STRIPE_TEST_WEBHOOK_SECRET;env.STRIPE_TEST_WEBHOOK_SECRET='whsec_early_event';
 try{const p=write('early-event-payment','early-event-payment',{},()=>s.createPayment(s.owner,{product_id:product.id}));s.prepareStripePayment(p.id,'test');const event={id:'evt_early_checkout',type:'checkout.session.completed',livemode:false,data:{object:{id:'cs_test_early',payment_status:'paid',amount_total:p.amount,currency:'usd',payment_intent:'pi_test_early',metadata:{agora_payment_id:p.id,agora_tenant_id:'owner'}}}};const raw=JSON.stringify(event),timestamp=Math.floor(Date.now()/1000),sig=createHmac('sha256',env.STRIPE_TEST_WEBHOOK_SECRET!).update(`${timestamp}.${raw}`).digest('hex');assert.equal(s.handleStripeWebhook(raw,`t=${timestamp},v1=${sig}`).status,'succeeded');s.saveStripeSession(p.id,{id:'cs_test_early',url:'https://checkout.stripe.com/c/pay',payment_intent:'pi_test_early',status:'open'},'test');assert.equal(d.one<{provider_session_id:string}>('SELECT provider_session_id FROM payments WHERE id=?',p.id)?.provider_session_id,'cs_test_early');}
 finally{if(previous===undefined)delete env.STRIPE_TEST_WEBHOOK_SECRET;else env.STRIPE_TEST_WEBHOOK_SECRET=previous;}
});
await test('Stripe webhook completion is mode-bound and replay-safe; sandbox cannot settle Stripe payments',()=>{
 const payment=write('payment','stripe-hook-payment',{},()=>s.createPayment(s.owner,{product_id:product.id}));
 s.prepareStripePayment(payment.id,'test');s.saveStripeSession(payment.id,{id:'cs_test_hook',url:'https://checkout.stripe.com/c/pay',payment_intent:'pi_test_hook',status:'open'},'test');
 assert.throws(()=>s.simulate(payment.checkout_token,{outcome:'succeeded'}),(e:unknown)=>e instanceof s.ApiError&&e.code==='processor_checkout');
 const env=process.env as Record<string,string|undefined>;const prior=env.STRIPE_TEST_WEBHOOK_SECRET;env.STRIPE_TEST_WEBHOOK_SECRET='whsec_test_service_secret';
 try{
  const event={id:'evt_service_1',type:'checkout.session.completed',livemode:false,data:{object:{id:'cs_test_hook',payment_status:'paid',amount_total:product.amount,currency:'usd',metadata:{agora_payment_id:payment.id,agora_tenant_id:'owner'}}}};
  const raw=JSON.stringify(event);const timestamp=Math.floor(Date.now()/1000);const sig=createHmac('sha256',env.STRIPE_TEST_WEBHOOK_SECRET).update(`${timestamp}.${raw}`).digest('hex');const header=`t=${timestamp},v1=${sig}`;
  assert.deepEqual(s.handleStripeWebhook(raw,header),{received:true,duplicate:false,status:'succeeded'});
  assert.deepEqual(s.handleStripeWebhook(raw,header),{received:true,duplicate:true});
  const linkedOrder=d.one<{id:string;status:string}>('SELECT id,status FROM orders WHERE payment_id=?',payment.id);assert.ok(linkedOrder);assert.equal(linkedOrder.status,'paid');assert.equal(d.one<{status:string}>('SELECT status FROM fulfillments WHERE order_id=?',linkedOrder.id)?.status,'ready');
  assert.equal(d.all('SELECT * FROM journal WHERE reference_id=?',payment.id).length,2);
  const refund=write('stripe-refund','stripe-refund-1',{payment_id:payment.id,amount:500,reason:'Test refund'},()=>s.createRefund(s.owner,{payment_id:payment.id,amount:500,reason:'Test refund'})) as unknown as {id:string;status:string;provider:string};
  assert.equal(refund.status,'pending');assert.equal(refund.provider,'stripe');assert.equal(d.one<{refunded:number}>('SELECT refunded FROM payments WHERE id=?',payment.id)?.refunded,0);
  const finalize=()=>d.transaction(()=>s.recordStripeRefundResult(refund.id,'re_test_refund_1','succeeded'));
  assert.equal(finalize().status,'succeeded');assert.equal(finalize().status,'succeeded');assert.equal(d.one<{refunded:number}>('SELECT refunded FROM payments WHERE id=?',payment.id)?.refunded,500);assert.equal(d.all('SELECT * FROM journal WHERE reference_id=?',refund.id).length,2);
  const saved=s.stripeRefundResult(refund.id,'owner');assert.equal(saved.status,'succeeded');assert.equal(saved.provider_refund_id,'re_test_refund_1');assert.equal(saved.tenant_id,'owner');
  const liveEvent={...event,id:'evt_service_live',livemode:true};const liveRaw=JSON.stringify(liveEvent);const liveSig=createHmac('sha256',env.STRIPE_TEST_WEBHOOK_SECRET).update(`${timestamp}.${liveRaw}`).digest('hex');
  assert.throws(()=>s.handleStripeWebhook(liveRaw,`t=${timestamp},v1=${liveSig}`),(e:unknown)=>e instanceof s.ApiError&&e.code==='webhook_mode_mismatch');
 }finally{if(prior===undefined)delete env.STRIPE_TEST_WEBHOOK_SECRET;else env.STRIPE_TEST_WEBHOOK_SECRET=prior;}
});
await test('Stripe reconciliation checks exact session mapping and journals a missed success once',()=>{
 const p=write('payment','reconcile-payment',{},()=>s.createPayment(s.owner,{product_id:product.id}));s.prepareStripePayment(p.id,'test');s.saveStripeSession(p.id,{id:'cs_test_reconcile',url:'https://checkout.stripe.com/c/pay',payment_intent:'pi_test_reconcile',status:'open'},'test');
 const session={id:'cs_test_reconcile',status:'complete' as const,payment_status:'paid' as const,amount_total:p.amount,currency:'usd',client_reference_id:p.id,payment_intent:'pi_test_reconcile',livemode:false,metadata:{agora_payment_id:p.id,agora_tenant_id:'owner'}};
 assert.throws(()=>s.reconcileStripePayment(p.id,'owner',{...session,amount_total:p.amount+1}),(e:unknown)=>e instanceof s.ApiError&&e.code==='provider_reconcile_mismatch');
 assert.deepEqual(s.reconcileStripePayment(p.id,'owner',session),{id:p.id,status:'succeeded',reconciled:true});assert.deepEqual(s.reconcileStripePayment(p.id,'owner',session),{id:p.id,status:'succeeded',reconciled:false});assert.equal(d.all('SELECT * FROM journal WHERE reference_id=?',p.id).length,2);
 assert.throws(()=>s.stripePaymentReconcileContext(p.id,'different-tenant'),(e:unknown)=>e instanceof s.ApiError&&e.status===404);
});
await test('Standard OAuth state is tenant, mode, redirect, expiry and replay bound; linked account never crosses tenants',()=>{
 const registration=s.registerMerchant({business_name:'OAuth Merchant',owner_name:'Owner',email:'oauth@example.test'});const tenant=d.one<{tenant_id:string}>('SELECT tenant_id FROM registrations WHERE id=?',registration.registration_id)!.tenant_id;s.reviewRegistration(s.owner,{registration_id:registration.registration_id,decision:'approve'});
 const other=s.registerMerchant({business_name:'Second Merchant',owner_name:'Owner',email:'oauth2@example.test'});const otherTenant=d.one<{tenant_id:string}>('SELECT tenant_id FROM registrations WHERE id=?',other.registration_id)!.tenant_id;s.reviewRegistration(s.owner,{registration_id:other.registration_id,decision:'approve'});
 const redirect='https://agora.example/api/provider/stripe/callback';const started=s.beginStripeConnect(s.owner,tenant,'test','ca_testclient',redirect);assert.match(started.authorize_url,/connect\.stripe\.com\/oauth\/authorize/);assert.equal(started.expires_at.length>0,true);
 assert.throws(()=>s.consumeStripeConnectState(started.state,'live',redirect),(e:unknown)=>e instanceof s.ApiError&&e.code==='invalid_oauth_state');
 const consumed=s.consumeStripeConnectState(started.state,'test',redirect);assert.equal(consumed.tenant_id,tenant);
 assert.throws(()=>s.consumeStripeConnectState(started.state,'test',redirect),(e:unknown)=>e instanceof s.ApiError&&e.code==='invalid_oauth_state');
 const connected=s.saveStripeConnectedAccount(tenant,'test',{id:'acct_testoauth1',charges_enabled:true,payouts_enabled:true,details_submitted:true,capabilities:{card_payments:'active'}});assert.equal(connected.status,'connected');assert.equal(s.stripeAccountForTenant(tenant,'test')?.account_id,'acct_testoauth1');assert.equal(s.stripeAccountForTenant(tenant,'live'),null);
 assert.throws(()=>s.saveStripeConnectedAccount(otherTenant,'test',{id:'acct_testoauth1',charges_enabled:true,payouts_enabled:true,details_submitted:true,capabilities:{}}),(e:unknown)=>e instanceof s.ApiError&&e.code==='provider_account_in_use');
});
await test('connected-account webhook must match the linked Stripe account and tenant metadata',()=>{
 const registration=s.registerMerchant({business_name:'Connected Merchant',owner_name:'Owner',email:'connected@example.test'});const tenant=d.one<{tenant_id:string}>('SELECT tenant_id FROM registrations WHERE id=?',registration.registration_id)!.tenant_id;s.reviewRegistration(s.owner,{registration_id:registration.registration_id,decision:'approve'});s.saveStripeConnectedAccount(tenant,'test',{id:'acct_connected123',charges_enabled:true,payouts_enabled:true,details_submitted:true,capabilities:{card_payments:'active'}});
 const product=s.createProduct({...s.owner,tenant_id:tenant},{name:'Merchant item',amount:1250});const merchantPayment=s.createPayment({...s.owner,tenant_id:tenant},{product_id:product.id});s.prepareStripePayment(merchantPayment.id,'test',tenant,'acct_connected123');s.saveStripeSession(merchantPayment.id,{id:'cs_test_connected',url:'https://checkout.stripe.com/c/pay',payment_intent:'pi_test_connected',status:'open'},'test',tenant,'acct_connected123');
 const env=process.env as Record<string,string|undefined>;const prior=env.STRIPE_TEST_WEBHOOK_SECRET;env.STRIPE_TEST_WEBHOOK_SECRET='whsec_connected_test';
 try{const event={id:'evt_connected_good',type:'checkout.session.completed',account:'acct_connected123',livemode:false,data:{object:{id:'cs_test_connected',payment_status:'paid',amount_total:1250,currency:'usd',payment_intent:'pi_test_connected',metadata:{agora_payment_id:merchantPayment.id,agora_tenant_id:tenant}}}};const sign=(value:unknown)=>{const raw=JSON.stringify(value);const timestamp=Math.floor(Date.now()/1000);const sig=createHmac('sha256',env.STRIPE_TEST_WEBHOOK_SECRET!).update(`${timestamp}.${raw}`).digest('hex');return{raw,header:`t=${timestamp},v1=${sig}`};};const wrong=sign({...event,id:'evt_connected_wrong',account:'acct_other'});assert.throws(()=>s.handleStripeWebhook(wrong.raw,wrong.header),(e:unknown)=>e instanceof s.ApiError&&e.code==='webhook_account_mismatch');const valid=sign(event);assert.equal(s.handleStripeWebhook(valid.raw,valid.header).status,'succeeded');assert.equal(d.one<{status:string}>('SELECT status FROM payments WHERE id=? AND tenant_id=?',merchantPayment.id,tenant)?.status,'succeeded');assert.equal(d.all('SELECT * FROM journal WHERE reference_id=? AND tenant_id=?',merchantPayment.id,tenant).length,2);}finally{if(prior===undefined)delete env.STRIPE_TEST_WEBHOOK_SECRET;else env.STRIPE_TEST_WEBHOOK_SECRET=prior;}
});
await test('console rejects cross-site requests',()=>{assert.throws(()=>s.consoleAuth(new Request('http://localhost/api/console',{headers:{host:'localhost',origin:'https://attacker.example','sec-fetch-site':'cross-site'}})));});
function totp(secret:string){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,value=0;const bytes:number[]=[];for(const c of secret){value=(value<<5)|alphabet.indexOf(c);bits+=5;if(bits>=8){bytes.push((value>>>(bits-8))&255);bits-=8;}}const counter=Math.floor(Date.now()/30000);const input=Buffer.alloc(8);input.writeBigUInt64BE(BigInt(counter));const digest=createHmac('sha1',Buffer.from(bytes)).update(input).digest();const offset=digest[digest.length-1]&15;return String((digest.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,'0');}
await test('owner password requires MFA enrollment; replay and recovery-code reuse are rejected',()=>{
 const env=process.env as Record<string,string|undefined>;
 const prior={password:env.AGORA_ADMIN_PASSWORD,token:env.AGORA_ADMIN_TOKEN,nodeEnv:env.NODE_ENV,origin:env.AGORA_PUBLIC_ORIGIN,mfaKey:env.AGORA_MFA_ENCRYPTION_KEY,mfaPrevious:env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS};
 env.AGORA_ADMIN_PASSWORD='correct horse battery staple';env.AGORA_ADMIN_TOKEN='test-only-signing-secret-long-enough-for-auth';env.AGORA_PUBLIC_ORIGIN='https://agora.example';env.AGORA_MFA_ENCRYPTION_KEY=Buffer.alloc(32,7).toString('base64');delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;env.AGORA_OWNER_EMAIL='owner@example.test';env.NODE_ENV='production';
 try{
  const loginRequest=new Request('https://api.example/api/auth/login',{method:'POST',headers:{host:'api.example',origin:'https://agora.example'},body:'{}'});
  const badOrigin=new Request('https://api.example/api/auth/login',{method:'POST',headers:{host:'api.example',origin:'https://attacker.example'},body:'{}'});
  assert.throws(()=>s.beginAdminLogin(badOrigin,{password:'wrong'}));
  const setup=s.beginAdminLogin(loginRequest,{password:env.AGORA_ADMIN_PASSWORD});assert.equal(setup.stage,'enroll');
  const pending=s.setMfaCookie(new Response(null),loginRequest,'pending',setup.cookie).headers.get('set-cookie')!.split(';')[0];
  const pendingRequest=new Request('https://api.example/api/auth/mfa/enroll',{method:'POST',headers:{host:'api.example',origin:'https://agora.example',cookie:pending}});
  assert.throws(()=>s.consoleAuth(pendingRequest,true));
  const enrolled=s.enrollAdminMfa(pendingRequest,{code:totp(setup.secret)});assert.equal(enrolled.recovery_codes.length,10);const oldKey=env.AGORA_MFA_ENCRYPTION_KEY!,newKey=Buffer.alloc(32,8).toString('base64');env.AGORA_MFA_ENCRYPTION_KEY=newKey;env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS=oldKey;assert.deepEqual(s.migrateMfaEncryptionKeys(),{migrated:1,remaining_old:0});delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;
  const ownerCookieHeader=s.setSessionCookie(new Response(null),loginRequest,enrolled.cookie).headers.get('set-cookie')!;assert.match(ownerCookieHeader,/SameSite=Lax/);const session=ownerCookieHeader.split(';')[0];assert.match(s.setMfaCookie(new Response(null),loginRequest,'pending',setup.cookie).headers.get('set-cookie')||'',/SameSite=Strict/);
  assert.equal(s.hasAdminSession(new Request('https://api.example/api/auth/session',{headers:{host:'api.example',cookie:session}})),true);
  const consoleRequest=new Request('https://api.example/api/console',{headers:{host:'api.example',cookie:session,origin:'https://agora.example'}});assert.equal(s.consoleAuth(consoleRequest).id,'console_owner');s.logout(consoleRequest);assert.equal(s.hasAdminSession(new Request('https://api.example/api/auth/session',{headers:{host:'api.example',cookie:session}})),false);
  const second=s.beginAdminLogin(loginRequest,{password:env.AGORA_ADMIN_PASSWORD});assert.equal(second.stage,'verify');
  const verifyRequest=new Request('https://api.example/api/auth/mfa/verify',{method:'POST',headers:{host:'api.example',origin:'https://agora.example',cookie:s.setMfaCookie(new Response(null),loginRequest,'pending',second.cookie).headers.get('set-cookie')!.split(';')[0]}});
  assert.throws(()=>s.verifyAdminMfa(verifyRequest,{code:totp(setup.secret)}),(e:unknown)=>e instanceof s.ApiError&&e.code==='invalid_mfa_code');
  const recovery=enrolled.recovery_codes[0];const verified=s.verifyAdminMfa(verifyRequest,{recovery_code:recovery});assert.ok(verified.cookie.value);
  const next=s.beginAdminLogin(loginRequest,{password:env.AGORA_ADMIN_PASSWORD});const nextRequest=new Request('https://api.example/api/auth/mfa/verify',{method:'POST',headers:{host:'api.example',origin:'https://agora.example',cookie:s.setMfaCookie(new Response(null),loginRequest,'pending',next.cookie).headers.get('set-cookie')!.split(';')[0]}});
  assert.throws(()=>s.verifyAdminMfa(nextRequest,{recovery_code:recovery}),(e:unknown)=>e instanceof s.ApiError&&e.code==='invalid_mfa_code');
 }finally{
  if(prior.password===undefined)delete env.AGORA_ADMIN_PASSWORD;else env.AGORA_ADMIN_PASSWORD=prior.password;
  if(prior.token===undefined)delete env.AGORA_ADMIN_TOKEN;else env.AGORA_ADMIN_TOKEN=prior.token;
  if(prior.nodeEnv===undefined)delete env.NODE_ENV;else env.NODE_ENV=prior.nodeEnv;
  if(prior.origin===undefined)delete env.AGORA_PUBLIC_ORIGIN;else env.AGORA_PUBLIC_ORIGIN=prior.origin;
  if(prior.mfaKey&&env.AGORA_MFA_ENCRYPTION_KEY&&prior.mfaKey!==env.AGORA_MFA_ENCRYPTION_KEY){const rotated=env.AGORA_MFA_ENCRYPTION_KEY;env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS=rotated;env.AGORA_MFA_ENCRYPTION_KEY=prior.mfaKey;s.migrateMfaEncryptionKeys();delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;}else if(prior.mfaKey===undefined)d.run('DELETE FROM owner_mfa');
  if(prior.mfaKey===undefined)delete env.AGORA_MFA_ENCRYPTION_KEY;else env.AGORA_MFA_ENCRYPTION_KEY=prior.mfaKey;
  if(prior.mfaPrevious===undefined)delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;else env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS=prior.mfaPrevious;
 }
});
d.db.close();rmSync(dir,{recursive:true,force:true});
