import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash, createHmac } from 'node:crypto';
const dir=mkdtempSync(join(tmpdir(),'agora-test-'));process.env.AGORA_DATABASE_PATH=join(dir,'test.sqlite');process.env.AGORA_SEED='false';
const s=await import('../lib/server/local');const d=await import('../lib/server/db');
const write=<T>(route:string,key:string,body:unknown,fn:()=>T,actor=s.owner)=>s.mutate(actor,route,key,body,fn);
const product=write('product','p1',{},()=>s.createProduct(s.owner,{name:'Test',amount:5000}));
const payment=write('payment','pay1',{},()=>s.createPayment(s.owner,{product_id:product.id}));
function key(name:string,budget:number,permissions:string[]=s.scopes as unknown as string[]){const c=write('key',name,{},()=>s.createCredential(s.owner,{name,kind:'agent',scopes:permissions,max_amount:10000,refund_budget:budget}));return{...c,actor:s.authenticate(new Request('http://localhost',{headers:{Authorization:`Bearer ${c.secret}`}}))}}
await test('same idempotency key creates only one payment; changed payload conflicts',()=>{const replay=write('payment','pay1',{},()=>s.createPayment(s.owner,{product_id:product.id}));assert.equal(replay.id,payment.id);assert.equal(d.all('SELECT * FROM payments').length,1);assert.throws(()=>write('payment','pay1',{changed:true},()=>null),(e:unknown)=>e instanceof s.ApiError&&e.status===409)});
await test('checkout success replay journals once, conflicting outcome is rejected',()=>{s.simulate(payment.checkout_token,{outcome:'succeeded'});s.simulate(payment.checkout_token,{outcome:'succeeded'});assert.equal(d.all('SELECT * FROM journal').length,2);assert.throws(()=>s.simulate(payment.checkout_token,{outcome:'failed'}));assert.equal(d.one<{sum:number}>('SELECT SUM(amount) AS sum FROM journal')?.sum,0)});
await test('limited agent needs human approval; replay does not duplicate request',()=>{const k=key('Limited',0);const b={payment_id:payment.id,amount:1000,reason:'Customer request'};const a=write('refund','r1',b,()=>s.createRefund(k.actor,b),k.actor);const again=write('refund','r1',b,()=>s.createRefund(k.actor,b),k.actor);assert.equal(a.id,again.id);assert.equal(a.status,'requires_approval');assert.equal(d.one<{refunded:number}>('SELECT refunded FROM payments WHERE id=?',payment.id)?.refunded,0);write('approve','a1',{},()=>s.resolveApproval(s.owner,{approval_id:a.id,decision:'approve'}));assert.equal(d.one<{refunded:number}>('SELECT refunded FROM payments WHERE id=?',payment.id)?.refunded,1000);assert.throws(()=>write('approve','a2',{},()=>s.resolveApproval(s.owner,{approval_id:a.id,decision:'approve'})));});
await test('cumulative allowance cannot be exceeded by splitting refunds',()=>{const k=key('Budget',1000);const b={payment_id:payment.id,amount:600,reason:'Partial return'};assert.equal(write('refund','b1',b,()=>s.createRefund(k.actor,b),k.actor).status,'succeeded');assert.equal(write('refund','b2',b,()=>s.createRefund(k.actor,b),k.actor).status,'requires_approval');assert.equal(d.one<{spent:number}>('SELECT spent FROM credentials WHERE id=?',k.id)?.spent,600)});
await test('read-only keys and amount limits are enforced',()=>{const k=key('Reader',0,['payments:read']);assert.throws(()=>write('refund','x1',{},()=>s.createRefund(k.actor,{payment_id:payment.id,amount:1,reason:'Test'}),k.actor),(e:unknown)=>e instanceof s.ApiError&&e.status===403);const expensive=write('product','p2',{},()=>s.createProduct(s.owner,{name:'Expensive',amount:20000}));const full=key('Small limit',0);assert.throws(()=>write('payment','high',{},()=>s.createPayment(full.actor,{product_id:expensive.id}),full.actor));});
await test('API keys are pinned to their creation mode and cannot cross test/live',()=>{const env=process.env as Record<string,string|undefined>;const before={provider:env.AGORA_PAYMENT_PROVIDER,mode:env.AGORA_STRIPE_MODE};env.AGORA_PAYMENT_PROVIDER='stripe';env.AGORA_STRIPE_MODE='test';try{const created=write('mode-key','mode-key-1',{},()=>s.createCredential(s.owner,{name:'Mode test key',kind:'developer',scopes:['payments:write','refunds:write'],max_amount:10000,refund_budget:1000}));assert.equal(created.provider_mode,'test');assert.match(created.secret,/^ag_test_/);const actor=s.authenticate(new Request('https://api.example',{headers:{Authorization:`Bearer ${created.secret}`}}));s.requireProviderMode(actor,'test');assert.throws(()=>s.requireProviderMode(actor,'live'),(e:unknown)=>e instanceof s.ApiError&&e.code==='key_mode_mismatch');assert.throws(()=>s.createRefund(actor,{payment_id:payment.id,amount:100,reason:'Wrong mode'}),(e:unknown)=>e instanceof s.ApiError&&e.code==='key_mode_mismatch');}finally{if(before.provider===undefined)delete env.AGORA_PAYMENT_PROVIDER;else env.AGORA_PAYMENT_PROVIDER=before.provider;if(before.mode===undefined)delete env.AGORA_STRIPE_MODE;else env.AGORA_STRIPE_MODE=before.mode;}});
await test('revocation invalidates keys and prevents pending approval execution',()=>{const k=key('Revoke me',0);const b={payment_id:payment.id,amount:100,reason:'Return'};const a=write('refund','rev1',b,()=>s.createRefund(k.actor,b),k.actor);write('revoke','rev',{},()=>s.revokeCredential(s.owner,{key_id:k.id}));assert.throws(()=>s.authenticate(new Request('http://localhost',{headers:{Authorization:`Bearer ${k.secret}`}})));assert.throws(()=>write('approve','revapprove',{},()=>s.resolveApproval(s.owner,{approval_id:a.id,decision:'approve'})));assert.throws(()=>write('refund','rev1',b,()=>s.createRefund(k.actor,b),k.actor));});
await test('over-refunds roll back without additional journal or event effects',()=>{const before=d.all('SELECT * FROM events').length;assert.throws(()=>write('refund','too-much',{},()=>s.createRefund(s.owner,{payment_id:payment.id,amount:5000,reason:'Over refund'})));assert.equal(d.all('SELECT * FROM events').length,before);assert.equal(d.one<{sum:number}>('SELECT SUM(amount) AS sum FROM journal')?.sum,0);assert.equal(d.all('SELECT * FROM idempotency WHERE key=?','too-much').length,0)});
await test('raw card-like fields and decimal amounts are rejected',()=>{assert.throws(()=>write('product','bad',{},()=>s.createProduct(s.owner,{name:'Bad',amount:1.5})));assert.throws(()=>write('payment','pan',{},()=>s.createPayment(s.owner,{product_id:product.id,card_number:'test'})));});
await test('pending merchant registration is blocked, then receives a tenant-isolated key after owner review',()=>{
 const registration=s.registerMerchant({business_name:'Merchant Two',owner_name:'Owner Two',email:'merchant-two@example.test'});
 assert.equal(registration.status,'pending');assert.equal(registration.provider_status,'not_connected');
 const row=d.one<{tenant_id:string}>('SELECT tenant_id FROM registrations WHERE id=?',registration.registration_id)!;
 assert.throws(()=>s.createCredential(s.owner,{name:'Pending key',kind:'developer',scopes:['products:read'],max_amount:1000,refund_budget:0,tenant_id:row.tenant_id}),(e:unknown)=>e instanceof s.ApiError&&e.code==='merchant_pending');
 s.reviewRegistration(s.owner,{registration_id:registration.registration_id,decision:'approve'});
 const secondKey=write('key','merchant-key',{},()=>s.createCredential(s.owner,{name:'Merchant key',kind:'developer',scopes:['products:read','payments:write'],max_amount:10000,refund_budget:0,tenant_id:row.tenant_id}));
 const merchant=s.authenticate(new Request('http://localhost',{headers:{Authorization:`Bearer ${secondKey.secret}`}}));
 assert.equal(merchant.tenant_id,row.tenant_id);
 assert.throws(()=>s.createPayment(merchant,{product_id:product.id}),(e:unknown)=>e instanceof s.ApiError&&e.status===404);
 assert.throws(()=>s.createCredential(merchant,{name:'Cross tenant',kind:'developer',scopes:['products:read'],max_amount:1000,refund_budget:0,tenant_id:'owner'}),(e:unknown)=>e instanceof s.ApiError&&e.status===403);
});
await test('merchant invite is single use; password + MFA enrollment unlock only the approved tenant',async()=>{
 const env=process.env as Record<string,string|undefined>;const prior={origin:env.AGORA_PUBLIC_ORIGIN,token:env.AGORA_ADMIN_TOKEN,mfa:env.AGORA_MFA_ENCRYPTION_KEY,mfaPrevious:env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS};env.AGORA_PUBLIC_ORIGIN='https://agora.example';env.AGORA_ADMIN_TOKEN='merchant-session-key-long-enough-for-tests';env.AGORA_MFA_ENCRYPTION_KEY=Buffer.alloc(32,9).toString('base64');delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;
 try{
  const registration=s.registerMerchant({business_name:'Invited Merchant',owner_name:'Member',email:'invite@example.test'});const tenant=d.one<{tenant_id:string}>('SELECT tenant_id FROM registrations WHERE id=?',registration.registration_id)!.tenant_id;s.reviewRegistration(s.owner,{registration_id:registration.registration_id,decision:'approve'});
  const invite=s.createMerchantInvite(s.owner,tenant);assert.equal(d.one<{token_hash:string}>('SELECT token_hash FROM merchant_invites WHERE tenant_id=?',tenant)?.token_hash,createHash('sha256').update(invite.token).digest('hex'));
  const req=new Request('https://agora.example/api/auth/invite/accept',{method:'POST',headers:{origin:'https://agora.example'}});const result=await s.acceptMerchantInvite(req,{token:invite.token,password:'a secure merchant password'});assert.equal(result.stage,'enroll');assert.equal(result.email,'invite@example.test');
  const hash=d.one<{password_hash:string}>('SELECT password_hash FROM merchant_users WHERE tenant_id=?',tenant)?.password_hash;assert.match(hash||'',/^scrypt\$65536\$8\$2\$[A-Za-z0-9_-]{43}$/);
  const previousKey=env.AGORA_MFA_ENCRYPTION_KEY!,nextKey=Buffer.alloc(32,10).toString('base64');env.AGORA_MFA_ENCRYPTION_KEY=nextKey;env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS=previousKey;assert.deepEqual(s.migrateMfaEncryptionKeys(),{migrated:1,remaining_old:0});delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;
  const pending=new Request('https://agora.example/api/auth/merchant/mfa/enroll',{method:'POST',headers:{origin:'https://agora.example',cookie:`agora_merchant_pending=${result.cookie.value}`}});assert.equal(s.authSession(pending).authenticated,false);assert.match(s.setMerchantCookie(new Response(null),pending,'pending',result.cookie).headers.get('set-cookie')||'',/SameSite=Strict/);
  const enrolled=s.enrollMerchantMfa(pending,{code:totp(result.secret)});assert.equal(enrolled.recovery_codes.length,10);
  const session=new Request('https://agora.example/api/console',{headers:{origin:'https://agora.example',cookie:`agora_merchant_session=${enrolled.cookie.value}`}});const actor=s.consoleAuth(session);assert.equal(actor.tenant_id,tenant);assert.equal(s.authSession(session).role,'merchant');assert.match(s.setMerchantCookie(new Response(null),session,'member',enrolled.cookie).headers.get('set-cookie')||'',/SameSite=Lax/);
  const own=s.createProduct(actor,{name:'Member product',amount:700});assert.equal(own.name,'Member product');assert.equal(s.snapshot(actor.tenant_id).products.some((p)=>p.id===product.id),false);assert.equal(s.snapshot(actor.tenant_id).registrations.length,0);s.logout(session);assert.equal(s.authSession(session).authenticated,false);assert.throws(()=>s.consoleAuth(session));
  assert.throws(()=>s.createMerchantInvite(actor,tenant),(e:unknown)=>e instanceof s.ApiError&&e.code==='permission_denied');
  await assert.rejects(()=>s.acceptMerchantInvite(req,{token:invite.token,password:'a different long password'}),(e:unknown)=>e instanceof s.ApiError&&e.code==='invite_invalid');
  const login=await s.merchantLogin(new Request('https://agora.example/api/auth/login',{method:'POST',headers:{origin:'https://agora.example'}}),{email:'invite@example.test',password:'a secure merchant password'});assert.equal(login.stage,'verify');
  d.run('DELETE FROM merchant_users WHERE tenant_id=?',tenant);
 }finally{if(prior.origin===undefined)delete env.AGORA_PUBLIC_ORIGIN;else env.AGORA_PUBLIC_ORIGIN=prior.origin;if(prior.token===undefined)delete env.AGORA_ADMIN_TOKEN;else env.AGORA_ADMIN_TOKEN=prior.token;if(prior.mfa===undefined)delete env.AGORA_MFA_ENCRYPTION_KEY;else env.AGORA_MFA_ENCRYPTION_KEY=prior.mfa;if(prior.mfaPrevious===undefined)delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;else env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS=prior.mfaPrevious;}
});
await test('Stripe webhook completion is mode-bound and replay-safe; sandbox cannot settle Stripe payments',()=>{
 const payment=write('payment','stripe-hook-payment',{},()=>s.createPayment(s.owner,{product_id:product.id}));
 s.prepareStripePayment(payment.id,'test');s.saveStripeSession(payment.id,{id:'cs_test_hook',url:'https://checkout.stripe.com/c/pay',payment_intent:'pi_test_hook',status:'open'},'test');
 assert.throws(()=>s.simulate(payment.checkout_token,{outcome:'succeeded'}),(e:unknown)=>e instanceof s.ApiError&&e.code==='processor_checkout');
 const env=process.env as Record<string,string|undefined>;const prior=env.STRIPE_TEST_WEBHOOK_SECRET;env.STRIPE_TEST_WEBHOOK_SECRET='whsec_test_service_secret';
 try{
  const event={id:'evt_service_1',type:'checkout.session.completed',livemode:false,data:{object:{id:'cs_test_hook',payment_status:'paid',amount_total:product.amount,currency:'usd',metadata:{agora_payment_id:payment.id,agora_tenant_id:'owner'}}}};
  const raw=JSON.stringify(event);const timestamp=Math.floor(Date.now()/1000);const sig=createHmac('sha256',env.STRIPE_TEST_WEBHOOK_SECRET).update(`${timestamp}.${raw}`).digest('hex');const header=`t=${timestamp},v1=${sig}`;
  assert.deepEqual(s.handleStripeWebhook(raw,header),{received:true,duplicate:false,status:'succeeded'});
  assert.deepEqual(s.handleStripeWebhook(raw,header),{received:true,duplicate:true});
  assert.equal(d.all('SELECT * FROM journal WHERE reference_id=?',payment.id).length,2);
  const refund=write('stripe-refund','stripe-refund-1',{payment_id:payment.id,amount:500,reason:'Test refund'},()=>s.createRefund(s.owner,{payment_id:payment.id,amount:500,reason:'Test refund'})) as unknown as {id:string;status:string;provider:string};
  assert.equal(refund.status,'pending');assert.equal(refund.provider,'stripe');assert.equal(d.one<{refunded:number}>('SELECT refunded FROM payments WHERE id=?',payment.id)?.refunded,0);
  const finalize=()=>d.transaction(()=>s.recordStripeRefundResult(refund.id,'re_test_refund_1','succeeded'));
  assert.equal(finalize().status,'succeeded');assert.equal(finalize().status,'succeeded');assert.equal(d.one<{refunded:number}>('SELECT refunded FROM payments WHERE id=?',payment.id)?.refunded,500);assert.equal(d.all('SELECT * FROM journal WHERE reference_id=?',refund.id).length,2);
  const saved=s.stripeRefundResult(refund.id,'owner');assert.equal(saved.status,'succeeded');assert.equal(saved.provider_refund_id,'re_test_refund_1');assert.equal(saved.tenant_id,'owner');
  const liveEvent={...event,id:'evt_service_live',livemode:true};const liveRaw=JSON.stringify(liveEvent);const liveSig=createHmac('sha256',env.STRIPE_TEST_WEBHOOK_SECRET).update(`${timestamp}.${liveRaw}`).digest('hex');
  assert.throws(()=>s.handleStripeWebhook(liveRaw,`t=${timestamp},v1=${liveSig}`),(e:unknown)=>e instanceof s.ApiError&&e.code==='webhook_mode_mismatch');
 }finally{if(prior===undefined)delete env.STRIPE_TEST_WEBHOOK_SECRET;else env.STRIPE_TEST_WEBHOOK_SECRET=prior;}
});
await test('Stripe reconciliation checks exact session mapping and journals a missed success once',()=>{
 const p=write('payment','reconcile-payment',{},()=>s.createPayment(s.owner,{product_id:product.id}));s.prepareStripePayment(p.id,'test');s.saveStripeSession(p.id,{id:'cs_test_reconcile',url:'https://checkout.stripe.com/c/pay',payment_intent:'pi_test_reconcile',status:'open'},'test');
 const session={id:'cs_test_reconcile',status:'complete' as const,payment_status:'paid' as const,amount_total:p.amount,currency:'usd',client_reference_id:p.id,payment_intent:'pi_test_reconcile',livemode:false,metadata:{agora_payment_id:p.id,agora_tenant_id:'owner'}};
 assert.throws(()=>s.reconcileStripePayment(p.id,'owner',{...session,amount_total:p.amount+1}),(e:unknown)=>e instanceof s.ApiError&&e.code==='provider_reconcile_mismatch');
 assert.deepEqual(s.reconcileStripePayment(p.id,'owner',session),{id:p.id,status:'succeeded',reconciled:true});assert.deepEqual(s.reconcileStripePayment(p.id,'owner',session),{id:p.id,status:'succeeded',reconciled:false});assert.equal(d.all('SELECT * FROM journal WHERE reference_id=?',p.id).length,2);
 assert.throws(()=>s.stripePaymentReconcileContext(p.id,'different-tenant'),(e:unknown)=>e instanceof s.ApiError&&e.status===404);
});
await test('Standard OAuth state is tenant, mode, redirect, expiry and replay bound; linked account never crosses tenants',()=>{
 const registration=s.registerMerchant({business_name:'OAuth Merchant',owner_name:'Owner',email:'oauth@example.test'});const tenant=d.one<{tenant_id:string}>('SELECT tenant_id FROM registrations WHERE id=?',registration.registration_id)!.tenant_id;s.reviewRegistration(s.owner,{registration_id:registration.registration_id,decision:'approve'});
 const other=s.registerMerchant({business_name:'Second Merchant',owner_name:'Owner',email:'oauth2@example.test'});const otherTenant=d.one<{tenant_id:string}>('SELECT tenant_id FROM registrations WHERE id=?',other.registration_id)!.tenant_id;s.reviewRegistration(s.owner,{registration_id:other.registration_id,decision:'approve'});
 const redirect='https://agora.example/api/provider/stripe/callback';const started=s.beginStripeConnect(s.owner,tenant,'test','ca_testclient',redirect);assert.match(started.authorize_url,/connect\.stripe\.com\/oauth\/authorize/);assert.equal(started.expires_at.length>0,true);
 assert.throws(()=>s.consumeStripeConnectState(started.state,'live',redirect),(e:unknown)=>e instanceof s.ApiError&&e.code==='invalid_oauth_state');
 const consumed=s.consumeStripeConnectState(started.state,'test',redirect);assert.equal(consumed.tenant_id,tenant);
 assert.throws(()=>s.consumeStripeConnectState(started.state,'test',redirect),(e:unknown)=>e instanceof s.ApiError&&e.code==='invalid_oauth_state');
 const connected=s.saveStripeConnectedAccount(tenant,'test',{id:'acct_testoauth1',charges_enabled:true,payouts_enabled:true,details_submitted:true,capabilities:{card_payments:'active'}});assert.equal(connected.status,'connected');assert.equal(s.stripeAccountForTenant(tenant,'test')?.account_id,'acct_testoauth1');assert.equal(s.stripeAccountForTenant(tenant,'live'),null);
 assert.throws(()=>s.saveStripeConnectedAccount(otherTenant,'test',{id:'acct_testoauth1',charges_enabled:true,payouts_enabled:true,details_submitted:true,capabilities:{}}),(e:unknown)=>e instanceof s.ApiError&&e.code==='provider_account_in_use');
});
await test('connected-account webhook must match the linked Stripe account and tenant metadata',()=>{
 const registration=s.registerMerchant({business_name:'Connected Merchant',owner_name:'Owner',email:'connected@example.test'});const tenant=d.one<{tenant_id:string}>('SELECT tenant_id FROM registrations WHERE id=?',registration.registration_id)!.tenant_id;s.reviewRegistration(s.owner,{registration_id:registration.registration_id,decision:'approve'});s.saveStripeConnectedAccount(tenant,'test',{id:'acct_connected123',charges_enabled:true,payouts_enabled:true,details_submitted:true,capabilities:{card_payments:'active'}});
 const product=s.createProduct({...s.owner,tenant_id:tenant},{name:'Merchant item',amount:1250});const merchantPayment=s.createPayment({...s.owner,tenant_id:tenant},{product_id:product.id});s.prepareStripePayment(merchantPayment.id,'test',tenant,'acct_connected123');s.saveStripeSession(merchantPayment.id,{id:'cs_test_connected',url:'https://checkout.stripe.com/c/pay',payment_intent:'pi_test_connected',status:'open'},'test',tenant,'acct_connected123');
 const env=process.env as Record<string,string|undefined>;const prior=env.STRIPE_TEST_WEBHOOK_SECRET;env.STRIPE_TEST_WEBHOOK_SECRET='whsec_connected_test';
 try{const event={id:'evt_connected_good',type:'checkout.session.completed',account:'acct_connected123',livemode:false,data:{object:{id:'cs_test_connected',payment_status:'paid',amount_total:1250,currency:'usd',payment_intent:'pi_test_connected',metadata:{agora_payment_id:merchantPayment.id,agora_tenant_id:tenant}}}};const sign=(value:unknown)=>{const raw=JSON.stringify(value);const timestamp=Math.floor(Date.now()/1000);const sig=createHmac('sha256',env.STRIPE_TEST_WEBHOOK_SECRET!).update(`${timestamp}.${raw}`).digest('hex');return{raw,header:`t=${timestamp},v1=${sig}`};};const wrong=sign({...event,id:'evt_connected_wrong',account:'acct_other'});assert.throws(()=>s.handleStripeWebhook(wrong.raw,wrong.header),(e:unknown)=>e instanceof s.ApiError&&e.code==='webhook_account_mismatch');const valid=sign(event);assert.equal(s.handleStripeWebhook(valid.raw,valid.header).status,'succeeded');assert.equal(d.one<{status:string}>('SELECT status FROM payments WHERE id=? AND tenant_id=?',merchantPayment.id,tenant)?.status,'succeeded');assert.equal(d.all('SELECT * FROM journal WHERE reference_id=? AND tenant_id=?',merchantPayment.id,tenant).length,2);}finally{if(prior===undefined)delete env.STRIPE_TEST_WEBHOOK_SECRET;else env.STRIPE_TEST_WEBHOOK_SECRET=prior;}
});
await test('console rejects cross-site requests',()=>{assert.throws(()=>s.consoleAuth(new Request('http://localhost/api/console',{headers:{host:'localhost',origin:'https://attacker.example','sec-fetch-site':'cross-site'}})));});
function totp(secret:string){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,value=0;const bytes:number[]=[];for(const c of secret){value=(value<<5)|alphabet.indexOf(c);bits+=5;if(bits>=8){bytes.push((value>>>(bits-8))&255);bits-=8;}}const counter=Math.floor(Date.now()/30000);const input=Buffer.alloc(8);input.writeBigUInt64BE(BigInt(counter));const digest=createHmac('sha1',Buffer.from(bytes)).update(input).digest();const offset=digest[digest.length-1]&15;return String((digest.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,'0');}
await test('owner password requires MFA enrollment; replay and recovery-code reuse are rejected',()=>{
 const env=process.env as Record<string,string|undefined>;
 const prior={password:env.AGORA_ADMIN_PASSWORD,token:env.AGORA_ADMIN_TOKEN,nodeEnv:env.NODE_ENV,origin:env.AGORA_PUBLIC_ORIGIN,mfaKey:env.AGORA_MFA_ENCRYPTION_KEY,mfaPrevious:env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS};
 env.AGORA_ADMIN_PASSWORD='correct horse battery staple';env.AGORA_ADMIN_TOKEN='test-only-signing-secret-long-enough-for-auth';env.AGORA_PUBLIC_ORIGIN='https://agora.example';env.AGORA_MFA_ENCRYPTION_KEY=Buffer.alloc(32,7).toString('base64');delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;env.AGORA_OWNER_EMAIL='owner@example.test';env.NODE_ENV='production';
 try{
  const loginRequest=new Request('https://api.example/api/auth/login',{method:'POST',headers:{host:'api.example',origin:'https://agora.example'},body:'{}'});
  const badOrigin=new Request('https://api.example/api/auth/login',{method:'POST',headers:{host:'api.example',origin:'https://attacker.example'},body:'{}'});
  assert.throws(()=>s.beginAdminLogin(badOrigin,{password:'wrong'}));
  const setup=s.beginAdminLogin(loginRequest,{password:env.AGORA_ADMIN_PASSWORD});assert.equal(setup.stage,'enroll');
  const pending=s.setMfaCookie(new Response(null),loginRequest,'pending',setup.cookie).headers.get('set-cookie')!.split(';')[0];
  const pendingRequest=new Request('https://api.example/api/auth/mfa/enroll',{method:'POST',headers:{host:'api.example',origin:'https://agora.example',cookie:pending}});
  assert.throws(()=>s.consoleAuth(pendingRequest,true));
  const enrolled=s.enrollAdminMfa(pendingRequest,{code:totp(setup.secret)});assert.equal(enrolled.recovery_codes.length,10);const oldKey=env.AGORA_MFA_ENCRYPTION_KEY!,newKey=Buffer.alloc(32,8).toString('base64');env.AGORA_MFA_ENCRYPTION_KEY=newKey;env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS=oldKey;assert.deepEqual(s.migrateMfaEncryptionKeys(),{migrated:1,remaining_old:0});delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;
  const ownerCookieHeader=s.setSessionCookie(new Response(null),loginRequest,enrolled.cookie).headers.get('set-cookie')!;assert.match(ownerCookieHeader,/SameSite=Lax/);const session=ownerCookieHeader.split(';')[0];assert.match(s.setMfaCookie(new Response(null),loginRequest,'pending',setup.cookie).headers.get('set-cookie')||'',/SameSite=Strict/);
  assert.equal(s.hasAdminSession(new Request('https://api.example/api/auth/session',{headers:{host:'api.example',cookie:session}})),true);
  const consoleRequest=new Request('https://api.example/api/console',{headers:{host:'api.example',cookie:session,origin:'https://agora.example'}});assert.equal(s.consoleAuth(consoleRequest).id,'console_owner');s.logout(consoleRequest);assert.equal(s.hasAdminSession(new Request('https://api.example/api/auth/session',{headers:{host:'api.example',cookie:session}})),false);
  const second=s.beginAdminLogin(loginRequest,{password:env.AGORA_ADMIN_PASSWORD});assert.equal(second.stage,'verify');
  const verifyRequest=new Request('https://api.example/api/auth/mfa/verify',{method:'POST',headers:{host:'api.example',origin:'https://agora.example',cookie:s.setMfaCookie(new Response(null),loginRequest,'pending',second.cookie).headers.get('set-cookie')!.split(';')[0]}});
  assert.throws(()=>s.verifyAdminMfa(verifyRequest,{code:totp(setup.secret)}),(e:unknown)=>e instanceof s.ApiError&&e.code==='invalid_mfa_code');
  const recovery=enrolled.recovery_codes[0];const verified=s.verifyAdminMfa(verifyRequest,{recovery_code:recovery});assert.ok(verified.cookie.value);
  const next=s.beginAdminLogin(loginRequest,{password:env.AGORA_ADMIN_PASSWORD});const nextRequest=new Request('https://api.example/api/auth/mfa/verify',{method:'POST',headers:{host:'api.example',origin:'https://agora.example',cookie:s.setMfaCookie(new Response(null),loginRequest,'pending',next.cookie).headers.get('set-cookie')!.split(';')[0]}});
  assert.throws(()=>s.verifyAdminMfa(nextRequest,{recovery_code:recovery}),(e:unknown)=>e instanceof s.ApiError&&e.code==='invalid_mfa_code');
 }finally{
  if(prior.password===undefined)delete env.AGORA_ADMIN_PASSWORD;else env.AGORA_ADMIN_PASSWORD=prior.password;
  if(prior.token===undefined)delete env.AGORA_ADMIN_TOKEN;else env.AGORA_ADMIN_TOKEN=prior.token;
  if(prior.nodeEnv===undefined)delete env.NODE_ENV;else env.NODE_ENV=prior.nodeEnv;
  if(prior.origin===undefined)delete env.AGORA_PUBLIC_ORIGIN;else env.AGORA_PUBLIC_ORIGIN=prior.origin;
  if(prior.mfaKey===undefined)delete env.AGORA_MFA_ENCRYPTION_KEY;else env.AGORA_MFA_ENCRYPTION_KEY=prior.mfaKey;
  if(prior.mfaPrevious===undefined)delete env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS;else env.AGORA_MFA_ENCRYPTION_KEY_PREVIOUS=prior.mfaPrevious;
 }
});
d.db.close();rmSync(dir,{recursive:true,force:true});
