import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHmac} from 'node:crypto';
const dir=mkdtempSync(join(tmpdir(),'agora-risk-'));const env=process.env as Record<string,string|undefined>;env.AGORA_DATABASE_PATH=join(dir,'risk.sqlite');env.AGORA_SEED='false';env.AGORA_DEPLOYMENT_ENV='qa';env.AGORA_PAYMENT_PROVIDER='stripe';env.AGORA_STRIPE_MODE='test';env.AGORA_SECRETS_ENCRYPTION_KEY=Buffer.alloc(32,91).toString('base64');env.AGORA_MFA_ENCRYPTION_KEY=env.AGORA_SECRETS_ENCRYPTION_KEY;const webhookSecret='whsec_riskfixture';
const local=await import('../lib/server/local');const db=await import('../lib/server/db');
local.setStripeConfig({provider:'stripe',mode:'test',public_origin:'https://risk.example',test_secret_key:'sk_test_riskfixture123',test_webhook_secret:webhookSecret});
const product=local.createProduct(local.owner,{name:'Risk fixture',amount:1200});const payment=local.createPayment(local.owner,{product_id:product.id});
function deliver(type:string,id:string,object:Record<string,unknown>,livemode=false,account?:string):Record<string,unknown>{const timestamp=Math.floor(Date.now()/1000).toString();const raw=JSON.stringify({id,type,livemode,...(account?{account}:{}),data:{object}});const digest=createHmac('sha256',webhookSecret).update(`${timestamp}.${raw}`).digest('hex');return local.handleStripeWebhook(raw,`t=${timestamp},v1=${digest}`) as Record<string,unknown>;}
await test('verified checkout webhook stores the PaymentIntent used to map later Radar signals',()=>{const result=deliver('checkout.session.completed','evt_checkout_fixture',{id:'cs_test_riskfixture',object:'checkout.session',amount_total:payment.amount,currency:'usd',payment_status:'paid',status:'complete',payment_intent:'pi_test_riskfixture',client_reference_id:payment.id,metadata:{agora_payment_id:payment.id,agora_tenant_id:'owner'}});assert.equal(result.status,'succeeded');assert.equal(db.one<{provider_payment_intent:string}>('SELECT provider_payment_intent FROM payments WHERE id=?',payment.id)?.provider_payment_intent,'pi_test_riskfixture');});
await test('Radar early fraud warnings and reviews are minimally projected and mode/account/tenant scoped',()=>{const warning=deliver('radar.early_fraud_warning.created','evt_warning_fixture',{id:'issfr_fixture',object:'radar.early_fraud_warning',payment_intent:'pi_test_riskfixture',charge:'ch_fixture',livemode:false,actionable:true,fraud_type:'made_with_stolen_card',created:1_700_000_000});assert.equal(warning.risk_signal,'recorded');const opened=deliver('review.opened','evt_review_opened',{id:'prv_fixture',object:'review',payment_intent:'pi_test_riskfixture',livemode:false,open:true,reason:'rule',created:1_700_000_001});assert.equal(opened.risk_signal,'recorded');const closed=deliver('review.closed','evt_review_closed',{id:'prv_fixture',object:'review',payment_intent:'pi_test_riskfixture',livemode:false,open:false,reason:'approved',created:1_700_000_001});assert.equal(closed.risk_signal,'recorded');const unmapped=deliver('radar.early_fraud_warning.created','evt_wrong_account',{id:'issfr_other',object:'radar.early_fraud_warning',payment_intent:'pi_test_riskfixture',livemode:false,actionable:true,fraud_type:'misc',created:1_700_000_002},false,'acct_unrelated');assert.equal(unmapped.risk_signal,'unmapped');const result=local.listStripeRiskSignals(local.owner,'test');assert.equal(result.status,'ready');assert.equal(result.data.length,2);const fraud=result.data.find((item)=>item.kind==='early_fraud_warning')!;assert.equal(fraud.payment_id,payment.id);assert.equal(fraud.state,'actionable');assert.equal(fraud.actionable,true);assert.equal(fraud.fraud_type,'made_with_stolen_card');const review=result.data.find((item)=>item.kind==='review')!;assert.equal(review.state,'closed');assert.equal(review.reason,'approved');assert.equal(JSON.stringify(result).includes('ch_fixture'),false);assert.equal(JSON.stringify(result).includes('acct_unrelated'),false);assert.equal(db.one<{n:number}>('SELECT COUNT(*) AS n FROM stripe_risk_signals')?.n,2);});
await test('invalid mode and unrelated signed events never project risk',()=>{assert.throws(()=>deliver('radar.early_fraud_warning.updated','evt_live_mismatch',{id:'issfr_bad',payment_intent:'pi_test_riskfixture',livemode:true,actionable:true,fraud_type:'misc',created:1_700_000_003},true),(error:unknown)=>error instanceof local.ApiError&&error.code==='webhook_mode_mismatch');const result=deliver('charge.refunded','evt_unhandled_fixture',{id:'ch_unknown',object:'charge',livemode:false});assert.equal(result.ignored,true);assert.equal(db.one<{n:number}>('SELECT COUNT(*) AS n FROM stripe_risk_signals')?.n,2);});
rmSync(dir,{recursive:true,force:true});
