import { transaction, id } from '@/lib/server/db';
import { ApiError, bodyOf, consoleAuth, createCredential, createMerchantInvite, createPayment, createProduct, createRefund, createCustomer, createQuote, quoteShareUrl, transitionFulfillment, updateProduct, mutate, prepareStripePayment, resolveApproval, responseError, revokeCredential, reviewRegistration, saveStripeSession, snapshot, stripeAccountForTenant, paymentProviderReadiness } from '@/lib/server/local';
import { createStripeCheckout, stripeApiKeyMatchesMode } from '@/lib/server/stripe';
import { submitStripeRefund } from '@/lib/server/stripe-runtime';
import { stripeRuntimeEnvironment } from '@/lib/server/local';
import { publicPayment } from '@/lib/server/public-payment';
export const runtime='nodejs';export const dynamic='force-dynamic';
export async function GET(request:Request){const requestId=id('req');try{const actor=consoleAuth(request);const includeArchived=actor.tenant_id==='owner'&&new URL(request.url).searchParams.get('include_archived')==='1';return Response.json(snapshot(actor.tenant_id,includeArchived),{headers:{'Cache-Control':'no-store'}})}catch(e){return responseError(e,requestId)}}
export async function POST(request:Request){const requestId=id('req');try{const actor=consoleAuth(request,true);const env=stripeRuntimeEnvironment();const b=await bodyOf(request) as {action:string;payload:unknown};if((b.action==='create_payment'||b.action==='accept_quote')&&!paymentProviderReadiness().checkout_enabled)throw new ApiError(503,'provider_not_configured','Payment acceptance is unavailable until processor setup is complete.');const handlers:Record<string,()=>unknown>={create_product:()=>createProduct(actor,b.payload),create_customer:()=>createCustomer(actor,b.payload),create_quote:()=>createQuote(actor,b.payload),create_payment:()=>createPayment(actor,b.payload),update_product:()=>{const payload=b.payload as {product_id?:string;expected_version?:number;name?:string;description?:string;amount?:number};if(typeof payload.product_id!=='string')throw new ApiError(422,'invalid_request','Provide a product_id.');const {product_id,...input}=payload;return updateProduct(actor,product_id,input);},claim_fulfillment:()=>{const payload=b.payload as {id?:string};if(typeof payload.id!=='string')throw new ApiError(422,'invalid_request','Provide a fulfillment id.');return transitionFulfillment(actor,payload.id,'claim',{});},complete_fulfillment:()=>{const payload=b.payload as {id?:string;note?:string};if(typeof payload.id!=='string')throw new ApiError(422,'invalid_request','Provide a fulfillment id.');return transitionFulfillment(actor,payload.id,'complete',{note:payload.note});},fail_fulfillment:()=>{const payload=b.payload as {id?:string;note?:string};if(typeof payload.id!=='string')throw new ApiError(422,'invalid_request','Provide a fulfillment id.');return transitionFulfillment(actor,payload.id,'fail',{note:payload.note});},retry_fulfillment:()=>{const payload=b.payload as {id?:string;note?:string};if(typeof payload.id!=='string')throw new ApiError(422,'invalid_request','Provide a fulfillment id.');return transitionFulfillment(actor,payload.id,'retry',{note:payload.note});},refund:()=>createRefund(actor,b.payload),resolve_approval:()=>resolveApproval(actor,b.payload),revoke_key:()=>revokeCredential(actor,b.payload)};let result:unknown;
 if(b.action==='review_registration')result=reviewRegistration(actor,b.payload);
 else if(b.action==='create_invite'){if(actor.tenant_id!=='owner')throw new ApiError(403,'permission_denied','Only the owner can issue merchant invitations.');const payload=b.payload as {tenant_id?:unknown};if(typeof payload?.tenant_id!=='string')throw new ApiError(422,'invalid_request','Provide a merchant workspace ID.');const origin=env.AGORA_PUBLIC_ORIGIN;if(!origin)throw new ApiError(503,'auth_not_configured','Set AGORA_PUBLIC_ORIGIN before issuing invitations.');const invite=createMerchantInvite(actor,payload.tenant_id);result={email:invite.email,expires_at:invite.expires_at,invite_url:`${origin}/invite#${invite.token}`};}
 else if(b.action==='create_payment'&&(env.AGORA_PAYMENT_PROVIDER as string)==='stripe'){const payment=mutate(actor,b.action,request.headers.get('idempotency-key'),b.payload,()=>createPayment(actor,b.payload)) as ReturnType<typeof createPayment>;const mode=env.AGORA_STRIPE_MODE;if(mode!=='test'&&mode!=='live')throw new ApiError(503,'provider_not_configured','Set AGORA_STRIPE_MODE to test or live.');const secretKey=mode==='live'?env.STRIPE_LIVE_SECRET_KEY:env.STRIPE_TEST_SECRET_KEY;if(!secretKey||!stripeApiKeyMatchesMode(secretKey,mode))throw new ApiError(503,'provider_not_configured',`Set a mode-matched STRIPE_${mode.toUpperCase()}_SECRET_KEY before enabling Stripe Checkout.`);const configured=env.AGORA_PUBLIC_ORIGIN;if(!configured)throw new ApiError(503,'provider_not_configured','Set AGORA_PUBLIC_ORIGIN before enabling Stripe Checkout.');const connected=actor.tenant_id==='owner'?null:stripeAccountForTenant(actor.tenant_id,mode);if(actor.tenant_id!=='owner'&&(!connected||connected.status!=='connected'||!connected.charges_enabled))throw new ApiError(409,'merchant_connection_required','This merchant must connect its own Stripe account before processor payments are enabled.');prepareStripePayment(payment.id,mode,actor.tenant_id,connected?.account_id||null);const session=await createStripeCheckout(secretKey,{amount:payment.amount,currency:'usd',productName:payment.product_name,paymentId:payment.id,tenantId:actor.tenant_id,successUrl:`${configured}/checkout/complete?payment_id=${encodeURIComponent(payment.id)}&session_id={CHECKOUT_SESSION_ID}`,cancelUrl:`${configured}/checkout/cancel?payment_id=${encodeURIComponent(payment.id)}`,idempotencyKey:`agora-checkout-${payment.id}`,...(connected?{stripeAccountId:connected.account_id}:{})});saveStripeSession(payment.id,session,mode,actor.tenant_id,connected?.account_id||null);const {checkout_token,...safePayment}=payment;result={...safePayment,checkout_url:`${configured}/checkout/start#${checkout_token}`,provider:'stripe',provider_mode:mode};}
 else
 if(b.action==='create_key'){let secret:string|undefined;result=mutate(actor,b.action,request.headers.get('idempotency-key'),b.payload,()=>{const c=createCredential(actor,b.payload);secret=c.secret;const {secret:_,...metadata}=c;return metadata;});if(secret)result={...result as object,secret};}
 else{const fn=handlers[b.action];if(!fn)throw new ApiError(400,'invalid_action','Unknown action.');result=mutate(actor,b.action,request.headers.get('idempotency-key'),b.payload,fn);const value=result as {id?:string;quote_token?:unknown;status?:string;provider?:string;refund?:{id:string;status:string;provider?:string}};if(b.action==='create_quote'){const {quote_token:_token,...safe}=value;const quote_url=quoteShareUrl(actor,value.id!,env.AGORA_PUBLIC_ORIGIN||new URL(request.url).origin);result={...safe,...(quote_url?{quote_url,quote_link_available:true}:{quote_link_available:false})};}if(b.action==='refund'&&value.status==='pending'&&value.provider==='stripe')result={...value,...await submitStripeRefund(value.id!,actor.tenant_id)};if(b.action==='resolve_approval'&&value.refund?.status==='pending'&&value.refund.provider==='stripe')result={...value,refund:{...value.refund,...await submitStripeRefund(value.refund.id,actor.tenant_id)}};if(b.action==='create_payment')result=publicPayment(result as ReturnType<typeof createPayment>,env.AGORA_PUBLIC_ORIGIN||new URL(request.url).origin);}
 return Response.json(result,{headers:{'Cache-Control':'no-store'}});
 }catch(e){return responseError(e,requestId)}}
