import { id } from '@/lib/server/db';
import { ApiError, bodyOf, consoleAuth, responseError, paymentProviderReadiness, setStripeConfig, stripeConfigSummary, stripeSecret } from '@/lib/server/local';
import { testStripeApiKey } from '@/lib/server/stripe';

export const runtime='nodejs';
export const dynamic='force-dynamic';
function requireOwner(request:Request,write=false){const actor=consoleAuth(request,write);if(actor.tenant_id!=='owner')throw new ApiError(403,'permission_denied','Only the workspace owner can configure Stripe.');}
export async function GET(request:Request){const requestId=id('req');try{requireOwner(request);return Response.json({...stripeConfigSummary(),...paymentProviderReadiness()},{headers:{'Cache-Control':'no-store','X-Request-Id':requestId}});}catch(error){return responseError(error,requestId);}}
export async function PATCH(request:Request){const requestId=id('req');try{requireOwner(request,true);const body=await bodyOf(request);const requestedOrigin=body&&typeof body==='object'?(body as {public_origin?:unknown}).public_origin:undefined;const requestOrigin=request.headers.get('origin');if(typeof requestedOrigin==='string'&&requestOrigin&&new URL(requestedOrigin).origin!==requestOrigin)throw new ApiError(422,'origin_mismatch','Public app URL must match the origin used to sign in.');const result=setStripeConfig(body);return Response.json({...result,...paymentProviderReadiness()},{headers:{'Cache-Control':'no-store','X-Request-Id':requestId}});}catch(error){return responseError(error,requestId);}}
export async function POST(request:Request){const requestId=id('req');try{requireOwner(request,true);const body=await bodyOf(request) as {action?:unknown;mode?:unknown};if(body.action!=='test'||(body.mode!=='test'&&body.mode!=='live'))throw new ApiError(422,'invalid_request','Provide action test and mode test or live.');const mode=body.mode;const secret=stripeSecret(mode,'api');if(!secret)throw new ApiError(409,'stripe_key_missing',`Configure a Stripe ${mode} API key first.`);const account=await testStripeApiKey(secret,mode);const config=stripeConfigSummary().configured[mode];return Response.json({ok:true,mode,account_id:account.account_id,webhook:{configured:config.webhook_secret,verified:config.webhook_verified},message:config.webhook_verified?'Stripe credentials and webhook delivery are verified.':'Stripe credentials work. Send a signed account.updated test event to verify webhook delivery.'},{headers:{'Cache-Control':'no-store','X-Request-Id':requestId}});}catch(error){return responseError(error,requestId);}}
