import { acceptPublicQuote, ApiError, bodyOf, mutate, responseError, saveStripeSession, prepareStripePayment, stripeAccountForTenant, stripeRuntimeEnvironment, reviewPublicQuote } from '@/lib/server/local';
import { id } from '@/lib/server/db';
import { createStripeCheckout, stripeApiKeyMatchesMode } from '@/lib/server/stripe';
import { publicPayment } from '@/lib/server/public-payment';

export const runtime='nodejs';
export const dynamic='force-dynamic';

export async function POST(request:Request){const requestId=id('req');try{const input=await bodyOf(request) as {token?:unknown};if(typeof input?.token!=='string')throw new ApiError(404,'not_found','Quote not found.');const reviewed=reviewPublicQuote(input.token);const env=stripeRuntimeEnvironment();const result=mutate({id:`public_quote_customer:${reviewed.guard.tenant_id}`,name:'Customer quote acceptance',scopes:['*'],tenant_id:reviewed.guard.tenant_id},'public_quote_accept',request.headers.get('idempotency-key'),{token:input.token},()=>acceptPublicQuote(input.token as string)) as ReturnType<typeof acceptPublicQuote>;const payment=result.payment;let publicResult:unknown;
 if(env.AGORA_PAYMENT_PROVIDER==='stripe'){const mode=env.AGORA_STRIPE_MODE;if(mode!=='test'&&mode!=='live')throw new ApiError(503,'provider_not_configured','Stripe Checkout is not configured for this quote.');const secret=mode==='live'?env.STRIPE_LIVE_SECRET_KEY:env.STRIPE_TEST_SECRET_KEY;const origin=env.AGORA_PUBLIC_ORIGIN;if(!secret||!stripeApiKeyMatchesMode(secret,mode)||!origin)throw new ApiError(503,'provider_not_configured','Stripe Checkout is not configured for this quote.');const connected=result.payment.tenant_id==='owner'?null:stripeAccountForTenant(result.payment.tenant_id,mode);if(result.payment.tenant_id!=='owner'&&(!connected||connected.status!=='connected'||!connected.charges_enabled))throw new ApiError(409,'merchant_connection_required','The seller’s Stripe account is unavailable.');prepareStripePayment(payment.id,mode,payment.tenant_id,connected?.account_id||null);const lineItems=result.items.filter(item=>item.net_total>0).map(item=>({name:`${item.product_name} × ${item.quantity}`,amount:item.net_total}));const session=await createStripeCheckout(secret,{amount:payment.amount,currency:'usd',productName:payment.product_name,lineItems,paymentId:payment.id,tenantId:payment.tenant_id,successUrl:`${origin}/checkout/complete?payment_id=${encodeURIComponent(payment.id)}&session_id={CHECKOUT_SESSION_ID}`,cancelUrl:`${origin}/checkout/cancel?payment_id=${encodeURIComponent(payment.id)}`,idempotencyKey:`agora-checkout-${payment.id}`,stripeAccountId:connected?.account_id});saveStripeSession(payment.id,session,mode,payment.tenant_id,connected?.account_id||null);publicResult={...result,payment:publicPayment({...payment,provider:'stripe',provider_mode:mode},origin)};
 }else publicResult={...result,payment:publicPayment(payment,env.AGORA_PUBLIC_ORIGIN||new URL(request.url).origin)};
 return Response.json(publicResult,{headers:{'Cache-Control':'no-store, private','Referrer-Policy':'no-referrer'}});
 }catch(error){return responseError(error,requestId)}}
